package astromath

// SabianSymbol returns the Sabian symbol for a given ecliptic longitude.
// Based on Marc Edmund Jones (1925) / Dane Rudhyar "An Astrological Mandala" (1973).
// Index 0 = Aries 1° (0°00'-0°59'), ... 359 = Pisces 30°.
func SabianSymbol(lon float64) string {
	idx := int(Normalize360(lon))
	if idx < 0 || idx >= len(sabianSymbols) {
		return ""
	}
	return sabianSymbols[idx]
}

// SabianDegree returns the formatted degree label for a longitude.
// e.g., lon=45.5 → "Tauro 16°"
func SabianDegree(lon float64) string {
	lon = Normalize360(lon)
	signIdx := int(lon / 30)
	deg := int(lon) - signIdx*30 + 1
	return Signs[signIdx] + " " + sabianItoa(deg) + "°"
}

func sabianItoa(n int) string {
	if n < 10 {
		return string(rune('0'+n))
	}
	return string(rune('0'+n/10)) + string(rune('0'+n%10))
}

// SabianResult holds a planet's Sabian symbol info.
type SabianResult struct {
	Planet string `json:"planet"`
	Degree string `json:"degree"` // "Tauro 16°"
	Symbol string `json:"symbol"`
}

// sabianSymbols contains the 360 Sabian symbols indexed by ecliptic degree.
var sabianSymbols = [360]string{
	// ── ARIES (0-29) ──
	"A woman rises out of water, a seal rises and embraces her",
	"A comedian entertaining a group",
	"A cameo profile of a man in the outline of his country",
	"Two lovers strolling through a secluded walk",
	"A triangle with wings",
	"A square brightly lighted on one side",
	"A man succeeding in expressing himself simultaneously in two realms",
	"A woman's hat with streamers blown by the east wind",
	"A crystal gazer",
	"A man teaching new forms for old symbols",
	"The president of the country",
	"A flock of wild geese",
	"An unexploded bomb reveals an unsuccessful social protest",
	"A serpent coiling near a man and a woman",
	"An Indian weaving a blanket",
	"Brownies dancing in the setting sun",
	"Two prim spinsters",
	"An empty hammock",
	"The magic carpet",
	"A young girl feeding birds in winter",
	"A pugilist entering the ring",
	"The gate to the garden of all fulfilled desires",
	"A pregnant woman in light summer dress",
	"An open window and a net curtain blowing into a cornucopia",
	"A double promise reveals its inner and outer meanings",
	"A man possessed of more gifts than he can hold",
	"Through imagination a lost opportunity is regained",
	"A large audience confronts the performer who disappointed its expectations",
	"The music of the spheres",
	"A duck pond and its brood",
	// ── TAURUS (30-59) ──
	"A clear mountain stream",
	"An electrical storm",
	"Natural steps lead to a lawn of clover in bloom",
	"The pot of gold at the end of the rainbow",
	"A widow at an open grave",
	"A bridge being built across a gorge",
	"The woman of Samaria at the ancestral well",
	"A sleigh on land uncovered by snow",
	"A fully decorated Christmas tree",
	"A Red Cross nurse",
	"A woman watering flowers in her garden",
	"A young couple window-shopping",
	"A porter carrying heavy baggage",
	"On the beach, children play while shellfish grope at the edge of the water",
	"A man with a rakish silk hat, muffled against the cold, braves a storm",
	"An old teacher fails to interest his pupils in traditional knowledge",
	"A battle between the swords and the torches",
	"A woman airing an old bag through a sunny window",
	"A new continent rising out of the ocean",
	"Wisps of winglike clouds streaming across the sky",
	"A finger pointing in an open book",
	"White dove over troubled waters",
	"A jewelry shop filled with the most magnificent jewels",
	"An Indian warrior riding fiercely, human scalps hanging at his belt",
	"A vast public park",
	"A Spanish gallant serenades his beloved",
	"An old Indian woman selling the artifacts of her tribe to passersby",
	"A woman in middle life stands in rapt sudden realization of forgotten charms",
	"Two cobblers working at a table",
	"A peacock parading on an ancient lawn",
	// ── GEMINI (60-89) ──
	"A glass-bottomed boat in still water",
	"Santa Claus filling stockings furtively",
	"The garden of the Tuileries in Paris",
	"Holly and mistletoe bring Christmas spirit to a home",
	"A revolutionary magazine asking for action",
	"Workmen drilling for oil",
	"A well with bucket and rope under the shade of majestic trees",
	"Aroused strikers round a factory",
	"A quiver filled with arrows",
	"An airplane performing a nosedive",
	"Newly opened lands offer the pioneer new opportunities for experience",
	"A black slave-girl demands her rights of her mistress",
	"A great musician at his piano",
	"A conversation between two men on a bridge",
	"Two Dutch children talking to each other, exchanging their knowledge",
	"A woman activist in an emotional speech dramatizing her cause",
	"The head of a robust youth changes into that of a mature thinker",
	"Two Chinese men talking Chinese in a Western crowd",
	"A large archaic volume reveals a traditional wisdom",
	"A modern cafeteria displays an abundance of food, products of various regions",
	"A tumultuous labor demonstration",
	"Dancing couples in a harvest festival",
	"Three fledglings in a nest high in a tree",
	"Children skating on ice",
	"A gardener trimming large palm trees",
	"Frost-covered trees against winter skies",
	"A gypsy coming out of the forest",
	"Bankruptcy granted to him, a man leaves the court with mixed feelings",
	"The first mockingbird of spring",
	"A parade of bathing beauties before large beach crowds",
	// ── CANCER (90-119) ──
	"On a ship the sailors lower an old flag and raise a new one",
	"A man on a magic carpet observes vast vistas below him",
	"An arctic explorer leads a reindeer through icy canyons",
	"A cat arguing with a mouse",
	"An automobile wrecked by a train",
	"Game birds feathering their nests",
	"Two nature spirits dancing under the moonlight",
	"A group of rabbits dressed in human clothes walk as if on parade",
	"A small, naked girl bends over a pond trying to catch a fish",
	"A large diamond in the first stages of the cutting process",
	"A clown caricaturing well-known personalities",
	"A Chinese woman nursing a baby whose aura reveals him to be the reincarnation of a great teacher",
	"A hand with a prominent thumb is held out for study",
	"A very old man facing a vast dark space to the northeast",
	"A group of people who have overeaten and enjoyed it",
	"A man studying a mandala in front of him, with the help of a very ancient book",
	"The unfoldment of multilevel potentialities of any germ growth",
	"A hen scratching the ground to find nourishment for her progeny",
	"A priest performing a marriage ceremony",
	"Venetian gondoliers giving a serenade",
	"A famous singer is proving her virtuosity during an operatic performance",
	"A young woman awaiting a sailboat",
	"The meeting of a literary society",
	"A woman and two men castaways on a small island of the South Seas",
	"A will-o'-the-wisp leading men over a swamp",
	"Guests are reading in the library of a luxurious home",
	"A violent storm in a canyon filled with expensive homes",
	"An Indian girl introduces her white lover to her assembled tribe",
	"A Greek muse weighing newborn twins in golden scales",
	"A daughter of the American Revolution",
	// ── LEO (120-149) ──
	"Blood rushes to a man's head as his vital energies are mobilized under the spur of ambition",
	"An epidemic of mumps",
	"A middle-aged woman, her long hair flowing over her shoulders and in a braless youthful garment",
	"A formal ball at the embassy",
	"Rock formations tower over a deep canyon",
	"A conservative, old-fashioned lady is confronted by a hippie girl",
	"The constellations of stars shine brilliantly in the night sky",
	"A communist activist spreading his revolutionary ideals",
	"Glass blowers shape beautiful vases with their controlled breathing",
	"Early morning dew",
	"Children play on a swing hanging from the branches of a huge oak tree",
	"An evening party of adults on a lawn illumined by fancy lanterns",
	"An old sea captain rocking on the porch of his cottage",
	"A human soul seeking opportunities for outward manifestation",
	"A pageant, with its spectacular floats, moves along a street crowded with cheering people",
	"The storm ended, all nature rejoices in brilliant sunshine",
	"A volunteer church choir singing religious hymns",
	"A chemist conducts an experiment for his students",
	"A houseboat party",
	"Zuni Indians perform a ritual to the sun",
	"Intoxicated chickens dizzily flap their wings trying to fly",
	"A carrier pigeon fulfilling its mission",
	"In a circus the bareback rider displays her dangerous skill",
	"Totally concentrated upon inner spiritual attainment, a man is sitting in a state of complete neglect of bodily appearance and cleanliness",
	"A large camel is seen crossing a vast and forbidding desert",
	"After the heavy storm, a rainbow",
	"The luminescence of dawn in the eastern sky",
	"Many little birds on a limb of a large tree",
	"A mermaid emerges from the ocean waves ready for rebirth in human form",
	"An unsealed letter",
	// ── VIRGO (150-179) ──
	"A man's head",
	"A large white cross dominates the landscape",
	"Two guardian angels",
	"Black and white children play together happily",
	"A man becoming aware of nature spirits and normally unseen spiritual agencies",
	"A merry-go-round",
	"A harem",
	"A five-year-old child takes a first dancing lesson",
	"An expressionist painter at work",
	"Two heads looking out and beyond the shadows",
	"In her baby a mother sees her deep longing for a son answered",
	"After the wedding, the groom snatches the veil away from his bride",
	"A powerful statesman overcomes a state of political hysteria",
	"An aristocratic family tree",
	"A fine lace ornamental handkerchief",
	"In the zoo, children are brought face to face with an orangutan",
	"A volcanic eruption",
	"A ouija board",
	"A swimming race",
	"A caravan of cars headed to the West Coast",
	"A girls' basketball team",
	"A royal coat of arms enriched with precious stones",
	"A lion tamer displays his skill and courage",
	"Mary and her little lamb",
	"A flag at half-mast in front of a public building",
	"A boy with a censer serves the priest near the altar",
	"A group of aristocratic ladies meet ceremonially at a court function",
	"A baldheaded man who has seized power",
	"A seeker after occult knowledge is reading an ancient scroll which illumines his mind",
	"Totally intent upon completing an immediate task, a man is deaf to any allurement",
	// ── LIBRA (180-209) ──
	"In a collection of perfect specimens of many biological forms, a butterfly displays the beauty of its wings, its body impaled by a fine dart",
	"The transmutation of the fruits of past experiences into the seed-realizations of the forever creative spirit",
	"The dawn of a new day reveals everything changed",
	"Around a campfire a group of young people sit in spiritual communion",
	"A man revealing to his students the foundation of an inner knowledge of the new world",
	"A man watches his ideals being concretized before his inner vision",
	"A woman feeding chickens and protecting them from the hawks",
	"A blazing fireplace in a deserted home",
	"Three old masters hanging in a special room of an art gallery",
	"Having passed through narrow rapids, a canoe reaches calm waters",
	"A professor peering over his glasses at his students",
	"Miners are surfacing from a deep coal mine",
	"Children blowing soap bubbles",
	"In the heat of the noon hour a man takes a siesta",
	"Circular paths",
	"After a storm a boat landing stands in need of reconstruction",
	"A retired sea captain watches ships entering and leaving the harbor",
	"Two men placed under arrest",
	"A gang of robbers in hiding",
	"A rabbi performing his duties",
	"A crowd upon the beach",
	"A child giving birds a drink at a fountain",
	"Chanticleer's voice heralds the rising sun with exuberant tones",
	"A butterfly with a third wing on its left side",
	"Information in the symbol of an autumn leaf",
	"An eagle and a large white dove change into each other",
	"An airplane sails, high in the clear sky",
	"A man becoming aware of spiritual forces surrounding and assisting him",
	"Mankind's vast and enduring effort to reach for knowledge transferable from generation to generation",
	"Three mounds of knowledge on a philosopher's head",
	// ── SCORPIO (210-239) ──
	"A sight-seeing bus",
	"A broken bottle and spilled perfume",
	"A house-raising",
	"A youth carrying a lighted candle in a devotional ritual",
	"A massive rocky shore resists the pounding of the sea",
	"The gold rush tears men away from their native soil",
	"Deep-sea divers",
	"A calm lake bathed in moonlight",
	"A dentist at work",
	"A fellowship supper reunites old comrades",
	"A drowning man is being rescued",
	"An embassy ball",
	"An inventor performs a laboratory experiment",
	"Telephone linemen at work installing new connections",
	"Children playing around five mounds of sand",
	"A girl's face breaking into a smile",
	"A woman, fecundated by her own spirit, is 'great with child'",
	"A path through woods brilliant with multicolored splendor",
	"A parrot listening and then talking, repeats a conversation he has overheard",
	"A woman draws away two dark curtains closing the entrance to a sacred pathway",
	"Obeying his conscience, a soldier resists orders",
	"Hunters shooting wild ducks",
	"A rabbit metamorphoses into a nature spirit",
	"Crowds coming down the mountain to listen to one inspired man",
	"An X-ray photograph",
	"Indians making camp after moving into a new territory",
	"A military band marches noisily on through the city streets",
	"The king of the fairies approaching his domain",
	"An Indian woman pleading to the chief for the lives of her children",
	"Children in Halloween costumes indulge in various pranks",
	// ── SAGITTARIUS (240-269) ──
	"Retired army veterans gather to reawaken old memories",
	"The ocean covered with whitecaps",
	"Two men playing chess",
	"A little child learning to walk with the encouragement of his parents",
	"An old owl sits alone on the branch of a large tree",
	"A game of cricket",
	"Cupid knocking at the door of a human heart",
	"Within the depths of the earth new elements are being formed",
	"A mother leads her small child step by step up a steep stairway",
	"A theatrical representation of a golden-haired goddess of opportunity",
	"In the left section of an archaic temple, a lamp burns in a container shaped like a human body",
	"A flag that turns into an eagle that crows",
	"A widow's past is brought to light",
	"The great Pyramid and the Sphinx",
	"The ground hog looking for its shadow on Ground Hog Day",
	"Sea gulls fly around a ship in expectation of food",
	"An Easter sunrise service draws a large crowd",
	"Tiny children in sunbonnets",
	"Pelicans menaced by the behavior and refuse of men seek safer areas for bringing up their young",
	"In an old-fashioned northern village a clear and frosty night brings out the finest qualities of the people",
	"A child and a dog wearing borrowed eyeglasses",
	"A Chinese laundry",
	"A group of immigrants as they fulfill the requirements of entrance into the new country",
	"A bluebird perched on the gate of a cottage",
	"A chubby boy on a hobbyhorse",
	"A flag-bearer in a battle",
	"A sculptor at his work",
	"An old bridge over a beautiful stream is still in constant use",
	"A fat boy mowing the lawn of his house on an elegant suburban street",
	"The Pope blessing the faithful",
	// ── CAPRICORN (270-299) ──
	"An Indian chief claims power from the assembled tribe",
	"Three rose windows in a Gothic church, one damaged by war",
	"A human soul, in its eagerness for new experiences, seeks embodiment",
	"A group of people outfitting a large canoe at the start of a journey by water",
	"Indians on the warpath. While some men row a well-filled canoe, others in it perform a war dance",
	"Ten logs lie under an archway leading to darker woods",
	"A veiled prophet speaks, seized by the power of a god",
	"In a sunlit home domesticated birds sing joyously",
	"An angel carrying a harp",
	"An albatross feeding from the hand of a sailor",
	"A large group of pheasants on a private estate",
	"An illustrated lecture on natural science reveals little-known aspects of life",
	"A fire worshiper meditates on the ultimate realities of existence",
	"An ancient bas-relief carved in granite remains a witness to a long-forgotten culture",
	"In a hospital, the children's ward is filled with toys",
	"School grounds filled with boys and girls in gymnasium suits",
	"A repressed woman finds a psychological release in nudism",
	"The Union Jack flag flies from a British warship",
	"A five-year-old child carrying a bag filled with groceries",
	"A hidden choir is singing during a religious service",
	"A relay race",
	"By accepting defeat gracefully, a general reveals nobility of character",
	"A soldier receiving two awards for bravery in combat",
	"A woman entering a convent",
	"A store filled with precious Oriental rugs",
	"A nature spirit dancing in the iridescent mist of a waterfall",
	"Pilgrims climbing the steep steps leading to a mountain shrine",
	"A large aviary",
	"A woman reading tea leaves",
	"A secret meeting of men responsible for executive decisions in world affairs",
	// ── AQUARIUS (300-329) ──
	"An old adobe mission in California",
	"An unexpected thunderstorm",
	"A deserter from the Navy",
	"A Hindu healer glows with a mystic healing power",
	"A council of ancestors has been called to guide a man",
	"A masked figure performs ritualistic acts in a mystery play",
	"A child is seen being born out of an egg",
	"Beautifully gowned wax figures on display",
	"A flag is seen turning into an eagle",
	"A man who had for a time become the embodiment of a popular ideal is made to realize that as a person he is not this ideal",
	"During a silent hour, a man receives a new inspiration which may change his life",
	"On a vast staircase stand people of different types, graduated upward",
	"A barometer",
	"A train entering a tunnel",
	"Two lovebirds sitting on a fence and singing happily",
	"A big businessman at his desk",
	"A watchdog stands guard, protecting his master and his possessions",
	"A man being unmasked at a masquerade",
	"A forest fire is being subdued by the use of water, chemicals, and sheer muscular energy",
	"A large white dove bearing a message",
	"A woman disappointed and disillusioned, courageously facing a seemingly empty life",
	"A rug is placed on the floor of a nursery to allow children to play in comfort and warmth",
	"A big bear sitting down and waving all its paws",
	"A man turning his back on his passions, teaches from his experience",
	"A butterfly with the right wing more perfectly formed",
	"A hydrometer",
	"An ancient pottery bowl filled with fresh violets",
	"A tree felled and sawed to ensure a supply of wood for the winter",
	"A butterfly emerging from a chrysalis",
	"Deeply rooted in the past of a very ancient culture, a spiritual brotherhood in which many individual minds are merged into the glow of a unanimous participation is revealed to one who has earnestly sought membership",
	// ── PISCES (330-359) ──
	"In a crowded marketplace farmers and middlemen display a great variety of products",
	"A squirrel hiding from hunters",
	"Petrified tree trunks lie broken on desert sand",
	"Heavy car traffic on a narrow isthmus linking two seashore resorts",
	"A church bazaar",
	"A parade of army officers in full dress",
	"Illumined by a shaft of light, a large cross lies on rocks surrounded by sea and mist",
	"A girl blowing a bugle",
	"A jockey spurs his horse, intent on outdistancing his rivals",
	"An aviator pursues his journey, flying through ground-hugging clouds and fog",
	"Men traveling a narrow path, seeking illumination",
	"In the sanctuary of an occult brotherhood, newly initiated members are being examined and their character tested",
	"An ancient sword, used in many battles, is displayed in a museum",
	"A lady wrapped in a large stole of fox fur",
	"An officer instructing his men before a simulated assault under a barrage of live shells",
	"In the quiet of his study a creative individual experiences a flow of inspiration",
	"An Easter promenade",
	"In a huge tent a famous revivalist conducts his meeting with a spectacular performance",
	"A master instructing his disciple",
	"A table set for an evening meal",
	"Under the watchful and kind eye of a Chinese servant, a girl fondles a little white lamb",
	"A prophet carrying tablets of the new law is walking down the slopes of Mount Sinai",
	"A 'materializing' medium giving a séance",
	"On a small island surrounded by the vast expanse of the sea, people are seen living in close interaction",
	"A religious organization succeeds in overcoming the corrupting influence of perverted practices and materialized ideals",
	"Watching the very thin moon crescent appearing at sunset, different people realize that the time has come to go ahead with their different projects",
	"The harvest moon illumines a clear autumnal sky",
	"A fertile garden under the full moon reveals a variety of full-grown vegetables",
	"Light breaking into many colors as it passes through a prism",
	"A majestic rock formation resembling a face is idealized by a boy who takes it as his ideal of greatness, and as he grows up, begins to look like it",
}
