// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (tenant_id, user_id, name, birth_date, birth_time, birth_time_known, city, nation, lat, lon, alt, utc_offset, relationship, notes, kind)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, tenant_id, user_id, name, birth_date, birth_time, birth_time_known, city, nation, lat, lon, alt, utc_offset, relationship, notes, kind, created_at, updated_at
`

type CreateContactParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Name           string      `json:"name"`
	BirthDate      pgtype.Date `json:"birth_date"`
	BirthTime      pgtype.Time `json:"birth_time"`
	BirthTimeKnown bool        `json:"birth_time_known"`
	City           string      `json:"city"`
	Nation         string      `json:"nation"`
	Lat            float64     `json:"lat"`
	Lon            float64     `json:"lon"`
	Alt            float64     `json:"alt"`
	UtcOffset      int32       `json:"utc_offset"`
	Relationship   pgtype.Text `json:"relationship"`
	Notes          pgtype.Text `json:"notes"`
	Kind           string      `json:"kind"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.TenantID,
		arg.UserID,
		arg.Name,
		arg.BirthDate,
		arg.BirthTime,
		arg.BirthTimeKnown,
		arg.City,
		arg.Nation,
		arg.Lat,
		arg.Lon,
		arg.Alt,
		arg.UtcOffset,
		arg.Relationship,
		arg.Notes,
		arg.Kind,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Name,
		&i.BirthDate,
		&i.BirthTime,
		&i.BirthTimeKnown,
		&i.City,
		&i.Nation,
		&i.Lat,
		&i.Lon,
		&i.Alt,
		&i.UtcOffset,
		&i.Relationship,
		&i.Notes,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts WHERE tenant_id = $1 AND id = $2
`

type DeleteContactParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) error {
	_, err := q.db.Exec(ctx, deleteContact, arg.TenantID, arg.ID)
	return err
}

const getContact = `-- name: GetContact :one
SELECT id, tenant_id, user_id, name, birth_date, birth_time, birth_time_known, city, nation, lat, lon, alt, utc_offset, relationship, notes, kind, created_at, updated_at FROM contacts WHERE tenant_id = $1 AND id = $2
`

type GetContactParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, arg.TenantID, arg.ID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Name,
		&i.BirthDate,
		&i.BirthTime,
		&i.BirthTimeKnown,
		&i.City,
		&i.Nation,
		&i.Lat,
		&i.Lon,
		&i.Alt,
		&i.UtcOffset,
		&i.Relationship,
		&i.Notes,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContactByName = `-- name: GetContactByName :one
SELECT id, tenant_id, user_id, name, birth_date, birth_time, birth_time_known, city, nation, lat, lon, alt, utc_offset, relationship, notes, kind, created_at, updated_at FROM contacts WHERE tenant_id = $1 AND lower(name) = lower($2)
`

type GetContactByNameParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Lower    string      `json:"lower"`
}

func (q *Queries) GetContactByName(ctx context.Context, arg GetContactByNameParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByName, arg.TenantID, arg.Lower)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Name,
		&i.BirthDate,
		&i.BirthTime,
		&i.BirthTimeKnown,
		&i.City,
		&i.Nation,
		&i.Lat,
		&i.Lon,
		&i.Alt,
		&i.UtcOffset,
		&i.Relationship,
		&i.Notes,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContacts = `-- name: ListContacts :many
SELECT id, tenant_id, user_id, name, birth_date, birth_time, birth_time_known, city, nation, lat, lon, alt, utc_offset, relationship, notes, kind, created_at, updated_at FROM contacts WHERE tenant_id = $1 AND user_id = $2 ORDER BY name
`

type ListContactsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Name,
			&i.BirthDate,
			&i.BirthTime,
			&i.BirthTimeKnown,
			&i.City,
			&i.Nation,
			&i.Lat,
			&i.Lon,
			&i.Alt,
			&i.UtcOffset,
			&i.Relationship,
			&i.Notes,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchContacts = `-- name: SearchContacts :many
SELECT id, tenant_id, user_id, name, birth_date, birth_time, birth_time_known, city, nation, lat, lon, alt, utc_offset, relationship, notes, kind, created_at, updated_at FROM contacts WHERE tenant_id = $1 AND user_id = $2 AND name ILIKE '%' || $3 || '%' ORDER BY name
`

type SearchContactsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Column3  pgtype.Text `json:"column_3"`
}

func (q *Queries) SearchContacts(ctx context.Context, arg SearchContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, searchContacts, arg.TenantID, arg.UserID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Name,
			&i.BirthDate,
			&i.BirthTime,
			&i.BirthTimeKnown,
			&i.City,
			&i.Nation,
			&i.Lat,
			&i.Lon,
			&i.Alt,
			&i.UtcOffset,
			&i.Relationship,
			&i.Notes,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts SET
    name = $3, birth_date = $4, birth_time = $5, birth_time_known = $6,
    city = $7, nation = $8, lat = $9, lon = $10, alt = $11, utc_offset = $12,
    relationship = $13, notes = $14, kind = $15, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, user_id, name, birth_date, birth_time, birth_time_known, city, nation, lat, lon, alt, utc_offset, relationship, notes, kind, created_at, updated_at
`

type UpdateContactParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	BirthDate      pgtype.Date `json:"birth_date"`
	BirthTime      pgtype.Time `json:"birth_time"`
	BirthTimeKnown bool        `json:"birth_time_known"`
	City           string      `json:"city"`
	Nation         string      `json:"nation"`
	Lat            float64     `json:"lat"`
	Lon            float64     `json:"lon"`
	Alt            float64     `json:"alt"`
	UtcOffset      int32       `json:"utc_offset"`
	Relationship   pgtype.Text `json:"relationship"`
	Notes          pgtype.Text `json:"notes"`
	Kind           string      `json:"kind"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.BirthDate,
		arg.BirthTime,
		arg.BirthTimeKnown,
		arg.City,
		arg.Nation,
		arg.Lat,
		arg.Lon,
		arg.Alt,
		arg.UtcOffset,
		arg.Relationship,
		arg.Notes,
		arg.Kind,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Name,
		&i.BirthDate,
		&i.BirthTime,
		&i.BirthTimeKnown,
		&i.City,
		&i.Nation,
		&i.Lat,
		&i.Lon,
		&i.Alt,
		&i.UtcOffset,
		&i.Relationship,
		&i.Notes,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
