-- 057_e2e_test_user.down.sql
--
-- NO-OP: matches the up-side (see 057_e2e_test_user.up.sql). The seed now
-- lives in `deploy/scripts/seed.sh`; this migration no longer creates or
-- owns any rows to roll back.
