-- 057_e2e_test_user.up.sql
--
-- NO-OP as of 2026-04-18 (ADR 027 F-02, branch 2.0.7).
--
-- The e2e-test user seed previously lived here and unconditionally INSERTed
-- a `role-admin` user with a bcrypt hash of a known plaintext ('testpassword123')
-- committed to git. Under the ADR 022/023 silo model every production silo
-- ran this migration on cold-start, so the public backdoor existed for the
-- entire window between 057 applying and 068 deleting. The seed is now in
-- `deploy/scripts/seed.sh`, invoked by `make seed` in dev/workstation only.
--
-- The filename stays so schema_migrations numbering is preserved and the
-- migration chain remains contiguous for silos that already recorded 057.
-- Migration 068 still runs as defense-in-depth against silos that applied
-- the original 057 before this was neutered.
