-- 058_admin_user.up.sql
--
-- NO-OP as of 2026-04-18 (ADR 027 F-02, branch 2.0.7).
--
-- Originally seeded the canonical admin user (`admin@sda.local` / `admin123`)
-- into every tenant on cold-start. The bcrypt hash was committed to git, so
-- under the ADR 022/023 silo model every production tenant held a publicly-
-- documented admin credential from 058 applying until 068 deleting it. The
-- seed is now in `deploy/scripts/seed.sh`, invoked by `make seed` in
-- dev/workstation only.
--
-- The filename stays so schema_migrations numbering is preserved. Migration
-- 068 still runs as defense-in-depth against silos that applied the original
-- 058 before this was neutered.
