-- 058_admin_user.down.sql
--
-- NO-OP: matches the up-side (see 058_admin_user.up.sql). The seed now
-- lives in `deploy/scripts/seed.sh`; this migration no longer creates or
-- owns any rows to roll back.
