// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingest.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO ingest_jobs (user_id, collection, file_name, file_size, status)
VALUES ($1, $2, $3, $4, 'pending')
RETURNING id, user_id, collection, file_name, file_size, status, error, created_at, updated_at
`

type CreateJobParams struct {
	UserID     string `json:"user_id"`
	Collection string `json:"collection"`
	FileName   string `json:"file_name"`
	FileSize   int64  `json:"file_size"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (IngestJob, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.UserID,
		arg.Collection,
		arg.FileName,
		arg.FileSize,
	)
	var i IngestJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Collection,
		&i.FileName,
		&i.FileSize,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :execrows
DELETE FROM ingest_jobs WHERE id = $1 AND user_id = $2
`

type DeleteJobParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteJob(ctx context.Context, arg DeleteJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteJob, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteJobByID = `-- name: DeleteJobByID :exec
DELETE FROM ingest_jobs WHERE id = $1
`

func (q *Queries) DeleteJobByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteJobByID, id)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, user_id, collection, file_name, file_size, status, error, created_at, updated_at
FROM ingest_jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id string) (IngestJob, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i IngestJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Collection,
		&i.FileName,
		&i.FileSize,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobsByUser = `-- name: ListJobsByUser :many
SELECT id, user_id, collection, file_name, file_size, status, error, created_at, updated_at
FROM ingest_jobs WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListJobsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListJobsByUser(ctx context.Context, arg ListJobsByUserParams) ([]IngestJob, error) {
	rows, err := q.db.Query(ctx, listJobsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestJob{}
	for rows.Next() {
		var i IngestJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Collection,
			&i.FileName,
			&i.FileSize,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE ingest_jobs SET status = $1, updated_at = now() WHERE id = $2
`

type UpdateJobStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStatus, arg.Status, arg.ID)
	return err
}

const updateJobStatusWithError = `-- name: UpdateJobStatusWithError :exec
UPDATE ingest_jobs SET status = $1, error = $2, updated_at = now() WHERE id = $3
`

type UpdateJobStatusWithErrorParams struct {
	Status string      `json:"status"`
	Error  pgtype.Text `json:"error"`
	ID     string      `json:"id"`
}

func (q *Queries) UpdateJobStatusWithError(ctx context.Context, arg UpdateJobStatusWithErrorParams) error {
	_, err := q.db.Exec(ctx, updateJobStatusWithError, arg.Status, arg.Error, arg.ID)
	return err
}
