// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Connector struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Config    []byte             `json:"config"`
	Enabled   bool               `json:"enabled"`
	CreatedBy pgtype.Text        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type IngestJob struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	Collection string             `json:"collection"`
	FileName   string             `json:"file_name"`
	FileSize   int64              `json:"file_size"`
	Status     string             `json:"status"`
	Error      pgtype.Text        `json:"error"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID string `json:"id"`
}
