// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Collection struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CollectionDocument struct {
	CollectionID string `json:"collection_id"`
	DocumentID   string `json:"document_id"`
}

type Connector struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Config    []byte             `json:"config"`
	Enabled   bool               `json:"enabled"`
	CreatedBy pgtype.Text        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Document struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	StorageKey string             `json:"storage_key"`
	FileType   string             `json:"file_type"`
	FileHash   string             `json:"file_hash"`
	SizeBytes  int64              `json:"size_bytes"`
	TotalPages pgtype.Int4        `json:"total_pages"`
	Status     string             `json:"status"`
	Metadata   []byte             `json:"metadata"`
	UploadedBy string             `json:"uploaded_by"`
	Error      pgtype.Text        `json:"error"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type DocumentPage struct {
	ID         string             `json:"id"`
	DocumentID string             `json:"document_id"`
	PageNumber int32              `json:"page_number"`
	Text       string             `json:"text"`
	Tables     []byte             `json:"tables"`
	Images     []byte             `json:"images"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type DocumentTree struct {
	ID             string             `json:"id"`
	DocumentID     string             `json:"document_id"`
	Tree           []byte             `json:"tree"`
	DocDescription pgtype.Text        `json:"doc_description"`
	TreeVersion    int32              `json:"tree_version"`
	ModelUsed      string             `json:"model_used"`
	NodeCount      int32              `json:"node_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type IngestJob struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	Collection string             `json:"collection"`
	FileName   string             `json:"file_name"`
	FileSize   int64              `json:"file_size"`
	Status     string             `json:"status"`
	Error      pgtype.Text        `json:"error"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ToolCall struct {
	ID         string             `json:"id"`
	TraceID    string             `json:"trace_id"`
	SessionID  string             `json:"session_id"`
	UserID     string             `json:"user_id"`
	ToolName   string             `json:"tool_name"`
	Input      []byte             `json:"input"`
	Output     []byte             `json:"output"`
	Status     string             `json:"status"`
	DurationMs pgtype.Int4        `json:"duration_ms"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID string `json:"id"`
}
