// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feedback.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateByModuleCategory = `-- name: AggregateByModuleCategory :many
SELECT module, category,
    COUNT(*)::int AS total,
    COUNT(*) FILTER (WHERE thumbs = 'up')::int AS positive,
    COUNT(*) FILTER (WHERE thumbs = 'down')::int AS negative,
    AVG(score)::float8 AS avg_score,
    COUNT(*) FILTER (WHERE category = 'error_report')::int AS error_count
FROM feedback_events
WHERE created_at > $1 AND created_at <= $2
GROUP BY module, category
`

type AggregateByModuleCategoryParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type AggregateByModuleCategoryRow struct {
	Module     string  `json:"module"`
	Category   string  `json:"category"`
	Total      int32   `json:"total"`
	Positive   int32   `json:"positive"`
	Negative   int32   `json:"negative"`
	AvgScore   float64 `json:"avg_score"`
	ErrorCount int32   `json:"error_count"`
}

func (q *Queries) AggregateByModuleCategory(ctx context.Context, arg AggregateByModuleCategoryParams) ([]AggregateByModuleCategoryRow, error) {
	rows, err := q.db.Query(ctx, aggregateByModuleCategory, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateByModuleCategoryRow{}
	for rows.Next() {
		var i AggregateByModuleCategoryRow
		if err := rows.Scan(
			&i.Module,
			&i.Category,
			&i.Total,
			&i.Positive,
			&i.Negative,
			&i.AvgScore,
			&i.ErrorCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const avgHourlyUsage = `-- name: AvgHourlyUsage :one
SELECT COALESCE(COUNT(*)::float8 / GREATEST(EXTRACT(EPOCH FROM (now() - MIN(created_at))) / 3600, 1), 0)::float8 AS avg_hourly
FROM feedback_events
WHERE category = 'usage'
  AND created_at > now() - interval '7 days'
`

func (q *Queries) AvgHourlyUsage(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, avgHourlyUsage)
	var avg_hourly float64
	err := row.Scan(&avg_hourly)
	return avg_hourly, err
}

const countByCategory = `-- name: CountByCategory :many
SELECT category, COUNT(*)::int AS count
FROM feedback_events
WHERE created_at > now() - make_interval(hours => $1)
GROUP BY category
`

type CountByCategoryRow struct {
	Category string `json:"category"`
	Count    int32  `json:"count"`
}

func (q *Queries) CountByCategory(ctx context.Context, hours int32) ([]CountByCategoryRow, error) {
	rows, err := q.db.Query(ctx, countByCategory, hours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountByCategoryRow{}
	for rows.Next() {
		var i CountByCategoryRow
		if err := rows.Scan(&i.Category, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCriticalSecurityEvents = `-- name: CountCriticalSecurityEvents :one
SELECT COUNT(*)::int AS count
FROM feedback_events
WHERE category = 'security' AND severity = 'critical'
  AND created_at > now() - interval '1 hour'
`

func (q *Queries) CountCriticalSecurityEvents(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countCriticalSecurityEvents)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countHistoricalUsage = `-- name: CountHistoricalUsage :one
SELECT COUNT(*)::int AS count
FROM feedback_events
WHERE category = 'usage' AND created_at > $1
`

func (q *Queries) CountHistoricalUsage(ctx context.Context, createdAt pgtype.Timestamptz) (int32, error) {
	row := q.db.QueryRow(ctx, countHistoricalUsage, createdAt)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const errorCounts = `-- name: ErrorCounts :one
SELECT
    COUNT(*)::int AS total,
    COUNT(*) FILTER (WHERE severity = 'critical')::int AS critical,
    COUNT(*) FILTER (WHERE status = 'open')::int AS open
FROM feedback_events
WHERE category = 'error_report'
  AND created_at > now() - make_interval(hours => $1)
`

type ErrorCountsRow struct {
	Total    int32 `json:"total"`
	Critical int32 `json:"critical"`
	Open     int32 `json:"open"`
}

func (q *Queries) ErrorCounts(ctx context.Context, hours int32) (ErrorCountsRow, error) {
	row := q.db.QueryRow(ctx, errorCounts, hours)
	var i ErrorCountsRow
	err := row.Scan(&i.Total, &i.Critical, &i.Open)
	return i, err
}

const getSummaryAIQuality = `-- name: GetSummaryAIQuality :one
SELECT COUNT(*)::int AS total_feedback,
    COALESCE(AVG(score), 0)::float8 AS avg_score,
    CASE WHEN COUNT(*) > 0 THEN COUNT(*) FILTER (WHERE thumbs = 'up')::float8 / NULLIF(COUNT(*), 0)
    ELSE 0 END::float8 AS positive_rate
FROM feedback_events
WHERE category IN ('response_quality','agent_quality','extraction','detection')
  AND created_at > now() - make_interval(hours => $1)
`

type GetSummaryAIQualityRow struct {
	TotalFeedback int32   `json:"total_feedback"`
	AvgScore      float64 `json:"avg_score"`
	PositiveRate  float64 `json:"positive_rate"`
}

func (q *Queries) GetSummaryAIQuality(ctx context.Context, hours int32) (GetSummaryAIQualityRow, error) {
	row := q.db.QueryRow(ctx, getSummaryAIQuality, hours)
	var i GetSummaryAIQualityRow
	err := row.Scan(&i.TotalFeedback, &i.AvgScore, &i.PositiveRate)
	return i, err
}

const getSummaryErrors = `-- name: GetSummaryErrors :one
SELECT COUNT(*)::int AS total,
    COUNT(*) FILTER (WHERE status = 'open')::int AS open,
    COUNT(*) FILTER (WHERE severity = 'critical')::int AS critical
FROM feedback_events
WHERE category = 'error_report'
  AND created_at > now() - make_interval(hours => $1)
`

type GetSummaryErrorsRow struct {
	Total    int32 `json:"total"`
	Open     int32 `json:"open"`
	Critical int32 `json:"critical"`
}

func (q *Queries) GetSummaryErrors(ctx context.Context, hours int32) (GetSummaryErrorsRow, error) {
	row := q.db.QueryRow(ctx, getSummaryErrors, hours)
	var i GetSummaryErrorsRow
	err := row.Scan(&i.Total, &i.Open, &i.Critical)
	return i, err
}

const getSummaryFeatures = `-- name: GetSummaryFeatures :one
SELECT COUNT(*)::int AS total,
    COUNT(*) FILTER (WHERE status = 'open')::int AS open
FROM feedback_events
WHERE category = 'feature_request'
  AND created_at > now() - make_interval(hours => $1)
`

type GetSummaryFeaturesRow struct {
	Total int32 `json:"total"`
	Open  int32 `json:"open"`
}

func (q *Queries) GetSummaryFeatures(ctx context.Context, hours int32) (GetSummaryFeaturesRow, error) {
	row := q.db.QueryRow(ctx, getSummaryFeatures, hours)
	var i GetSummaryFeaturesRow
	err := row.Scan(&i.Total, &i.Open)
	return i, err
}

const getSummaryNPS = `-- name: GetSummaryNPS :one
SELECT COUNT(*)::int AS responses,
    COALESCE(
        (COUNT(*) FILTER (WHERE score >= 9)::float8 - COUNT(*) FILTER (WHERE score < 7)::float8)
        / NULLIF(COUNT(*), 0) * 100, 0)::float8 AS score
FROM feedback_events
WHERE category = 'nps'
  AND created_at > now() - interval '30 days'
`

type GetSummaryNPSRow struct {
	Responses int32   `json:"responses"`
	Score     float64 `json:"score"`
}

func (q *Queries) GetSummaryNPS(ctx context.Context) (GetSummaryNPSRow, error) {
	row := q.db.QueryRow(ctx, getSummaryNPS)
	var i GetSummaryNPSRow
	err := row.Scan(&i.Responses, &i.Score)
	return i, err
}

const getUsageByModule = `-- name: GetUsageByModule :many
SELECT module, COUNT(*)::int AS actions, COUNT(DISTINCT user_id)::int AS unique_users
FROM feedback_events
WHERE category = 'usage'
  AND created_at > now() - make_interval(hours => $1)
GROUP BY module
ORDER BY COUNT(*) DESC
`

type GetUsageByModuleRow struct {
	Module      string `json:"module"`
	Actions     int32  `json:"actions"`
	UniqueUsers int32  `json:"unique_users"`
}

func (q *Queries) GetUsageByModule(ctx context.Context, hours int32) ([]GetUsageByModuleRow, error) {
	rows, err := q.db.Query(ctx, getUsageByModule, hours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsageByModuleRow{}
	for rows.Next() {
		var i GetUsageByModuleRow
		if err := rows.Scan(&i.Module, &i.Actions, &i.UniqueUsers); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFeedbackEvent = `-- name: InsertFeedbackEvent :exec
INSERT INTO feedback_events (category, module, user_id, score, thumbs, severity, context, comment)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertFeedbackEventParams struct {
	Category string      `json:"category"`
	Module   string      `json:"module"`
	UserID   pgtype.Text `json:"user_id"`
	Score    pgtype.Int4 `json:"score"`
	Thumbs   pgtype.Text `json:"thumbs"`
	Severity pgtype.Text `json:"severity"`
	Context  []byte      `json:"context"`
	Comment  pgtype.Text `json:"comment"`
}

func (q *Queries) InsertFeedbackEvent(ctx context.Context, arg InsertFeedbackEventParams) error {
	_, err := q.db.Exec(ctx, insertFeedbackEvent,
		arg.Category,
		arg.Module,
		arg.UserID,
		arg.Score,
		arg.Thumbs,
		arg.Severity,
		arg.Context,
		arg.Comment,
	)
	return err
}

const listErrorEvents = `-- name: ListErrorEvents :many
SELECT id, module, severity, status, context, comment, created_at
FROM feedback_events
WHERE category = 'error_report' AND status = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListErrorEventsParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
}

type ListErrorEventsRow struct {
	ID        string             `json:"id"`
	Module    string             `json:"module"`
	Severity  pgtype.Text        `json:"severity"`
	Status    string             `json:"status"`
	Context   []byte             `json:"context"`
	Comment   pgtype.Text        `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListErrorEvents(ctx context.Context, arg ListErrorEventsParams) ([]ListErrorEventsRow, error) {
	rows, err := q.db.Query(ctx, listErrorEvents, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListErrorEventsRow{}
	for rows.Next() {
		var i ListErrorEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Severity,
			&i.Status,
			&i.Context,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQualityEvents = `-- name: ListQualityEvents :many
SELECT id, category, module, score, thumbs, comment, created_at
FROM feedback_events
WHERE category IN ('response_quality','agent_quality','extraction','detection')
  AND created_at > now() - make_interval(hours => $1)
ORDER BY created_at DESC
LIMIT $2
`

type ListQualityEventsParams struct {
	Hours int32 `json:"hours"`
	Limit int32 `json:"limit"`
}

type ListQualityEventsRow struct {
	ID        string             `json:"id"`
	Category  string             `json:"category"`
	Module    string             `json:"module"`
	Score     pgtype.Int4        `json:"score"`
	Thumbs    pgtype.Text        `json:"thumbs"`
	Comment   pgtype.Text        `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListQualityEvents(ctx context.Context, arg ListQualityEventsParams) ([]ListQualityEventsRow, error) {
	rows, err := q.db.Query(ctx, listQualityEvents, arg.Hours, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQualityEventsRow{}
	for rows.Next() {
		var i ListQualityEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Module,
			&i.Score,
			&i.Thumbs,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQualityEventsByModule = `-- name: ListQualityEventsByModule :many
SELECT id, category, module, score, thumbs, comment, created_at
FROM feedback_events
WHERE category IN ('response_quality','agent_quality','extraction','detection')
  AND created_at > now() - make_interval(hours => $1)
  AND module = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListQualityEventsByModuleParams struct {
	Hours  int32  `json:"hours"`
	Module string `json:"module"`
	Limit  int32  `json:"limit"`
}

type ListQualityEventsByModuleRow struct {
	ID        string             `json:"id"`
	Category  string             `json:"category"`
	Module    string             `json:"module"`
	Score     pgtype.Int4        `json:"score"`
	Thumbs    pgtype.Text        `json:"thumbs"`
	Comment   pgtype.Text        `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListQualityEventsByModule(ctx context.Context, arg ListQualityEventsByModuleParams) ([]ListQualityEventsByModuleRow, error) {
	rows, err := q.db.Query(ctx, listQualityEventsByModule, arg.Hours, arg.Module, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQualityEventsByModuleRow{}
	for rows.Next() {
		var i ListQualityEventsByModuleRow
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Module,
			&i.Score,
			&i.Thumbs,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const performancePercentiles = `-- name: PerformancePercentiles :one
SELECT
    COALESCE(percentile_cont(0.50) WITHIN GROUP (ORDER BY latency_ms), 0)::float8 AS p50,
    COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY latency_ms), 0)::float8 AS p95,
    COALESCE(percentile_cont(0.99) WITHIN GROUP (ORDER BY latency_ms), 0)::float8 AS p99
FROM feedback_events
WHERE category = 'performance'
  AND created_at > now() - make_interval(hours => $1)
`

type PerformancePercentilesRow struct {
	P50 float64 `json:"p50"`
	P95 float64 `json:"p95"`
	P99 float64 `json:"p99"`
}

func (q *Queries) PerformancePercentiles(ctx context.Context, hours int32) (PerformancePercentilesRow, error) {
	row := q.db.QueryRow(ctx, performancePercentiles, hours)
	var i PerformancePercentilesRow
	err := row.Scan(&i.P50, &i.P95, &i.P99)
	return i, err
}

const purgeOldEvents = `-- name: PurgeOldEvents :execrows
DELETE FROM feedback_events WHERE created_at < now() - interval '90 days'
`

func (q *Queries) PurgeOldEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOldEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const qualityMetrics = `-- name: QualityMetrics :one
SELECT
    COUNT(*) FILTER (WHERE thumbs = 'up')::int AS positive,
    COUNT(*) FILTER (WHERE thumbs = 'down')::int AS negative,
    COUNT(*)::int AS total,
    COALESCE(AVG(score), 0)::float8 AS avg_score
FROM feedback_events
WHERE category IN ('response_quality', 'agent_quality', 'extraction', 'detection')
  AND created_at > now() - make_interval(hours => $1)
`

type QualityMetricsRow struct {
	Positive int32   `json:"positive"`
	Negative int32   `json:"negative"`
	Total    int32   `json:"total"`
	AvgScore float64 `json:"avg_score"`
}

func (q *Queries) QualityMetrics(ctx context.Context, hours int32) (QualityMetricsRow, error) {
	row := q.db.QueryRow(ctx, qualityMetrics, hours)
	var i QualityMetricsRow
	err := row.Scan(
		&i.Positive,
		&i.Negative,
		&i.Total,
		&i.AvgScore,
	)
	return i, err
}
