// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FeedbackEvent struct {
	ID        string             `json:"id"`
	Category  string             `json:"category"`
	Module    string             `json:"module"`
	UserID    pgtype.Text        `json:"user_id"`
	Score     pgtype.Int4        `json:"score"`
	Thumbs    pgtype.Text        `json:"thumbs"`
	Severity  pgtype.Text        `json:"severity"`
	Status    string             `json:"status"`
	Context   []byte             `json:"context"`
	Comment   pgtype.Text        `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
