#!/bin/bash
# deploy.sh — Deterministic deploy for SDA Framework
#
# Usage:
#   deploy/scripts/deploy.sh              # deploy all Go services
#   deploy/scripts/deploy.sh auth chat    # deploy specific services
#   deploy/scripts/deploy.sh --cache auth # fast rebuild (use Docker layer cache)
#
# What it does:
#   1. Reads VERSION files + git SHA
#   2. Generates .env.deploy with all version vars
#   3. Builds images (--no-cache by default)
#   4. docker compose up -d
#   5. Waits for health checks
#   6. Verifies /v1/info matches expected SHA
#   7. Reports mismatch as error (exit 1)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
DEPLOY_DIR="$ROOT_DIR/deploy"
COMPOSE_FILE="$DEPLOY_DIR/docker-compose.prod.yml"

GIT_SHA=$(cd "$ROOT_DIR" && git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILD_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)

declare -A SERVICE_PORTS=(
    [auth]=8001 [ws]=8002 [chat]=8003 [agent]=8004
    [notification]=8005 [platform]=8006 [ingest]=8007
    [feedback]=8008 [search]=8010
    [erp]=8013 [app]=8020
)

ALL_GO_SERVICES=(auth ws chat agent search notification platform ingest feedback erp app)
ALL_FRONTEND_SERVICES=(web)
ALL_SERVICES=("${ALL_GO_SERVICES[@]}" "${ALL_FRONTEND_SERVICES[@]}")

# is_frontend <name> → 0 if name is in ALL_FRONTEND_SERVICES, 1 otherwise
is_frontend() {
    local name="$1"
    for fe in "${ALL_FRONTEND_SERVICES[@]}"; do
        [ "$name" = "$fe" ] && return 0
    done
    return 1
}

NO_CACHE="--no-cache"
SERVICES=()
for arg in "$@"; do
    if [ "$arg" = "--cache" ]; then
        NO_CACHE=""
    else
        SERVICES+=("$arg")
    fi
done

if [ ${#SERVICES[@]} -eq 0 ]; then
    SERVICES=("${ALL_SERVICES[@]}")
fi

echo "═══ SDA Deploy ═══"
echo "  Git SHA:    $GIT_SHA"
echo "  Build time: $BUILD_TIME"
echo "  Services:   ${SERVICES[*]}"
echo "  Cache:      ${NO_CACHE:-enabled}"
echo ""

# Generate .env.deploy
ENV_DEPLOY="$DEPLOY_DIR/.env.deploy"
{
    echo "# Auto-generated by deploy.sh — $(date -u)"
    echo "GIT_SHA=$GIT_SHA"
    echo "BUILD_TIME=$BUILD_TIME"
    for svc in "${SERVICES[@]}"; do
        upper=$(echo "$svc" | tr '[:lower:]' '[:upper:]')
        # Frontend services live under apps/<svc>/, Go services under services/<svc>/.
        if is_frontend "$svc"; then
            version_file="$ROOT_DIR/apps/$svc/VERSION"
        else
            version_file="$ROOT_DIR/services/$svc/VERSION"
        fi
        if [ -f "$version_file" ]; then
            version=$(tr -d '[:space:]' < "$version_file")
        else
            version="dev"
        fi
        echo "${upper}_VERSION=${version}"
    done
} > "$ENV_DEPLOY"

echo "  Generated $ENV_DEPLOY"

set -a
source "$ENV_DEPLOY"
[ -f "$DEPLOY_DIR/.env" ] && source "$DEPLOY_DIR/.env"
set +a

# Build
echo ""
echo "── Building ──"
docker compose -f "$COMPOSE_FILE" build $NO_CACHE "${SERVICES[@]}"

# Start
echo ""
echo "── Starting ──"
docker compose -f "$COMPOSE_FILE" up -d "${SERVICES[@]}"

# Wait for health
echo ""
echo "── Waiting for health checks (max 60s) ──"
TIMEOUT=60
for svc in "${SERVICES[@]}"; do
    port=${SERVICE_PORTS[$svc]:-0}
    if [ "$port" -eq 0 ]; then
        echo "  $svc: no port mapping, skipping"
        continue
    fi

    elapsed=0
    code="000"
    while [ $elapsed -lt $TIMEOUT ]; do
        code=$(curl -sf --max-time 2 -o /dev/null -w "%{http_code}" "http://localhost:$port/health" 2>/dev/null || echo "000")
        if [ "$code" = "200" ]; then
            break
        fi
        sleep 2
        elapsed=$((elapsed + 2))
    done

    if [ "$code" = "200" ]; then
        printf "  %-20s :%-5s \033[32mHEALTHY\033[0m\n" "$svc" "$port"
    else
        printf "  %-20s :%-5s \033[31mUNHEALTHY (code: %s)\033[0m\n" "$svc" "$port" "$code"
    fi
done

# Verify /v1/info matches expected SHA (Go services only — frontend has no /v1/info)
echo ""
echo "── Verifying build info ──"
MISMATCHES=0
for svc in "${SERVICES[@]}"; do
    if is_frontend "$svc"; then continue; fi
    port=${SERVICE_PORTS[$svc]:-0}
    if [ "$port" -eq 0 ]; then continue; fi

    info=$(curl -sf --max-time 2 "http://localhost:$port/v1/info" 2>/dev/null || echo "{}")
    running_sha=$(echo "$info" | grep -o '"git_sha":"[^"]*"' | cut -d'"' -f4)

    if [ "$running_sha" = "$GIT_SHA" ]; then
        printf "  %-20s \033[32mOK\033[0m (sha: %s)\n" "$svc" "$running_sha"
    elif [ -z "$running_sha" ] || [ "$running_sha" = "unknown" ]; then
        printf "  %-20s \033[33mNO INFO\033[0m (endpoint returned: %s)\n" "$svc" "${running_sha:-empty}"
        MISMATCHES=$((MISMATCHES + 1))
    else
        printf "  %-20s \033[31mMISMATCH\033[0m (expected: %s, got: %s)\n" "$svc" "$GIT_SHA" "$running_sha"
        MISMATCHES=$((MISMATCHES + 1))
    fi
done

echo ""
if [ $MISMATCHES -gt 0 ]; then
    echo "═══ DEPLOY COMPLETE WITH $MISMATCHES WARNING(S) ═══"
    echo "  Some services may be running stale code."
    echo "  Try: bash deploy/scripts/deploy.sh ${SERVICES[*]}"
    exit 1
else
    echo "═══ DEPLOY COMPLETE — ALL VERIFIED ═══"
fi
