// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkMFAEnabled = `-- name: CheckMFAEnabled :one
SELECT COALESCE(mfa_enabled, false)::bool AS enabled FROM users WHERE id = $1
`

func (q *Queries) CheckMFAEnabled(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, checkMFAEnabled, id)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const disableMFA = `-- name: DisableMFA :exec
UPDATE users SET mfa_enabled = false, mfa_secret = NULL WHERE id = $1
`

func (q *Queries) DisableMFA(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, disableMFA, id)
	return err
}

const enableMFA = `-- name: EnableMFA :exec
UPDATE users SET mfa_enabled = true WHERE id = $1
`

func (q *Queries) EnableMFA(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, enableMFA, id)
	return err
}

const getActiveUserById = `-- name: GetActiveUserById :one
SELECT email, name
FROM users WHERE id = $1 AND is_active = true
`

type GetActiveUserByIdRow struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

func (q *Queries) GetActiveUserById(ctx context.Context, id string) (GetActiveUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getActiveUserById, id)
	var i GetActiveUserByIdRow
	err := row.Scan(&i.Email, &i.Name)
	return i, err
}

const getMFASecret = `-- name: GetMFASecret :one
SELECT mfa_secret FROM users WHERE id = $1
`

func (q *Queries) GetMFASecret(ctx context.Context, id string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getMFASecret, id)
	var mfa_secret pgtype.Text
	err := row.Scan(&mfa_secret)
	return mfa_secret, err
}

const getPermissions = `-- name: GetPermissions :many
SELECT DISTINCT p.id FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
JOIN user_roles ur ON ur.role_id = rp.role_id
WHERE ur.user_id = $1
ORDER BY p.id
`

func (q *Queries) GetPermissions(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrimaryRole = `-- name: GetPrimaryRole :one
SELECT r.name FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
ORDER BY CASE r.name
    WHEN 'admin' THEN 1
    WHEN 'manager' THEN 2
    WHEN 'user' THEN 3
    ELSE 4
END
LIMIT 1
`

func (q *Queries) GetPrimaryRole(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, getPrimaryRole, userID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getRefreshTokenOwner = `-- name: GetRefreshTokenOwner :one
SELECT user_id FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenOwner(ctx context.Context, tokenHash string) (string, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenOwner, tokenHash)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, name, password_hash, is_active, failed_logins, locked_until
FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	PasswordHash string             `json:"password_hash"`
	IsActive     bool               `json:"is_active"`
	FailedLogins int32              `json:"failed_logins"`
	LockedUntil  pgtype.Timestamptz `json:"locked_until"`
}

// Auth service queries — generated code lives in internal/repository/
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.IsActive,
		&i.FailedLogins,
		&i.LockedUntil,
	)
	return i, err
}

const getUserEmail = `-- name: GetUserEmail :one
SELECT email FROM users WHERE id = $1
`

func (q *Queries) GetUserEmail(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getUserEmail, id)
	var email string
	err := row.Scan(&email)
	return email, err
}

const getUserForRefresh = `-- name: GetUserForRefresh :one
SELECT name, email, is_active
FROM users WHERE id = $1
`

type GetUserForRefreshRow struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) GetUserForRefresh(ctx context.Context, id string) (GetUserForRefreshRow, error) {
	row := q.db.QueryRow(ctx, getUserForRefresh, id)
	var i GetUserForRefreshRow
	err := row.Scan(&i.Name, &i.Email, &i.IsActive)
	return i, err
}

const recordFailedLogin = `-- name: RecordFailedLogin :exec
UPDATE users SET
    failed_logins = failed_logins + 1,
    locked_until = CASE
        WHEN failed_logins + 1 >= $2::int THEN now() + interval '15 minutes'
        ELSE locked_until
    END,
    is_active = CASE
        WHEN failed_logins + 1 >= $3::int THEN false
        ELSE is_active
    END
WHERE id = $1
`

type RecordFailedLoginParams struct {
	ID               string `json:"id"`
	MaxFailed        int32  `json:"max_failed"`
	PermanentLockout int32  `json:"permanent_lockout"`
}

func (q *Queries) RecordFailedLogin(ctx context.Context, arg RecordFailedLoginParams) error {
	_, err := q.db.Exec(ctx, recordFailedLogin, arg.ID, arg.MaxFailed, arg.PermanentLockout)
	return err
}

const recordSuccessfulLogin = `-- name: RecordSuccessfulLogin :exec
UPDATE users SET
    failed_logins = 0,
    locked_until = NULL,
    last_login_at = now(),
    last_login_ip = $2
WHERE id = $1
`

type RecordSuccessfulLoginParams struct {
	ID          string      `json:"id"`
	LastLoginIp pgtype.Text `json:"last_login_ip"`
}

func (q *Queries) RecordSuccessfulLogin(ctx context.Context, arg RecordSuccessfulLoginParams) error {
	_, err := q.db.Exec(ctx, recordSuccessfulLogin, arg.ID, arg.LastLoginIp)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByHash, tokenHash)
	return err
}

const revokeUserRefreshTokens = `-- name: RevokeUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserRefreshTokens(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeUserRefreshTokens, userID)
	return err
}

const setMFASecret = `-- name: SetMFASecret :exec
UPDATE users SET mfa_secret = $2 WHERE id = $1
`

type SetMFASecretParams struct {
	ID        string      `json:"id"`
	MfaSecret pgtype.Text `json:"mfa_secret"`
}

func (q *Queries) SetMFASecret(ctx context.Context, arg SetMFASecretParams) error {
	_, err := q.db.Exec(ctx, setMFASecret, arg.ID, arg.MfaSecret)
	return err
}

const storeRefreshToken = `-- name: StoreRefreshToken :exec
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type StoreRefreshTokenParams struct {
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) StoreRefreshToken(ctx context.Context, arg StoreRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, storeRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const validateRefreshToken = `-- name: ValidateRefreshToken :one
SELECT EXISTS(
    SELECT 1 FROM refresh_tokens
    WHERE token_hash = $1 AND user_id = $2
      AND revoked_at IS NULL AND expires_at > now()
)
`

type ValidateRefreshTokenParams struct {
	TokenHash string `json:"token_hash"`
	UserID    string `json:"user_id"`
}

func (q *Queries) ValidateRefreshToken(ctx context.Context, arg ValidateRefreshTokenParams) (bool, error) {
	row := q.db.QueryRow(ctx, validateRefreshToken, arg.TokenHash, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
