package service

import (
	"context"
	"fmt"
	"log/slog"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/redis/go-redis/v9"

	"github.com/Camionerou/rag-saldivia/pkg/audit"
	"github.com/Camionerou/rag-saldivia/pkg/crypto"
)

// CredentialService manages encrypted credentials for devices.
// Uses pkg/crypto/envelope for KEK/DEK encryption with AAD.
type CredentialService struct {
	db         *pgxpool.Pool
	enc        *crypto.Encryptor
	audit      *audit.Writer
	rdb        *redis.Client
	tenantSlug string
}

// NewCredentialService creates a credential service.
func NewCredentialService(db *pgxpool.Pool, enc *crypto.Encryptor, auditWriter *audit.Writer, rdb *redis.Client, tenantSlug string) *CredentialService {
	return &CredentialService{db: db, enc: enc, audit: auditWriter, rdb: rdb, tenantSlug: tenantSlug}
}

// CredentialMeta is the metadata returned by list (never plaintext).
type CredentialMeta struct {
	ID             string  `json:"id"`
	DeviceID       string  `json:"device_id"`
	CredType       string  `json:"cred_type"`
	KeyVersion     int     `json:"key_version"`
	KeyFingerprint *string `json:"key_fingerprint,omitempty"`
	CreatedAt      string  `json:"created_at"`
	RotatedAt      *string `json:"rotated_at,omitempty"`
}

// StoreRequest holds the data to create a new credential.
type StoreRequest struct {
	DeviceID       string
	CredType       string // ssh_key, ssh_password, winrm, snmp_community
	Plaintext      []byte
	KeyFingerprint string // SSH key fingerprint (optional)
	UserID         string
	IP             string
}

// Store encrypts and stores a credential for a device.
func (s *CredentialService) Store(ctx context.Context, req StoreRequest) (*CredentialMeta, error) {
	// Build AAD: ties ciphertext to this specific credential context
	// We don't have the credential_id yet (generated by DB), so use device_id + tenant_slug + cred_type
	aad := []byte(fmt.Sprintf("%s||%s||%s", req.DeviceID, s.tenantSlug, req.CredType))

	encDEK, encData, err := s.enc.Encrypt(req.Plaintext, aad)
	if err != nil {
		return nil, fmt.Errorf("encrypt credential: %w", err)
	}
	// Zero plaintext after encryption
	clear(req.Plaintext)

	var meta CredentialMeta
	err = s.db.QueryRow(ctx,
		`INSERT INTO bb_credentials (tenant_id, device_id, cred_type, encrypted_dek, encrypted_data, key_fingerprint)
		 VALUES (
			(SELECT id FROM tenants WHERE slug = $1 LIMIT 1),
			$2, $3, $4, $5, $6
		 )
		 ON CONFLICT (tenant_id, device_id, cred_type) DO UPDATE SET
			encrypted_dek = EXCLUDED.encrypted_dek,
			encrypted_data = EXCLUDED.encrypted_data,
			key_fingerprint = EXCLUDED.key_fingerprint,
			rotated_at = now()
		 RETURNING id, device_id, cred_type, key_version, key_fingerprint, created_at`,
		s.tenantSlug, req.DeviceID, req.CredType, encDEK, encData, nilIfEmpty(req.KeyFingerprint),
	).Scan(&meta.ID, &meta.DeviceID, &meta.CredType, &meta.KeyVersion, &meta.KeyFingerprint, &meta.CreatedAt)
	if err != nil {
		return nil, fmt.Errorf("store credential: %w", err)
	}

	s.audit.Write(ctx, audit.Entry{
		TenantID: s.tenantSlug,
		UserID:   req.UserID,
		Action:   "bigbrother.credential.stored",
		Resource: fmt.Sprintf("device:%s/cred:%s", req.DeviceID, meta.ID),
		IP:       req.IP,
	})

	return &meta, nil
}

// List returns credential metadata (never plaintext) for a tenant.
func (s *CredentialService) List(ctx context.Context) ([]CredentialMeta, error) {
	rows, err := s.db.Query(ctx,
		`SELECT id, device_id, cred_type, key_version, key_fingerprint, created_at, rotated_at
		 FROM bb_credentials
		 WHERE tenant_id = (SELECT id FROM tenants WHERE slug = $1 LIMIT 1)
		 ORDER BY created_at DESC`, s.tenantSlug)
	if err != nil {
		return nil, fmt.Errorf("list credentials: %w", err)
	}
	defer rows.Close()

	var creds []CredentialMeta
	for rows.Next() {
		var c CredentialMeta
		if err := rows.Scan(&c.ID, &c.DeviceID, &c.CredType, &c.KeyVersion,
			&c.KeyFingerprint, &c.CreatedAt, &c.RotatedAt); err != nil {
			return nil, fmt.Errorf("scan credential: %w", err)
		}
		creds = append(creds, c)
	}
	if creds == nil {
		creds = []CredentialMeta{}
	}
	return creds, nil
}

// Decrypt retrieves and decrypts a credential. Rate-limited via Redis.
// Caller is responsible for zeroing the returned plaintext after use.
func (s *CredentialService) Decrypt(ctx context.Context, credID, userID string) ([]byte, error) {
	// Rate limit: max 10 decrypts per minute per user (Redis-backed)
	if s.rdb != nil {
		key := fmt.Sprintf("sda:bb:decrypt_rate:%s", userID)
		count, err := s.rdb.Incr(ctx, key).Result()
		if err != nil {
			slog.Warn("redis rate limit check failed", "error", err)
		} else {
			if count == 1 {
				s.rdb.Expire(ctx, key, time.Minute)
			}
			if count > 10 {
				return nil, fmt.Errorf("decrypt rate limit exceeded: max 10 per minute")
			}
		}
	}

	var deviceID, credType string
	var encDEK, encData []byte
	err := s.db.QueryRow(ctx,
		`SELECT device_id, cred_type, encrypted_dek, encrypted_data
		 FROM bb_credentials
		 WHERE id = $1 AND tenant_id = (SELECT id FROM tenants WHERE slug = $2 LIMIT 1)`,
		credID, s.tenantSlug,
	).Scan(&deviceID, &credType, &encDEK, &encData)
	if err != nil {
		return nil, fmt.Errorf("get credential: %w", err)
	}

	// Reconstruct AAD
	aad := []byte(fmt.Sprintf("%s||%s||%s", deviceID, s.tenantSlug, credType))

	plaintext, err := s.enc.Decrypt(encDEK, encData, aad)
	if err != nil {
		return nil, fmt.Errorf("decrypt credential: %w", err)
	}

	// Audit the decryption
	if err := s.audit.WriteStrict(ctx, audit.Entry{
		TenantID: s.tenantSlug,
		UserID:   userID,
		Action:   "bigbrother.credential.decrypted",
		Resource: fmt.Sprintf("device:%s/cred:%s", deviceID, credID),
	}); err != nil {
		clear(plaintext)
		return nil, fmt.Errorf("audit failed, decrypt aborted: %w", err)
	}

	return plaintext, nil
}

// Delete removes a credential and zeros the memory.
func (s *CredentialService) Delete(ctx context.Context, credID, userID, ip string) error {
	tag, err := s.db.Exec(ctx,
		`DELETE FROM bb_credentials
		 WHERE id = $1 AND tenant_id = (SELECT id FROM tenants WHERE slug = $2 LIMIT 1)`,
		credID, s.tenantSlug)
	if err != nil {
		return fmt.Errorf("delete credential: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("credential not found")
	}

	s.audit.Write(ctx, audit.Entry{
		TenantID: s.tenantSlug,
		UserID:   userID,
		Action:   "bigbrother.credential.deleted",
		Resource: fmt.Sprintf("cred:%s", credID),
		IP:       ip,
	})

	return nil
}
