// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const disableModuleForTenant = `-- name: DisableModuleForTenant :exec
UPDATE tenant_modules SET enabled = false WHERE tenant_id = $1 AND module_id = $2
`

type DisableModuleForTenantParams struct {
	TenantID string `json:"tenant_id"`
	ModuleID string `json:"module_id"`
}

func (q *Queries) DisableModuleForTenant(ctx context.Context, arg DisableModuleForTenantParams) error {
	_, err := q.db.Exec(ctx, disableModuleForTenant, arg.TenantID, arg.ModuleID)
	return err
}

const enableModuleForTenant = `-- name: EnableModuleForTenant :exec
INSERT INTO tenant_modules (tenant_id, module_id, enabled, config, enabled_by)
VALUES ($1, $2, true, $3, $4)
ON CONFLICT (tenant_id, module_id) DO UPDATE
SET enabled = true, config = $3, enabled_at = now(), enabled_by = $4
`

type EnableModuleForTenantParams struct {
	TenantID  string `json:"tenant_id"`
	ModuleID  string `json:"module_id"`
	Config    []byte `json:"config"`
	EnabledBy string `json:"enabled_by"`
}

func (q *Queries) EnableModuleForTenant(ctx context.Context, arg EnableModuleForTenantParams) error {
	_, err := q.db.Exec(ctx, enableModuleForTenant,
		arg.TenantID,
		arg.ModuleID,
		arg.Config,
		arg.EnabledBy,
	)
	return err
}

const getEnabledModulesForTenant = `-- name: GetEnabledModulesForTenant :many
SELECT m.id, m.name, m.category, m.icon, tm.config, tm.enabled_at
FROM tenant_modules tm
JOIN modules m ON m.id = tm.module_id
WHERE tm.tenant_id = $1 AND tm.enabled = true AND m.enabled = true
ORDER BY m.category, m.name
`

type GetEnabledModulesForTenantRow struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Category  string             `json:"category"`
	Icon      pgtype.Text        `json:"icon"`
	Config    []byte             `json:"config"`
	EnabledAt pgtype.Timestamptz `json:"enabled_at"`
}

func (q *Queries) GetEnabledModulesForTenant(ctx context.Context, tenantID string) ([]GetEnabledModulesForTenantRow, error) {
	rows, err := q.db.Query(ctx, getEnabledModulesForTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEnabledModulesForTenantRow{}
	for rows.Next() {
		var i GetEnabledModulesForTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Icon,
			&i.Config,
			&i.EnabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModuleConfigForTenant = `-- name: GetModuleConfigForTenant :one
SELECT config FROM tenant_modules
WHERE tenant_id = $1 AND module_id = $2 AND enabled = true
`

type GetModuleConfigForTenantParams struct {
	TenantID string `json:"tenant_id"`
	ModuleID string `json:"module_id"`
}

func (q *Queries) GetModuleConfigForTenant(ctx context.Context, arg GetModuleConfigForTenantParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getModuleConfigForTenant, arg.TenantID, arg.ModuleID)
	var config []byte
	err := row.Scan(&config)
	return config, err
}

const listModules = `-- name: ListModules :many
SELECT id, name, category, description, icon, version, requires, tier_min, enabled
FROM modules
WHERE enabled = true
ORDER BY category, name
`

func (q *Queries) ListModules(ctx context.Context) ([]Module, error) {
	rows, err := q.db.Query(ctx, listModules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Module{}
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Icon,
			&i.Version,
			&i.Requires,
			&i.TierMin,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
