// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (session_id, role, content, thinking, sources, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, session_id, role, content, thinking, sources, metadata, created_at
`

type CreateMessageParams struct {
	SessionID string      `json:"session_id"`
	Role      string      `json:"role"`
	Content   string      `json:"content"`
	Thinking  pgtype.Text `json:"thinking"`
	Sources   []byte      `json:"sources"`
	Metadata  []byte      `json:"metadata"`
}

type CreateMessageRow struct {
	ID        string             `json:"id"`
	SessionID string             `json:"session_id"`
	Role      string             `json:"role"`
	Content   string             `json:"content"`
	Thinking  pgtype.Text        `json:"thinking"`
	Sources   []byte             `json:"sources"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.Thinking,
		arg.Sources,
		arg.Metadata,
	)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.Thinking,
		&i.Sources,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, title, collection)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, collection, is_saved, created_at, updated_at
`

type CreateSessionParams struct {
	UserID     string      `json:"user_id"`
	Title      string      `json:"title"`
	Collection pgtype.Text `json:"collection"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.Title, arg.Collection)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Collection,
		&i.IsSaved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE id = $1 AND user_id = $2
`

type DeleteSessionParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, title, collection, is_saved, created_at, updated_at
FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Collection,
		&i.IsSaved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, session_id, role, content, thinking, sources, metadata, created_at
FROM messages WHERE session_id = $1
ORDER BY created_at
`

type ListMessagesRow struct {
	ID        string             `json:"id"`
	SessionID string             `json:"session_id"`
	Role      string             `json:"role"`
	Content   string             `json:"content"`
	Thinking  pgtype.Text        `json:"thinking"`
	Sources   []byte             `json:"sources"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMessages(ctx context.Context, sessionID string) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesRow{}
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.Thinking,
			&i.Sources,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, title, collection, is_saved, created_at, updated_at
FROM sessions WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Collection,
			&i.IsSaved,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameSession = `-- name: RenameSession :execrows
UPDATE sessions SET title = $3, updated_at = now()
WHERE id = $1 AND user_id = $2
`

type RenameSessionParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	Title  string `json:"title"`
}

func (q *Queries) RenameSession(ctx context.Context, arg RenameSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameSession, arg.ID, arg.UserID, arg.Title)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
