// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatFeedback struct {
	ID        string             `json:"id"`
	MessageID string             `json:"message_id"`
	UserID    string             `json:"user_id"`
	Thumbs    string             `json:"thumbs"`
	Comment   pgtype.Text        `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID        string             `json:"id"`
	SessionID string             `json:"session_id"`
	Role      string             `json:"role"`
	Content   string             `json:"content"`
	Sources   []byte             `json:"sources"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Thinking  pgtype.Text        `json:"thinking"`
}

type Session struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	Title      string             `json:"title"`
	Collection pgtype.Text        `json:"collection"`
	IsSaved    bool               `json:"is_saved"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Tag struct {
	ID        string             `json:"id"`
	SessionID string             `json:"session_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID string `json:"id"`
}
