// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounting.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeFiscalYear = `-- name: CloseFiscalYear :execrows
UPDATE erp_fiscal_years
SET status = 'closed', closed_by = $3, closed_at = now(),
    closing_entry_id = $4, opening_entry_id = $5
WHERE id = $1 AND tenant_id = $2 AND status = 'open'
`

type CloseFiscalYearParams struct {
	ID             pgtype.UUID `json:"id"`
	TenantID       string      `json:"tenant_id"`
	ClosedBy       pgtype.Text `json:"closed_by"`
	ClosingEntryID pgtype.UUID `json:"closing_entry_id"`
	OpeningEntryID pgtype.UUID `json:"opening_entry_id"`
}

func (q *Queries) CloseFiscalYear(ctx context.Context, arg CloseFiscalYearParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeFiscalYear,
		arg.ID,
		arg.TenantID,
		arg.ClosedBy,
		arg.ClosingEntryID,
		arg.OpeningEntryID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO erp_accounts (tenant_id, code, name, parent_id, account_type, is_detail, cost_center_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, code, name, parent_id, account_type, is_detail, cost_center_id, active
`

type CreateAccountParams struct {
	TenantID     string      `json:"tenant_id"`
	Code         string      `json:"code"`
	Name         string      `json:"name"`
	ParentID     pgtype.UUID `json:"parent_id"`
	AccountType  string      `json:"account_type"`
	IsDetail     bool        `json:"is_detail"`
	CostCenterID pgtype.UUID `json:"cost_center_id"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (ErpAccount, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.ParentID,
		arg.AccountType,
		arg.IsDetail,
		arg.CostCenterID,
	)
	var i ErpAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ParentID,
		&i.AccountType,
		&i.IsDetail,
		&i.CostCenterID,
		&i.Active,
	)
	return i, err
}

const createCostCenter = `-- name: CreateCostCenter :one
INSERT INTO erp_cost_centers (tenant_id, code, name, parent_id)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, code, name, parent_id, active
`

type CreateCostCenterParams struct {
	TenantID string      `json:"tenant_id"`
	Code     string      `json:"code"`
	Name     string      `json:"name"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateCostCenter(ctx context.Context, arg CreateCostCenterParams) (ErpCostCenter, error) {
	row := q.db.QueryRow(ctx, createCostCenter,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.ParentID,
	)
	var i ErpCostCenter
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ParentID,
		&i.Active,
	)
	return i, err
}

const createFiscalYear = `-- name: CreateFiscalYear :one
INSERT INTO erp_fiscal_years (tenant_id, year, start_date, end_date, result_account_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, year, start_date, end_date, status, result_account_id,
    closed_by, closed_at, closing_entry_id, opening_entry_id
`

type CreateFiscalYearParams struct {
	TenantID        string      `json:"tenant_id"`
	Year            int32       `json:"year"`
	StartDate       pgtype.Date `json:"start_date"`
	EndDate         pgtype.Date `json:"end_date"`
	ResultAccountID pgtype.UUID `json:"result_account_id"`
}

type CreateFiscalYearRow struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        string             `json:"tenant_id"`
	Year            int32              `json:"year"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	Status          string             `json:"status"`
	ResultAccountID pgtype.UUID        `json:"result_account_id"`
	ClosedBy        pgtype.Text        `json:"closed_by"`
	ClosedAt        pgtype.Timestamptz `json:"closed_at"`
	ClosingEntryID  pgtype.UUID        `json:"closing_entry_id"`
	OpeningEntryID  pgtype.UUID        `json:"opening_entry_id"`
}

func (q *Queries) CreateFiscalYear(ctx context.Context, arg CreateFiscalYearParams) (CreateFiscalYearRow, error) {
	row := q.db.QueryRow(ctx, createFiscalYear,
		arg.TenantID,
		arg.Year,
		arg.StartDate,
		arg.EndDate,
		arg.ResultAccountID,
	)
	var i CreateFiscalYearRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Year,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ResultAccountID,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.ClosingEntryID,
		&i.OpeningEntryID,
	)
	return i, err
}

const createJournalEntry = `-- name: CreateJournalEntry :one
INSERT INTO erp_journal_entries (tenant_id, number, date, fiscal_year_id, concept, entry_type,
    reference_type, reference_id, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, number, date, fiscal_year_id, concept, entry_type,
    reference_type, reference_id, user_id, status, created_at
`

type CreateJournalEntryParams struct {
	TenantID      string      `json:"tenant_id"`
	Number        string      `json:"number"`
	Date          pgtype.Date `json:"date"`
	FiscalYearID  pgtype.UUID `json:"fiscal_year_id"`
	Concept       string      `json:"concept"`
	EntryType     string      `json:"entry_type"`
	ReferenceType pgtype.Text `json:"reference_type"`
	ReferenceID   pgtype.UUID `json:"reference_id"`
	UserID        string      `json:"user_id"`
}

type CreateJournalEntryRow struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      string             `json:"tenant_id"`
	Number        string             `json:"number"`
	Date          pgtype.Date        `json:"date"`
	FiscalYearID  pgtype.UUID        `json:"fiscal_year_id"`
	Concept       string             `json:"concept"`
	EntryType     string             `json:"entry_type"`
	ReferenceType pgtype.Text        `json:"reference_type"`
	ReferenceID   pgtype.UUID        `json:"reference_id"`
	UserID        string             `json:"user_id"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (CreateJournalEntryRow, error) {
	row := q.db.QueryRow(ctx, createJournalEntry,
		arg.TenantID,
		arg.Number,
		arg.Date,
		arg.FiscalYearID,
		arg.Concept,
		arg.EntryType,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.UserID,
	)
	var i CreateJournalEntryRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Number,
		&i.Date,
		&i.FiscalYearID,
		&i.Concept,
		&i.EntryType,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createJournalLine = `-- name: CreateJournalLine :one
INSERT INTO erp_journal_lines (tenant_id, entry_id, account_id, cost_center_id, entry_date, debit, credit, description, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, entry_id, account_id, cost_center_id, entry_date, debit, credit, description, sort_order
`

type CreateJournalLineParams struct {
	TenantID     string         `json:"tenant_id"`
	EntryID      pgtype.UUID    `json:"entry_id"`
	AccountID    pgtype.UUID    `json:"account_id"`
	CostCenterID pgtype.UUID    `json:"cost_center_id"`
	EntryDate    pgtype.Date    `json:"entry_date"`
	Debit        pgtype.Numeric `json:"debit"`
	Credit       pgtype.Numeric `json:"credit"`
	Description  string         `json:"description"`
	SortOrder    int32          `json:"sort_order"`
}

func (q *Queries) CreateJournalLine(ctx context.Context, arg CreateJournalLineParams) (ErpJournalLine, error) {
	row := q.db.QueryRow(ctx, createJournalLine,
		arg.TenantID,
		arg.EntryID,
		arg.AccountID,
		arg.CostCenterID,
		arg.EntryDate,
		arg.Debit,
		arg.Credit,
		arg.Description,
		arg.SortOrder,
	)
	var i ErpJournalLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntryID,
		&i.AccountID,
		&i.CostCenterID,
		&i.EntryDate,
		&i.Debit,
		&i.Credit,
		&i.Description,
		&i.SortOrder,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, tenant_id, code, name, parent_id, account_type, is_detail, cost_center_id, active
FROM erp_accounts WHERE id = $1 AND tenant_id = $2
`

type GetAccountParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (ErpAccount, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.ID, arg.TenantID)
	var i ErpAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ParentID,
		&i.AccountType,
		&i.IsDetail,
		&i.CostCenterID,
		&i.Active,
	)
	return i, err
}

const getAccountBalance = `-- name: GetAccountBalance :many
SELECT jl.account_id, a.code AS account_code, a.name AS account_name,
       SUM(jl.debit)::NUMERIC(16,2) AS total_debit,
       SUM(jl.credit)::NUMERIC(16,2) AS total_credit,
       (SUM(jl.debit) - SUM(jl.credit))::NUMERIC(16,2) AS balance
FROM erp_journal_lines jl
JOIN erp_accounts a ON a.id = jl.account_id
JOIN erp_journal_entries je ON je.id = jl.entry_id
WHERE jl.tenant_id = $1 AND je.status = 'posted'
  AND ($2::DATE IS NULL OR jl.entry_date >= $2::DATE)
  AND ($3::DATE IS NULL OR jl.entry_date <= $3::DATE)
GROUP BY jl.account_id, a.code, a.name
ORDER BY a.code
`

type GetAccountBalanceParams struct {
	TenantID string      `json:"tenant_id"`
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
}

type GetAccountBalanceRow struct {
	AccountID   pgtype.UUID    `json:"account_id"`
	AccountCode string         `json:"account_code"`
	AccountName string         `json:"account_name"`
	TotalDebit  pgtype.Numeric `json:"total_debit"`
	TotalCredit pgtype.Numeric `json:"total_credit"`
	Balance     pgtype.Numeric `json:"balance"`
}

func (q *Queries) GetAccountBalance(ctx context.Context, arg GetAccountBalanceParams) ([]GetAccountBalanceRow, error) {
	rows, err := q.db.Query(ctx, getAccountBalance, arg.TenantID, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAccountBalanceRow{}
	for rows.Next() {
		var i GetAccountBalanceRow
		if err := rows.Scan(
			&i.AccountID,
			&i.AccountCode,
			&i.AccountName,
			&i.TotalDebit,
			&i.TotalCredit,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountBalancesForClose = `-- name: GetAccountBalancesForClose :many
SELECT a.id, a.code, a.name, a.account_type,
    COALESCE(SUM(jl.debit), 0)::NUMERIC(16,2) AS total_debit,
    COALESCE(SUM(jl.credit), 0)::NUMERIC(16,2) AS total_credit,
    (COALESCE(SUM(jl.debit), 0) - COALESCE(SUM(jl.credit), 0))::NUMERIC(16,2) AS balance
FROM erp_accounts a
JOIN erp_journal_lines jl ON jl.account_id = a.id AND jl.tenant_id = a.tenant_id
JOIN erp_journal_entries je ON je.id = jl.entry_id AND je.tenant_id = jl.tenant_id
WHERE a.tenant_id = $1
    AND a.is_detail = true
    AND je.fiscal_year_id = $2
    AND je.status = 'posted'
GROUP BY a.id, a.code, a.name, a.account_type
HAVING COALESCE(SUM(jl.debit), 0) - COALESCE(SUM(jl.credit), 0) != 0
`

type GetAccountBalancesForCloseParams struct {
	TenantID     string      `json:"tenant_id"`
	FiscalYearID pgtype.UUID `json:"fiscal_year_id"`
}

type GetAccountBalancesForCloseRow struct {
	ID          pgtype.UUID    `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	AccountType string         `json:"account_type"`
	TotalDebit  pgtype.Numeric `json:"total_debit"`
	TotalCredit pgtype.Numeric `json:"total_credit"`
	Balance     pgtype.Numeric `json:"balance"`
}

func (q *Queries) GetAccountBalancesForClose(ctx context.Context, arg GetAccountBalancesForCloseParams) ([]GetAccountBalancesForCloseRow, error) {
	rows, err := q.db.Query(ctx, getAccountBalancesForClose, arg.TenantID, arg.FiscalYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAccountBalancesForCloseRow{}
	for rows.Next() {
		var i GetAccountBalancesForCloseRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.AccountType,
			&i.TotalDebit,
			&i.TotalCredit,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFiscalYear = `-- name: GetFiscalYear :one
SELECT id, tenant_id, year, start_date, end_date, status, result_account_id,
       closed_by, closed_at, closing_entry_id, opening_entry_id
FROM erp_fiscal_years WHERE id = $1 AND tenant_id = $2
`

type GetFiscalYearParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

type GetFiscalYearRow struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        string             `json:"tenant_id"`
	Year            int32              `json:"year"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	Status          string             `json:"status"`
	ResultAccountID pgtype.UUID        `json:"result_account_id"`
	ClosedBy        pgtype.Text        `json:"closed_by"`
	ClosedAt        pgtype.Timestamptz `json:"closed_at"`
	ClosingEntryID  pgtype.UUID        `json:"closing_entry_id"`
	OpeningEntryID  pgtype.UUID        `json:"opening_entry_id"`
}

func (q *Queries) GetFiscalYear(ctx context.Context, arg GetFiscalYearParams) (GetFiscalYearRow, error) {
	row := q.db.QueryRow(ctx, getFiscalYear, arg.ID, arg.TenantID)
	var i GetFiscalYearRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Year,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ResultAccountID,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.ClosingEntryID,
		&i.OpeningEntryID,
	)
	return i, err
}

const getFiscalYearByDate = `-- name: GetFiscalYearByDate :one
-- Returns the open fiscal year that contains the given date, if any.
SELECT id, tenant_id, year, start_date, end_date, status, result_account_id,
       closed_by, closed_at, closing_entry_id, opening_entry_id
FROM erp_fiscal_years
WHERE tenant_id = $1 AND start_date <= $2 AND end_date >= $2 AND status = 'open'
LIMIT 1
`

type GetFiscalYearByDateParams struct {
	TenantID string      `json:"tenant_id"`
	Date     pgtype.Date `json:"date"`
}

type GetFiscalYearByDateRow = GetFiscalYearRow

func (q *Queries) GetFiscalYearByDate(ctx context.Context, arg GetFiscalYearByDateParams) (GetFiscalYearByDateRow, error) {
	row := q.db.QueryRow(ctx, getFiscalYearByDate, arg.TenantID, arg.Date)
	var i GetFiscalYearByDateRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Year,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ResultAccountID,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.ClosingEntryID,
		&i.OpeningEntryID,
	)
	return i, err
}

const getJournalEntry = `-- name: GetJournalEntry :one
SELECT id, tenant_id, number, date, fiscal_year_id, concept, entry_type,
       reference_type, reference_id, user_id, status, created_at
FROM erp_journal_entries WHERE id = $1 AND tenant_id = $2
`

type GetJournalEntryParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

type GetJournalEntryRow struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      string             `json:"tenant_id"`
	Number        string             `json:"number"`
	Date          pgtype.Date        `json:"date"`
	FiscalYearID  pgtype.UUID        `json:"fiscal_year_id"`
	Concept       string             `json:"concept"`
	EntryType     string             `json:"entry_type"`
	ReferenceType pgtype.Text        `json:"reference_type"`
	ReferenceID   pgtype.UUID        `json:"reference_id"`
	UserID        string             `json:"user_id"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetJournalEntry(ctx context.Context, arg GetJournalEntryParams) (GetJournalEntryRow, error) {
	row := q.db.QueryRow(ctx, getJournalEntry, arg.ID, arg.TenantID)
	var i GetJournalEntryRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Number,
		&i.Date,
		&i.FiscalYearID,
		&i.Concept,
		&i.EntryType,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getLedger = `-- name: GetLedger :many
SELECT jl.id, jl.entry_date, jl.debit, jl.credit, jl.description,
       je.number AS entry_number, je.concept
FROM erp_journal_lines jl
JOIN erp_journal_entries je ON je.id = jl.entry_id
WHERE jl.tenant_id = $1 AND jl.account_id = $2 AND je.status = 'posted'
  AND ($5::DATE IS NULL OR jl.entry_date >= $5::DATE)
  AND ($6::DATE IS NULL OR jl.entry_date <= $6::DATE)
ORDER BY jl.entry_date, je.number
LIMIT $3 OFFSET $4
`

type GetLedgerParams struct {
	TenantID  string      `json:"tenant_id"`
	AccountID pgtype.UUID `json:"account_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
	DateFrom  pgtype.Date `json:"date_from"`
	DateTo    pgtype.Date `json:"date_to"`
}

type GetLedgerRow struct {
	ID          pgtype.UUID    `json:"id"`
	EntryDate   pgtype.Date    `json:"entry_date"`
	Debit       pgtype.Numeric `json:"debit"`
	Credit      pgtype.Numeric `json:"credit"`
	Description string         `json:"description"`
	EntryNumber string         `json:"entry_number"`
	Concept     string         `json:"concept"`
}

func (q *Queries) GetLedger(ctx context.Context, arg GetLedgerParams) ([]GetLedgerRow, error) {
	rows, err := q.db.Query(ctx, getLedger,
		arg.TenantID,
		arg.AccountID,
		arg.Limit,
		arg.Offset,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLedgerRow{}
	for rows.Next() {
		var i GetLedgerRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryDate,
			&i.Debit,
			&i.Credit,
			&i.Description,
			&i.EntryNumber,
			&i.Concept,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, tenant_id, code, name, parent_id, account_type, is_detail, cost_center_id, active
FROM erp_accounts
WHERE tenant_id = $1 AND ($2::BOOLEAN = false OR active = true)
ORDER BY code
`

type ListAccountsParams struct {
	TenantID   string `json:"tenant_id"`
	ActiveOnly bool   `json:"active_only"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ErpAccount, error) {
	rows, err := q.db.Query(ctx, listAccounts, arg.TenantID, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpAccount{}
	for rows.Next() {
		var i ErpAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.ParentID,
			&i.AccountType,
			&i.IsDetail,
			&i.CostCenterID,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCostCenters = `-- name: ListCostCenters :many
SELECT id, tenant_id, code, name, parent_id, active
FROM erp_cost_centers
WHERE tenant_id = $1 AND ($2::BOOLEAN = false OR active = true)
ORDER BY code
`

type ListCostCentersParams struct {
	TenantID   string `json:"tenant_id"`
	ActiveOnly bool   `json:"active_only"`
}

func (q *Queries) ListCostCenters(ctx context.Context, arg ListCostCentersParams) ([]ErpCostCenter, error) {
	rows, err := q.db.Query(ctx, listCostCenters, arg.TenantID, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpCostCenter{}
	for rows.Next() {
		var i ErpCostCenter
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.ParentID,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftEntriesInPeriod = `-- name: ListDraftEntriesInPeriod :many
SELECT id, number FROM erp_journal_entries
WHERE tenant_id = $1 AND fiscal_year_id = $2 AND status = 'draft'
`

type ListDraftEntriesInPeriodParams struct {
	TenantID     string      `json:"tenant_id"`
	FiscalYearID pgtype.UUID `json:"fiscal_year_id"`
}

type ListDraftEntriesInPeriodRow struct {
	ID     pgtype.UUID `json:"id"`
	Number string      `json:"number"`
}

func (q *Queries) ListDraftEntriesInPeriod(ctx context.Context, arg ListDraftEntriesInPeriodParams) ([]ListDraftEntriesInPeriodRow, error) {
	rows, err := q.db.Query(ctx, listDraftEntriesInPeriod, arg.TenantID, arg.FiscalYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDraftEntriesInPeriodRow{}
	for rows.Next() {
		var i ListDraftEntriesInPeriodRow
		if err := rows.Scan(&i.ID, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiscalYears = `-- name: ListFiscalYears :many
SELECT id, tenant_id, year, start_date, end_date, status, result_account_id,
       closed_by, closed_at, closing_entry_id, opening_entry_id
FROM erp_fiscal_years WHERE tenant_id = $1 ORDER BY year DESC
`

type ListFiscalYearsRow struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        string             `json:"tenant_id"`
	Year            int32              `json:"year"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	Status          string             `json:"status"`
	ResultAccountID pgtype.UUID        `json:"result_account_id"`
	ClosedBy        pgtype.Text        `json:"closed_by"`
	ClosedAt        pgtype.Timestamptz `json:"closed_at"`
	ClosingEntryID  pgtype.UUID        `json:"closing_entry_id"`
	OpeningEntryID  pgtype.UUID        `json:"opening_entry_id"`
}

func (q *Queries) ListFiscalYears(ctx context.Context, tenantID string) ([]ListFiscalYearsRow, error) {
	rows, err := q.db.Query(ctx, listFiscalYears, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFiscalYearsRow{}
	for rows.Next() {
		var i ListFiscalYearsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Year,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.ResultAccountID,
			&i.ClosedBy,
			&i.ClosedAt,
			&i.ClosingEntryID,
			&i.OpeningEntryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntries = `-- name: ListJournalEntries :many
SELECT id, tenant_id, number, date, fiscal_year_id, concept, entry_type,
       reference_type, reference_id, user_id, status, created_at
FROM erp_journal_entries
WHERE tenant_id = $1
  AND ($4::DATE IS NULL OR date >= $4::DATE)
  AND ($5::DATE IS NULL OR date <= $5::DATE)
  AND ($6::TEXT = '' OR status = $6::TEXT)
ORDER BY date DESC, number DESC
LIMIT $2 OFFSET $3
`

type ListJournalEntriesParams struct {
	TenantID     string      `json:"tenant_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
	DateFrom     pgtype.Date `json:"date_from"`
	DateTo       pgtype.Date `json:"date_to"`
	StatusFilter string      `json:"status_filter"`
}

type ListJournalEntriesRow struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      string             `json:"tenant_id"`
	Number        string             `json:"number"`
	Date          pgtype.Date        `json:"date"`
	FiscalYearID  pgtype.UUID        `json:"fiscal_year_id"`
	Concept       string             `json:"concept"`
	EntryType     string             `json:"entry_type"`
	ReferenceType pgtype.Text        `json:"reference_type"`
	ReferenceID   pgtype.UUID        `json:"reference_id"`
	UserID        string             `json:"user_id"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListJournalEntries(ctx context.Context, arg ListJournalEntriesParams) ([]ListJournalEntriesRow, error) {
	rows, err := q.db.Query(ctx, listJournalEntries,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.DateFrom,
		arg.DateTo,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJournalEntriesRow{}
	for rows.Next() {
		var i ListJournalEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Number,
			&i.Date,
			&i.FiscalYearID,
			&i.Concept,
			&i.EntryType,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalLines = `-- name: ListJournalLines :many
SELECT jl.id, jl.tenant_id, jl.entry_id, jl.account_id, jl.cost_center_id,
       jl.entry_date, jl.debit, jl.credit, jl.description, jl.sort_order,
       a.code AS account_code, a.name AS account_name
FROM erp_journal_lines jl
JOIN erp_accounts a ON a.id = jl.account_id
WHERE jl.entry_id = $1 AND jl.tenant_id = $2
ORDER BY jl.sort_order
`

type ListJournalLinesParams struct {
	EntryID  pgtype.UUID `json:"entry_id"`
	TenantID string      `json:"tenant_id"`
}

type ListJournalLinesRow struct {
	ID           pgtype.UUID    `json:"id"`
	TenantID     string         `json:"tenant_id"`
	EntryID      pgtype.UUID    `json:"entry_id"`
	AccountID    pgtype.UUID    `json:"account_id"`
	CostCenterID pgtype.UUID    `json:"cost_center_id"`
	EntryDate    pgtype.Date    `json:"entry_date"`
	Debit        pgtype.Numeric `json:"debit"`
	Credit       pgtype.Numeric `json:"credit"`
	Description  string         `json:"description"`
	SortOrder    int32          `json:"sort_order"`
	AccountCode  string         `json:"account_code"`
	AccountName  string         `json:"account_name"`
}

func (q *Queries) ListJournalLines(ctx context.Context, arg ListJournalLinesParams) ([]ListJournalLinesRow, error) {
	rows, err := q.db.Query(ctx, listJournalLines, arg.EntryID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJournalLinesRow{}
	for rows.Next() {
		var i ListJournalLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntryID,
			&i.AccountID,
			&i.CostCenterID,
			&i.EntryDate,
			&i.Debit,
			&i.Credit,
			&i.Description,
			&i.SortOrder,
			&i.AccountCode,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEntryReversed = `-- name: MarkEntryReversed :execrows
UPDATE erp_journal_entries SET status = 'reversed', reversed_by = $3
WHERE id = $1 AND tenant_id = $2 AND status = 'posted'
`

type MarkEntryReversedParams struct {
	ID         pgtype.UUID `json:"id"`
	TenantID   string      `json:"tenant_id"`
	ReversedBy pgtype.UUID `json:"reversed_by"`
}

func (q *Queries) MarkEntryReversed(ctx context.Context, arg MarkEntryReversedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markEntryReversed, arg.ID, arg.TenantID, arg.ReversedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const postJournalEntry = `-- name: PostJournalEntry :execrows
UPDATE erp_journal_entries SET status = 'posted'
WHERE id = $1 AND tenant_id = $2 AND status = 'draft'
`

type PostJournalEntryParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) PostJournalEntry(ctx context.Context, arg PostJournalEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, postJournalEntry, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setFiscalYearResultAccount = `-- name: SetFiscalYearResultAccount :execrows
UPDATE erp_fiscal_years SET result_account_id = $3
WHERE id = $1 AND tenant_id = $2 AND status = 'open'
`

type SetFiscalYearResultAccountParams struct {
	ID              pgtype.UUID `json:"id"`
	TenantID        string      `json:"tenant_id"`
	ResultAccountID pgtype.UUID `json:"result_account_id"`
}

func (q *Queries) SetFiscalYearResultAccount(ctx context.Context, arg SetFiscalYearResultAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, setFiscalYearResultAccount, arg.ID, arg.TenantID, arg.ResultAccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE erp_accounts
SET code = $3, name = $4, parent_id = $5, account_type = $6, is_detail = $7,
    cost_center_id = $8, active = $9
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, code, name, parent_id, account_type, is_detail, cost_center_id, active
`

type UpdateAccountParams struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     string      `json:"tenant_id"`
	Code         string      `json:"code"`
	Name         string      `json:"name"`
	ParentID     pgtype.UUID `json:"parent_id"`
	AccountType  string      `json:"account_type"`
	IsDetail     bool        `json:"is_detail"`
	CostCenterID pgtype.UUID `json:"cost_center_id"`
	Active       bool        `json:"active"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (ErpAccount, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.ParentID,
		arg.AccountType,
		arg.IsDetail,
		arg.CostCenterID,
		arg.Active,
	)
	var i ErpAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ParentID,
		&i.AccountType,
		&i.IsDetail,
		&i.CostCenterID,
		&i.Active,
	)
	return i, err
}
