// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalogs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCatalog = `-- name: CreateCatalog :one
INSERT INTO erp_catalogs (tenant_id, type, code, name, parent_id, sort_order, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, type, code, name, parent_id, sort_order, active, metadata, created_at, updated_at
`

type CreateCatalogParams struct {
	TenantID  string      `json:"tenant_id"`
	Type      string      `json:"type"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	ParentID  pgtype.UUID `json:"parent_id"`
	SortOrder int32       `json:"sort_order"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) CreateCatalog(ctx context.Context, arg CreateCatalogParams) (ErpCatalog, error) {
	row := q.db.QueryRow(ctx, createCatalog,
		arg.TenantID,
		arg.Type,
		arg.Code,
		arg.Name,
		arg.ParentID,
		arg.SortOrder,
		arg.Metadata,
	)
	var i ErpCatalog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Code,
		&i.Name,
		&i.ParentID,
		&i.SortOrder,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCatalog = `-- name: DeleteCatalog :execrows
UPDATE erp_catalogs SET active = false, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type DeleteCatalogParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) DeleteCatalog(ctx context.Context, arg DeleteCatalogParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCatalog, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCatalog = `-- name: GetCatalog :one
SELECT id, tenant_id, type, code, name, parent_id, sort_order, active, metadata, created_at, updated_at
FROM erp_catalogs
WHERE id = $1 AND tenant_id = $2
`

type GetCatalogParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) GetCatalog(ctx context.Context, arg GetCatalogParams) (ErpCatalog, error) {
	row := q.db.QueryRow(ctx, getCatalog, arg.ID, arg.TenantID)
	var i ErpCatalog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Code,
		&i.Name,
		&i.ParentID,
		&i.SortOrder,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCatalogTypes = `-- name: ListCatalogTypes :many
SELECT DISTINCT type FROM erp_catalogs
WHERE tenant_id = $1
ORDER BY type
`

func (q *Queries) ListCatalogTypes(ctx context.Context, tenantID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listCatalogTypes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var type_ string
		if err := rows.Scan(&type_); err != nil {
			return nil, err
		}
		items = append(items, type_)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogs = `-- name: ListCatalogs :many
SELECT id, tenant_id, type, code, name, parent_id, sort_order, active, metadata, created_at, updated_at
FROM erp_catalogs
WHERE tenant_id = $1 AND type = $2 AND ($3::BOOLEAN = false OR active = true)
ORDER BY sort_order, name
`

type ListCatalogsParams struct {
	TenantID   string `json:"tenant_id"`
	Type       string `json:"type"`
	ActiveOnly bool   `json:"active_only"`
}

func (q *Queries) ListCatalogs(ctx context.Context, arg ListCatalogsParams) ([]ErpCatalog, error) {
	rows, err := q.db.Query(ctx, listCatalogs, arg.TenantID, arg.Type, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpCatalog{}
	for rows.Next() {
		var i ErpCatalog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Code,
			&i.Name,
			&i.ParentID,
			&i.SortOrder,
			&i.Active,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCatalog = `-- name: UpdateCatalog :one
UPDATE erp_catalogs
SET code = $3, name = $4, parent_id = $5, sort_order = $6, active = $7, metadata = $8, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, type, code, name, parent_id, sort_order, active, metadata, created_at, updated_at
`

type UpdateCatalogParams struct {
	ID        pgtype.UUID `json:"id"`
	TenantID  string      `json:"tenant_id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	ParentID  pgtype.UUID `json:"parent_id"`
	SortOrder int32       `json:"sort_order"`
	Active    bool        `json:"active"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) UpdateCatalog(ctx context.Context, arg UpdateCatalogParams) (ErpCatalog, error) {
	row := q.db.QueryRow(ctx, updateCatalog,
		arg.ID,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.ParentID,
		arg.SortOrder,
		arg.Active,
		arg.Metadata,
	)
	var i ErpCatalog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Code,
		&i.Name,
		&i.ParentID,
		&i.SortOrder,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
