// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: current_accounts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccountMovement = `-- name: CreateAccountMovement :one
INSERT INTO erp_account_movements (tenant_id, entity_id, date, movement_type, direction,
    amount, balance, invoice_id, treasury_id, journal_entry_id, notes, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, tenant_id, entity_id, date, movement_type, direction, amount, balance,
    invoice_id, treasury_id, journal_entry_id, notes, user_id, created_at
`

type CreateAccountMovementParams struct {
	TenantID       string         `json:"tenant_id"`
	EntityID       pgtype.UUID    `json:"entity_id"`
	Date           pgtype.Date    `json:"date"`
	MovementType   string         `json:"movement_type"`
	Direction      string         `json:"direction"`
	Amount         pgtype.Numeric `json:"amount"`
	Balance        pgtype.Numeric `json:"balance"`
	InvoiceID      pgtype.UUID    `json:"invoice_id"`
	TreasuryID     pgtype.UUID    `json:"treasury_id"`
	JournalEntryID pgtype.UUID    `json:"journal_entry_id"`
	Notes          string         `json:"notes"`
	UserID         string         `json:"user_id"`
}

func (q *Queries) CreateAccountMovement(ctx context.Context, arg CreateAccountMovementParams) (ErpAccountMovement, error) {
	row := q.db.QueryRow(ctx, createAccountMovement,
		arg.TenantID,
		arg.EntityID,
		arg.Date,
		arg.MovementType,
		arg.Direction,
		arg.Amount,
		arg.Balance,
		arg.InvoiceID,
		arg.TreasuryID,
		arg.JournalEntryID,
		arg.Notes,
		arg.UserID,
	)
	var i ErpAccountMovement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityID,
		&i.Date,
		&i.MovementType,
		&i.Direction,
		&i.Amount,
		&i.Balance,
		&i.InvoiceID,
		&i.TreasuryID,
		&i.JournalEntryID,
		&i.Notes,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const createPaymentAllocation = `-- name: CreatePaymentAllocation :one
INSERT INTO erp_payment_allocations (tenant_id, payment_id, invoice_id, amount)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, payment_id, invoice_id, amount, created_at
`

type CreatePaymentAllocationParams struct {
	TenantID  string         `json:"tenant_id"`
	PaymentID pgtype.UUID    `json:"payment_id"`
	InvoiceID pgtype.UUID    `json:"invoice_id"`
	Amount    pgtype.Numeric `json:"amount"`
}

func (q *Queries) CreatePaymentAllocation(ctx context.Context, arg CreatePaymentAllocationParams) (ErpPaymentAllocation, error) {
	row := q.db.QueryRow(ctx, createPaymentAllocation,
		arg.TenantID,
		arg.PaymentID,
		arg.InvoiceID,
		arg.Amount,
	)
	var i ErpPaymentAllocation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PaymentID,
		&i.InvoiceID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getEntityBalances = `-- name: GetEntityBalances :many
SELECT am.entity_id, e.name AS entity_name, e.type AS entity_type, am.direction,
       SUM(am.balance)::NUMERIC(16,2) AS open_balance
FROM erp_account_movements am
JOIN erp_entities e ON e.id = am.entity_id
WHERE am.tenant_id = $1 AND am.balance > 0
  AND ($2::TEXT = '' OR am.direction = $2::TEXT)
GROUP BY am.entity_id, e.name, e.type, am.direction
ORDER BY open_balance DESC
`

type GetEntityBalancesParams struct {
	TenantID        string `json:"tenant_id"`
	DirectionFilter string `json:"direction_filter"`
}

type GetEntityBalancesRow struct {
	EntityID    pgtype.UUID    `json:"entity_id"`
	EntityName  string         `json:"entity_name"`
	EntityType  string         `json:"entity_type"`
	Direction   string         `json:"direction"`
	OpenBalance pgtype.Numeric `json:"open_balance"`
}

func (q *Queries) GetEntityBalances(ctx context.Context, arg GetEntityBalancesParams) ([]GetEntityBalancesRow, error) {
	rows, err := q.db.Query(ctx, getEntityBalances, arg.TenantID, arg.DirectionFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEntityBalancesRow{}
	for rows.Next() {
		var i GetEntityBalancesRow
		if err := rows.Scan(
			&i.EntityID,
			&i.EntityName,
			&i.EntityType,
			&i.Direction,
			&i.OpenBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverdueInvoices = `-- name: GetOverdueInvoices :many
SELECT am.id, am.entity_id, am.date, am.amount, am.balance, am.direction, am.created_at,
       e.name AS entity_name, i.number AS invoice_number, i.due_date
FROM erp_account_movements am
JOIN erp_entities e ON e.id = am.entity_id
LEFT JOIN erp_invoices i ON i.id = am.invoice_id
WHERE am.tenant_id = $1 AND am.balance > 0 AND am.movement_type = 'invoice'
  AND i.due_date IS NOT NULL AND i.due_date < CURRENT_DATE
ORDER BY i.due_date
`

type GetOverdueInvoicesRow struct {
	ID            pgtype.UUID        `json:"id"`
	EntityID      pgtype.UUID        `json:"entity_id"`
	Date          pgtype.Date        `json:"date"`
	Amount        pgtype.Numeric     `json:"amount"`
	Balance       pgtype.Numeric     `json:"balance"`
	Direction     string             `json:"direction"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	EntityName    string             `json:"entity_name"`
	InvoiceNumber pgtype.Text        `json:"invoice_number"`
	DueDate       pgtype.Date        `json:"due_date"`
}

func (q *Queries) GetOverdueInvoices(ctx context.Context, tenantID string) ([]GetOverdueInvoicesRow, error) {
	rows, err := q.db.Query(ctx, getOverdueInvoices, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOverdueInvoicesRow{}
	for rows.Next() {
		var i GetOverdueInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.Date,
			&i.Amount,
			&i.Balance,
			&i.Direction,
			&i.CreatedAt,
			&i.EntityName,
			&i.InvoiceNumber,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountMovements = `-- name: ListAccountMovements :many
SELECT am.id, am.tenant_id, am.entity_id, am.date, am.movement_type, am.direction,
       am.amount, am.balance, am.invoice_id, am.treasury_id, am.notes, am.user_id, am.created_at,
       e.name AS entity_name
FROM erp_account_movements am
JOIN erp_entities e ON e.id = am.entity_id
WHERE am.tenant_id = $1
  AND ($4::UUID IS NULL OR am.entity_id = $4::UUID)
  AND ($5::TEXT = '' OR am.direction = $5::TEXT)
  AND ($6::DATE IS NULL OR am.date >= $6::DATE)
  AND ($7::DATE IS NULL OR am.date <= $7::DATE)
ORDER BY am.date DESC, am.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAccountMovementsParams struct {
	TenantID        string      `json:"tenant_id"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
	EntityFilter    pgtype.UUID `json:"entity_filter"`
	DirectionFilter string      `json:"direction_filter"`
	DateFrom        pgtype.Date `json:"date_from"`
	DateTo          pgtype.Date `json:"date_to"`
}

type ListAccountMovementsRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     string             `json:"tenant_id"`
	EntityID     pgtype.UUID        `json:"entity_id"`
	Date         pgtype.Date        `json:"date"`
	MovementType string             `json:"movement_type"`
	Direction    string             `json:"direction"`
	Amount       pgtype.Numeric     `json:"amount"`
	Balance      pgtype.Numeric     `json:"balance"`
	InvoiceID    pgtype.UUID        `json:"invoice_id"`
	TreasuryID   pgtype.UUID        `json:"treasury_id"`
	Notes        string             `json:"notes"`
	UserID       string             `json:"user_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	EntityName   string             `json:"entity_name"`
}

func (q *Queries) ListAccountMovements(ctx context.Context, arg ListAccountMovementsParams) ([]ListAccountMovementsRow, error) {
	rows, err := q.db.Query(ctx, listAccountMovements,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.EntityFilter,
		arg.DirectionFilter,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountMovementsRow{}
	for rows.Next() {
		var i ListAccountMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityID,
			&i.Date,
			&i.MovementType,
			&i.Direction,
			&i.Amount,
			&i.Balance,
			&i.InvoiceID,
			&i.TreasuryID,
			&i.Notes,
			&i.UserID,
			&i.CreatedAt,
			&i.EntityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovementBalance = `-- name: UpdateMovementBalance :execrows
UPDATE erp_account_movements SET balance = balance - $3
WHERE id = $1 AND tenant_id = $2 AND balance >= $3
`

type UpdateMovementBalanceParams struct {
	ID       pgtype.UUID    `json:"id"`
	TenantID string         `json:"tenant_id"`
	Balance  pgtype.Numeric `json:"balance"`
}

func (q *Queries) UpdateMovementBalance(ctx context.Context, arg UpdateMovementBalanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMovementBalance, arg.ID, arg.TenantID, arg.Balance)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
