// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoicing.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO erp_invoices (tenant_id, number, date, due_date, invoice_type, direction,
    entity_id, currency_id, subtotal, tax_amount, total, order_id, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, tenant_id, number, date, due_date, invoice_type, direction,
    entity_id, currency_id, subtotal, tax_amount, total, order_id,
    journal_entry_id, afip_cae, afip_cae_due, status, user_id, created_at
`

type CreateInvoiceParams struct {
	TenantID    string         `json:"tenant_id"`
	Number      string         `json:"number"`
	Date        pgtype.Date    `json:"date"`
	DueDate     pgtype.Date    `json:"due_date"`
	InvoiceType string         `json:"invoice_type"`
	Direction   string         `json:"direction"`
	EntityID    pgtype.UUID    `json:"entity_id"`
	CurrencyID  pgtype.UUID    `json:"currency_id"`
	Subtotal    pgtype.Numeric `json:"subtotal"`
	TaxAmount   pgtype.Numeric `json:"tax_amount"`
	Total       pgtype.Numeric `json:"total"`
	OrderID     pgtype.UUID    `json:"order_id"`
	UserID      string         `json:"user_id"`
}

type CreateInvoiceRow struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       string             `json:"tenant_id"`
	Number         string             `json:"number"`
	Date           pgtype.Date        `json:"date"`
	DueDate        pgtype.Date        `json:"due_date"`
	InvoiceType    string             `json:"invoice_type"`
	Direction      string             `json:"direction"`
	EntityID       pgtype.UUID        `json:"entity_id"`
	CurrencyID     pgtype.UUID        `json:"currency_id"`
	Subtotal       pgtype.Numeric     `json:"subtotal"`
	TaxAmount      pgtype.Numeric     `json:"tax_amount"`
	Total          pgtype.Numeric     `json:"total"`
	OrderID        pgtype.UUID        `json:"order_id"`
	JournalEntryID pgtype.UUID        `json:"journal_entry_id"`
	AfipCae        pgtype.Text        `json:"afip_cae"`
	AfipCaeDue     pgtype.Date        `json:"afip_cae_due"`
	Status         string             `json:"status"`
	UserID         string             `json:"user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (CreateInvoiceRow, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.TenantID,
		arg.Number,
		arg.Date,
		arg.DueDate,
		arg.InvoiceType,
		arg.Direction,
		arg.EntityID,
		arg.CurrencyID,
		arg.Subtotal,
		arg.TaxAmount,
		arg.Total,
		arg.OrderID,
		arg.UserID,
	)
	var i CreateInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Number,
		&i.Date,
		&i.DueDate,
		&i.InvoiceType,
		&i.Direction,
		&i.EntityID,
		&i.CurrencyID,
		&i.Subtotal,
		&i.TaxAmount,
		&i.Total,
		&i.OrderID,
		&i.JournalEntryID,
		&i.AfipCae,
		&i.AfipCaeDue,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const createInvoiceLine = `-- name: CreateInvoiceLine :one
INSERT INTO erp_invoice_lines (tenant_id, invoice_id, article_id, description,
    quantity, unit_price, tax_rate, tax_amount, line_total, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, invoice_id, article_id, description,
    quantity, unit_price, tax_rate, tax_amount, line_total, sort_order
`

type CreateInvoiceLineParams struct {
	TenantID    string         `json:"tenant_id"`
	InvoiceID   pgtype.UUID    `json:"invoice_id"`
	ArticleID   pgtype.UUID    `json:"article_id"`
	Description string         `json:"description"`
	Quantity    pgtype.Numeric `json:"quantity"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	TaxRate     pgtype.Numeric `json:"tax_rate"`
	TaxAmount   pgtype.Numeric `json:"tax_amount"`
	LineTotal   pgtype.Numeric `json:"line_total"`
	SortOrder   int32          `json:"sort_order"`
}

func (q *Queries) CreateInvoiceLine(ctx context.Context, arg CreateInvoiceLineParams) (ErpInvoiceLine, error) {
	row := q.db.QueryRow(ctx, createInvoiceLine,
		arg.TenantID,
		arg.InvoiceID,
		arg.ArticleID,
		arg.Description,
		arg.Quantity,
		arg.UnitPrice,
		arg.TaxRate,
		arg.TaxAmount,
		arg.LineTotal,
		arg.SortOrder,
	)
	var i ErpInvoiceLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvoiceID,
		&i.ArticleID,
		&i.Description,
		&i.Quantity,
		&i.UnitPrice,
		&i.TaxRate,
		&i.TaxAmount,
		&i.LineTotal,
		&i.SortOrder,
	)
	return i, err
}

const createTaxEntry = `-- name: CreateTaxEntry :one
INSERT INTO erp_tax_entries (tenant_id, invoice_id, period, direction, net_amount, tax_rate, tax_amount)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, invoice_id, period, direction, net_amount, tax_rate, tax_amount, created_at
`

type CreateTaxEntryParams struct {
	TenantID  string         `json:"tenant_id"`
	InvoiceID pgtype.UUID    `json:"invoice_id"`
	Period    string         `json:"period"`
	Direction string         `json:"direction"`
	NetAmount pgtype.Numeric `json:"net_amount"`
	TaxRate   pgtype.Numeric `json:"tax_rate"`
	TaxAmount pgtype.Numeric `json:"tax_amount"`
}

func (q *Queries) CreateTaxEntry(ctx context.Context, arg CreateTaxEntryParams) (ErpTaxEntry, error) {
	row := q.db.QueryRow(ctx, createTaxEntry,
		arg.TenantID,
		arg.InvoiceID,
		arg.Period,
		arg.Direction,
		arg.NetAmount,
		arg.TaxRate,
		arg.TaxAmount,
	)
	var i ErpTaxEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvoiceID,
		&i.Period,
		&i.Direction,
		&i.NetAmount,
		&i.TaxRate,
		&i.TaxAmount,
		&i.CreatedAt,
	)
	return i, err
}

const createWithholding = `-- name: CreateWithholding :one
INSERT INTO erp_withholdings (tenant_id, invoice_id, movement_id, entity_id, type, rate, base_amount, amount, certificate_num, date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, invoice_id, movement_id, entity_id, type, rate, base_amount, amount, certificate_num, date, created_at
`

type CreateWithholdingParams struct {
	TenantID       string         `json:"tenant_id"`
	InvoiceID      pgtype.UUID    `json:"invoice_id"`
	MovementID     pgtype.UUID    `json:"movement_id"`
	EntityID       pgtype.UUID    `json:"entity_id"`
	Type           string         `json:"type"`
	Rate           pgtype.Numeric `json:"rate"`
	BaseAmount     pgtype.Numeric `json:"base_amount"`
	Amount         pgtype.Numeric `json:"amount"`
	CertificateNum pgtype.Text    `json:"certificate_num"`
	Date           pgtype.Date    `json:"date"`
}

func (q *Queries) CreateWithholding(ctx context.Context, arg CreateWithholdingParams) (ErpWithholding, error) {
	row := q.db.QueryRow(ctx, createWithholding,
		arg.TenantID,
		arg.InvoiceID,
		arg.MovementID,
		arg.EntityID,
		arg.Type,
		arg.Rate,
		arg.BaseAmount,
		arg.Amount,
		arg.CertificateNum,
		arg.Date,
	)
	var i ErpWithholding
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvoiceID,
		&i.MovementID,
		&i.EntityID,
		&i.Type,
		&i.Rate,
		&i.BaseAmount,
		&i.Amount,
		&i.CertificateNum,
		&i.Date,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, tenant_id, number, date, due_date, invoice_type, direction,
       entity_id, currency_id, subtotal, tax_amount, total, order_id,
       journal_entry_id, afip_cae, afip_cae_due, status, user_id, created_at
FROM erp_invoices WHERE id = $1 AND tenant_id = $2
`

type GetInvoiceParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

type GetInvoiceRow struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       string             `json:"tenant_id"`
	Number         string             `json:"number"`
	Date           pgtype.Date        `json:"date"`
	DueDate        pgtype.Date        `json:"due_date"`
	InvoiceType    string             `json:"invoice_type"`
	Direction      string             `json:"direction"`
	EntityID       pgtype.UUID        `json:"entity_id"`
	CurrencyID     pgtype.UUID        `json:"currency_id"`
	Subtotal       pgtype.Numeric     `json:"subtotal"`
	TaxAmount      pgtype.Numeric     `json:"tax_amount"`
	Total          pgtype.Numeric     `json:"total"`
	OrderID        pgtype.UUID        `json:"order_id"`
	JournalEntryID pgtype.UUID        `json:"journal_entry_id"`
	AfipCae        pgtype.Text        `json:"afip_cae"`
	AfipCaeDue     pgtype.Date        `json:"afip_cae_due"`
	Status         string             `json:"status"`
	UserID         string             `json:"user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetInvoice(ctx context.Context, arg GetInvoiceParams) (GetInvoiceRow, error) {
	row := q.db.QueryRow(ctx, getInvoice, arg.ID, arg.TenantID)
	var i GetInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Number,
		&i.Date,
		&i.DueDate,
		&i.InvoiceType,
		&i.Direction,
		&i.EntityID,
		&i.CurrencyID,
		&i.Subtotal,
		&i.TaxAmount,
		&i.Total,
		&i.OrderID,
		&i.JournalEntryID,
		&i.AfipCae,
		&i.AfipCaeDue,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getTaxBook = `-- name: GetTaxBook :many
SELECT te.id, te.tenant_id, te.invoice_id, te.period, te.direction,
       te.net_amount, te.tax_rate, te.tax_amount, te.created_at,
       i.number AS invoice_number, e.name AS entity_name
FROM erp_tax_entries te
JOIN erp_invoices i ON i.id = te.invoice_id
JOIN erp_entities e ON e.id = i.entity_id
WHERE te.tenant_id = $1 AND te.period = $2
  AND ($3::TEXT = '' OR te.direction = $3::TEXT)
ORDER BY i.date, i.number
`

type GetTaxBookParams struct {
	TenantID        string `json:"tenant_id"`
	Period          string `json:"period"`
	DirectionFilter string `json:"direction_filter"`
}

type GetTaxBookRow struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      string             `json:"tenant_id"`
	InvoiceID     pgtype.UUID        `json:"invoice_id"`
	Period        string             `json:"period"`
	Direction     string             `json:"direction"`
	NetAmount     pgtype.Numeric     `json:"net_amount"`
	TaxRate       pgtype.Numeric     `json:"tax_rate"`
	TaxAmount     pgtype.Numeric     `json:"tax_amount"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	InvoiceNumber string             `json:"invoice_number"`
	EntityName    string             `json:"entity_name"`
}

func (q *Queries) GetTaxBook(ctx context.Context, arg GetTaxBookParams) ([]GetTaxBookRow, error) {
	rows, err := q.db.Query(ctx, getTaxBook, arg.TenantID, arg.Period, arg.DirectionFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTaxBookRow{}
	for rows.Next() {
		var i GetTaxBookRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InvoiceID,
			&i.Period,
			&i.Direction,
			&i.NetAmount,
			&i.TaxRate,
			&i.TaxAmount,
			&i.CreatedAt,
			&i.InvoiceNumber,
			&i.EntityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceLines = `-- name: ListInvoiceLines :many
SELECT il.id, il.tenant_id, il.invoice_id, il.article_id, il.description,
       il.quantity, il.unit_price, il.tax_rate, il.tax_amount, il.line_total, il.sort_order
FROM erp_invoice_lines il
WHERE il.invoice_id = $1 AND il.tenant_id = $2
ORDER BY il.sort_order
`

type ListInvoiceLinesParams struct {
	InvoiceID pgtype.UUID `json:"invoice_id"`
	TenantID  string      `json:"tenant_id"`
}

func (q *Queries) ListInvoiceLines(ctx context.Context, arg ListInvoiceLinesParams) ([]ErpInvoiceLine, error) {
	rows, err := q.db.Query(ctx, listInvoiceLines, arg.InvoiceID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpInvoiceLine{}
	for rows.Next() {
		var i ErpInvoiceLine
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InvoiceID,
			&i.ArticleID,
			&i.Description,
			&i.Quantity,
			&i.UnitPrice,
			&i.TaxRate,
			&i.TaxAmount,
			&i.LineTotal,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT i.id, i.tenant_id, i.number, i.date, i.due_date, i.invoice_type, i.direction,
       i.entity_id, i.currency_id, i.subtotal, i.tax_amount, i.total, i.order_id,
       i.afip_cae, i.status, i.user_id, i.created_at,
       e.name AS entity_name
FROM erp_invoices i
JOIN erp_entities e ON e.id = i.entity_id
WHERE i.tenant_id = $1
  AND ($4::TEXT = '' OR i.invoice_type = $4::TEXT)
  AND ($5::TEXT = '' OR i.direction = $5::TEXT)
  AND ($6::TEXT = '' OR i.status = $6::TEXT)
  AND ($7::DATE IS NULL OR i.date >= $7::DATE)
  AND ($8::DATE IS NULL OR i.date <= $8::DATE)
ORDER BY i.date DESC, i.number DESC
LIMIT $2 OFFSET $3
`

type ListInvoicesParams struct {
	TenantID        string      `json:"tenant_id"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
	TypeFilter      string      `json:"type_filter"`
	DirectionFilter string      `json:"direction_filter"`
	StatusFilter    string      `json:"status_filter"`
	DateFrom        pgtype.Date `json:"date_from"`
	DateTo          pgtype.Date `json:"date_to"`
}

type ListInvoicesRow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    string             `json:"tenant_id"`
	Number      string             `json:"number"`
	Date        pgtype.Date        `json:"date"`
	DueDate     pgtype.Date        `json:"due_date"`
	InvoiceType string             `json:"invoice_type"`
	Direction   string             `json:"direction"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	CurrencyID  pgtype.UUID        `json:"currency_id"`
	Subtotal    pgtype.Numeric     `json:"subtotal"`
	TaxAmount   pgtype.Numeric     `json:"tax_amount"`
	Total       pgtype.Numeric     `json:"total"`
	OrderID     pgtype.UUID        `json:"order_id"`
	AfipCae     pgtype.Text        `json:"afip_cae"`
	Status      string             `json:"status"`
	UserID      string             `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	EntityName  string             `json:"entity_name"`
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]ListInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listInvoices,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.TypeFilter,
		arg.DirectionFilter,
		arg.StatusFilter,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoicesRow{}
	for rows.Next() {
		var i ListInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Number,
			&i.Date,
			&i.DueDate,
			&i.InvoiceType,
			&i.Direction,
			&i.EntityID,
			&i.CurrencyID,
			&i.Subtotal,
			&i.TaxAmount,
			&i.Total,
			&i.OrderID,
			&i.AfipCae,
			&i.Status,
			&i.UserID,
			&i.CreatedAt,
			&i.EntityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxEntriesByInvoice = `-- name: ListTaxEntriesByInvoice :many

SELECT id, tenant_id, invoice_id, period, direction, net_amount, tax_rate, tax_amount
FROM erp_tax_entries WHERE tenant_id = $1 AND invoice_id = $2
`

type ListTaxEntriesByInvoiceParams struct {
	TenantID  string      `json:"tenant_id"`
	InvoiceID pgtype.UUID `json:"invoice_id"`
}

type ListTaxEntriesByInvoiceRow struct {
	ID        pgtype.UUID    `json:"id"`
	TenantID  string         `json:"tenant_id"`
	InvoiceID pgtype.UUID    `json:"invoice_id"`
	Period    string         `json:"period"`
	Direction string         `json:"direction"`
	NetAmount pgtype.Numeric `json:"net_amount"`
	TaxRate   pgtype.Numeric `json:"tax_rate"`
	TaxAmount pgtype.Numeric `json:"tax_amount"`
}

// ============================================================
// Cascade void queries (Plan 18 Fase 2)
// ============================================================
func (q *Queries) ListTaxEntriesByInvoice(ctx context.Context, arg ListTaxEntriesByInvoiceParams) ([]ListTaxEntriesByInvoiceRow, error) {
	rows, err := q.db.Query(ctx, listTaxEntriesByInvoice, arg.TenantID, arg.InvoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaxEntriesByInvoiceRow{}
	for rows.Next() {
		var i ListTaxEntriesByInvoiceRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InvoiceID,
			&i.Period,
			&i.Direction,
			&i.NetAmount,
			&i.TaxRate,
			&i.TaxAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithholdings = `-- name: ListWithholdings :many
SELECT w.id, w.tenant_id, w.invoice_id, w.movement_id, w.entity_id, w.type,
       w.rate, w.base_amount, w.amount, w.certificate_num, w.date, w.created_at,
       e.name AS entity_name
FROM erp_withholdings w
JOIN erp_entities e ON e.id = w.entity_id
WHERE w.tenant_id = $1
  AND ($4::TEXT = '' OR w.type = $4::TEXT)
ORDER BY w.date DESC
LIMIT $2 OFFSET $3
`

type ListWithholdingsParams struct {
	TenantID   string `json:"tenant_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
	TypeFilter string `json:"type_filter"`
}

type ListWithholdingsRow struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       string             `json:"tenant_id"`
	InvoiceID      pgtype.UUID        `json:"invoice_id"`
	MovementID     pgtype.UUID        `json:"movement_id"`
	EntityID       pgtype.UUID        `json:"entity_id"`
	Type           string             `json:"type"`
	Rate           pgtype.Numeric     `json:"rate"`
	BaseAmount     pgtype.Numeric     `json:"base_amount"`
	Amount         pgtype.Numeric     `json:"amount"`
	CertificateNum pgtype.Text        `json:"certificate_num"`
	Date           pgtype.Date        `json:"date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	EntityName     string             `json:"entity_name"`
}

func (q *Queries) ListWithholdings(ctx context.Context, arg ListWithholdingsParams) ([]ListWithholdingsRow, error) {
	rows, err := q.db.Query(ctx, listWithholdings,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.TypeFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWithholdingsRow{}
	for rows.Next() {
		var i ListWithholdingsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InvoiceID,
			&i.MovementID,
			&i.EntityID,
			&i.Type,
			&i.Rate,
			&i.BaseAmount,
			&i.Amount,
			&i.CertificateNum,
			&i.Date,
			&i.CreatedAt,
			&i.EntityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postInvoice = `-- name: PostInvoice :execrows
UPDATE erp_invoices SET status = 'posted'
WHERE id = $1 AND tenant_id = $2 AND status = 'draft'
`

type PostInvoiceParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) PostInvoice(ctx context.Context, arg PostInvoiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, postInvoice, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const voidInvoice = `-- name: VoidInvoice :execrows
UPDATE erp_invoices SET status = 'cancelled', voided_by = $3, void_reason = $4
WHERE id = $1 AND tenant_id = $2 AND status IN ('posted', 'paid')
`

type VoidInvoiceParams struct {
	ID         pgtype.UUID `json:"id"`
	TenantID   string      `json:"tenant_id"`
	VoidedBy   pgtype.UUID `json:"voided_by"`
	VoidReason pgtype.Text `json:"void_reason"`
}

func (q *Queries) VoidInvoice(ctx context.Context, arg VoidInvoiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, voidInvoice,
		arg.ID,
		arg.TenantID,
		arg.VoidedBy,
		arg.VoidReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
