// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: manufacturing.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addBOMItem = `-- name: AddBOMItem :one
INSERT INTO erp_carroceria_bom (tenant_id, carroceria_model_id, article_id, quantity, unit_of_use)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, carroceria_model_id, article_id, quantity, unit_of_use,
          created_at, updated_at
`

type AddBOMItemParams struct {
	TenantID          string         `json:"tenant_id"`
	CarroceriaModelID pgtype.UUID    `json:"carroceria_model_id"`
	ArticleID         pgtype.UUID    `json:"article_id"`
	Quantity          pgtype.Numeric `json:"quantity"`
	UnitOfUse         string         `json:"unit_of_use"`
}

func (q *Queries) AddBOMItem(ctx context.Context, arg AddBOMItemParams) (ErpCarroceriaBom, error) {
	row := q.db.QueryRow(ctx, addBOMItem,
		arg.TenantID,
		arg.CarroceriaModelID,
		arg.ArticleID,
		arg.Quantity,
		arg.UnitOfUse,
	)
	var i ErpCarroceriaBom
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CarroceriaModelID,
		&i.ArticleID,
		&i.Quantity,
		&i.UnitOfUse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addLCMModel = `-- name: AddLCMModel :one
INSERT INTO erp_manufacturing_lcm_models (
    tenant_id, lcm_id, article_id, bom_qty, issued_qty, returned_qty, unit_cost, notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, lcm_id, article_id, bom_qty, issued_qty, returned_qty,
          unit_cost, notes, created_at, updated_at
`

type AddLCMModelParams struct {
	TenantID    string         `json:"tenant_id"`
	LcmID       pgtype.UUID    `json:"lcm_id"`
	ArticleID   pgtype.UUID    `json:"article_id"`
	BomQty      pgtype.Numeric `json:"bom_qty"`
	IssuedQty   pgtype.Numeric `json:"issued_qty"`
	ReturnedQty pgtype.Numeric `json:"returned_qty"`
	UnitCost    pgtype.Numeric `json:"unit_cost"`
	Notes       string         `json:"notes"`
}

func (q *Queries) AddLCMModel(ctx context.Context, arg AddLCMModelParams) (ErpManufacturingLcmModel, error) {
	row := q.db.QueryRow(ctx, addLCMModel,
		arg.TenantID,
		arg.LcmID,
		arg.ArticleID,
		arg.BomQty,
		arg.IssuedQty,
		arg.ReturnedQty,
		arg.UnitCost,
		arg.Notes,
	)
	var i ErpManufacturingLcmModel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LcmID,
		&i.ArticleID,
		&i.BomQty,
		&i.IssuedQty,
		&i.ReturnedQty,
		&i.UnitCost,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const approveRework = `-- name: ApproveRework :execrows
UPDATE erp_production_rework
SET corrected_by = $3, correction = $4, resolved_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type ApproveReworkParams struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    string      `json:"tenant_id"`
	CorrectedBy pgtype.UUID `json:"corrected_by"`
	Correction  string      `json:"correction"`
}

func (q *Queries) ApproveRework(ctx context.Context, arg ApproveReworkParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveRework,
		arg.ID,
		arg.TenantID,
		arg.CorrectedBy,
		arg.Correction,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCNRTWork = `-- name: CreateCNRTWork :one
INSERT INTO erp_cnrt_work_orders (
    tenant_id, unit_id, cnrt_number, inspection_type, inspector_name,
    inspection_date, observations
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, unit_id, cnrt_number, inspection_type, inspector_name,
          inspection_date, approved, approval_date, expiry_date, observations,
          rejection_reasons, status, document_url, created_at, updated_at
`

type CreateCNRTWorkParams struct {
	TenantID       string      `json:"tenant_id"`
	UnitID         pgtype.UUID `json:"unit_id"`
	CnrtNumber     string      `json:"cnrt_number"`
	InspectionType string      `json:"inspection_type"`
	InspectorName  string      `json:"inspector_name"`
	InspectionDate pgtype.Date `json:"inspection_date"`
	Observations   string      `json:"observations"`
}

func (q *Queries) CreateCNRTWork(ctx context.Context, arg CreateCNRTWorkParams) (ErpCnrtWorkOrder, error) {
	row := q.db.QueryRow(ctx, createCNRTWork,
		arg.TenantID,
		arg.UnitID,
		arg.CnrtNumber,
		arg.InspectionType,
		arg.InspectorName,
		arg.InspectionDate,
		arg.Observations,
	)
	var i ErpCnrtWorkOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnitID,
		&i.CnrtNumber,
		&i.InspectionType,
		&i.InspectorName,
		&i.InspectionDate,
		&i.Approved,
		&i.ApprovalDate,
		&i.ExpiryDate,
		&i.Observations,
		&i.RejectionReasons,
		&i.Status,
		&i.DocumentUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCarroceriaModel = `-- name: CreateCarroceriaModel :one
INSERT INTO erp_carroceria_models (
    tenant_id, code, model_code, description, abbreviation, double_deck,
    axle_weight_pct, productive_hours_per_station, tech_sheet_image
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, code, model_code, description, abbreviation, double_deck,
          axle_weight_pct, productive_hours_per_station, active, tech_sheet_image,
          created_at, updated_at
`

type CreateCarroceriaModelParams struct {
	TenantID                  string          `json:"tenant_id"`
	Code                      string          `json:"code"`
	ModelCode                 string          `json:"model_code"`
	Description               string          `json:"description"`
	Abbreviation              string          `json:"abbreviation"`
	DoubleDeck                bool            `json:"double_deck"`
	AxleWeightPct             pgtype.Numeric  `json:"axle_weight_pct"`
	ProductiveHoursPerStation pgtype.Interval `json:"productive_hours_per_station"`
	TechSheetImage            string          `json:"tech_sheet_image"`
}

func (q *Queries) CreateCarroceriaModel(ctx context.Context, arg CreateCarroceriaModelParams) (ErpCarroceriaModel, error) {
	row := q.db.QueryRow(ctx, createCarroceriaModel,
		arg.TenantID,
		arg.Code,
		arg.ModelCode,
		arg.Description,
		arg.Abbreviation,
		arg.DoubleDeck,
		arg.AxleWeightPct,
		arg.ProductiveHoursPerStation,
		arg.TechSheetImage,
	)
	var i ErpCarroceriaModel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.ModelCode,
		&i.Description,
		&i.Abbreviation,
		&i.DoubleDeck,
		&i.AxleWeightPct,
		&i.ProductiveHoursPerStation,
		&i.Active,
		&i.TechSheetImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCertificate = `-- name: CreateCertificate :one
INSERT INTO erp_manufacturing_certificates (
    tenant_id, unit_id, certificate_number, cert_type, issued_by,
    valid_from, valid_until, authority, document_url, observations
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, unit_id, certificate_number, cert_type, issued_by,
          issued_at, valid_from, valid_until, authority, document_url,
          observations, status, revoked_at, revocation_reason, created_at, updated_at
`

type CreateCertificateParams struct {
	TenantID          string      `json:"tenant_id"`
	UnitID            pgtype.UUID `json:"unit_id"`
	CertificateNumber string      `json:"certificate_number"`
	CertType          string      `json:"cert_type"`
	IssuedBy          pgtype.UUID `json:"issued_by"`
	ValidFrom         pgtype.Date `json:"valid_from"`
	ValidUntil        pgtype.Date `json:"valid_until"`
	Authority         string      `json:"authority"`
	DocumentUrl       string      `json:"document_url"`
	Observations      string      `json:"observations"`
}

func (q *Queries) CreateCertificate(ctx context.Context, arg CreateCertificateParams) (ErpManufacturingCertificate, error) {
	row := q.db.QueryRow(ctx, createCertificate,
		arg.TenantID,
		arg.UnitID,
		arg.CertificateNumber,
		arg.CertType,
		arg.IssuedBy,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.Authority,
		arg.DocumentUrl,
		arg.Observations,
	)
	var i ErpManufacturingCertificate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnitID,
		&i.CertificateNumber,
		&i.CertType,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Authority,
		&i.DocumentUrl,
		&i.Observations,
		&i.Status,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createChassisBrand = `-- name: CreateChassisBrand :one
INSERT INTO erp_chassis_brands (tenant_id, code, name)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, code, name, active, created_at, updated_at
`

type CreateChassisBrandParams struct {
	TenantID string `json:"tenant_id"`
	Code     string `json:"code"`
	Name     string `json:"name"`
}

func (q *Queries) CreateChassisBrand(ctx context.Context, arg CreateChassisBrandParams) (ErpChassisBrand, error) {
	row := q.db.QueryRow(ctx, createChassisBrand, arg.TenantID, arg.Code, arg.Name)
	var i ErpChassisBrand
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLCM = `-- name: CreateLCM :one
INSERT INTO erp_manufacturing_lcm (
    tenant_id, unit_id, issued_by, warehouse_id, reference, notes
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, unit_id, issued_at, issued_by, warehouse_id,
          reference, status, notes, created_at, updated_at
`

type CreateLCMParams struct {
	TenantID    string      `json:"tenant_id"`
	UnitID      pgtype.UUID `json:"unit_id"`
	IssuedBy    pgtype.UUID `json:"issued_by"`
	WarehouseID pgtype.UUID `json:"warehouse_id"`
	Reference   string      `json:"reference"`
	Notes       string      `json:"notes"`
}

func (q *Queries) CreateLCM(ctx context.Context, arg CreateLCMParams) (ErpManufacturingLcm, error) {
	row := q.db.QueryRow(ctx, createLCM,
		arg.TenantID,
		arg.UnitID,
		arg.IssuedBy,
		arg.WarehouseID,
		arg.Reference,
		arg.Notes,
	)
	var i ErpManufacturingLcm
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnitID,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.WarehouseID,
		&i.Reference,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createManufacturingUnit = `-- name: CreateManufacturingUnit :one
INSERT INTO erp_manufacturing_units (
    tenant_id, work_order_number, chassis_serial, engine_number,
    chassis_brand_id, chassis_model_id, carroceria_model_id, customer_id,
    entry_date, expected_completion, tachograph_id, tachograph_serial,
    invoice_reference, observations
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, tenant_id, work_order_number, chassis_serial, engine_number,
          chassis_brand_id, chassis_model_id, carroceria_model_id, customer_id,
          entry_date, expected_completion, actual_completion, exit_date,
          tachograph_id, tachograph_serial, invoice_reference, observations,
          status, created_at, updated_at
`

type CreateManufacturingUnitParams struct {
	TenantID           string      `json:"tenant_id"`
	WorkOrderNumber    int32       `json:"work_order_number"`
	ChassisSerial      string      `json:"chassis_serial"`
	EngineNumber       string      `json:"engine_number"`
	ChassisBrandID     pgtype.UUID `json:"chassis_brand_id"`
	ChassisModelID     pgtype.UUID `json:"chassis_model_id"`
	CarroceriaModelID  pgtype.UUID `json:"carroceria_model_id"`
	CustomerID         pgtype.UUID `json:"customer_id"`
	EntryDate          pgtype.Date `json:"entry_date"`
	ExpectedCompletion pgtype.Date `json:"expected_completion"`
	TachographID       pgtype.Int4 `json:"tachograph_id"`
	TachographSerial   string      `json:"tachograph_serial"`
	InvoiceReference   pgtype.Text `json:"invoice_reference"`
	Observations       string      `json:"observations"`
}

func (q *Queries) CreateManufacturingUnit(ctx context.Context, arg CreateManufacturingUnitParams) (ErpManufacturingUnit, error) {
	row := q.db.QueryRow(ctx, createManufacturingUnit,
		arg.TenantID,
		arg.WorkOrderNumber,
		arg.ChassisSerial,
		arg.EngineNumber,
		arg.ChassisBrandID,
		arg.ChassisModelID,
		arg.CarroceriaModelID,
		arg.CustomerID,
		arg.EntryDate,
		arg.ExpectedCompletion,
		arg.TachographID,
		arg.TachographSerial,
		arg.InvoiceReference,
		arg.Observations,
	)
	var i ErpManufacturingUnit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkOrderNumber,
		&i.ChassisSerial,
		&i.EngineNumber,
		&i.ChassisBrandID,
		&i.ChassisModelID,
		&i.CarroceriaModelID,
		&i.CustomerID,
		&i.EntryDate,
		&i.ExpectedCompletion,
		&i.ActualCompletion,
		&i.ExitDate,
		&i.TachographID,
		&i.TachographSerial,
		&i.InvoiceReference,
		&i.Observations,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProductionControl = `-- name: CreateProductionControl :one
INSERT INTO erp_production_controls (
    tenant_id, unit_id, station, station_seq, responsible_id,
    planned_start, planned_end, notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, unit_id, station, station_seq, responsible_id,
          planned_start, planned_end, actual_start, actual_end, status, notes,
          created_at, updated_at
`

type CreateProductionControlParams struct {
	TenantID      string      `json:"tenant_id"`
	UnitID        pgtype.UUID `json:"unit_id"`
	Station       string      `json:"station"`
	StationSeq    int32       `json:"station_seq"`
	ResponsibleID pgtype.UUID `json:"responsible_id"`
	PlannedStart  pgtype.Date `json:"planned_start"`
	PlannedEnd    pgtype.Date `json:"planned_end"`
	Notes         string      `json:"notes"`
}

func (q *Queries) CreateProductionControl(ctx context.Context, arg CreateProductionControlParams) (ErpProductionControl, error) {
	row := q.db.QueryRow(ctx, createProductionControl,
		arg.TenantID,
		arg.UnitID,
		arg.Station,
		arg.StationSeq,
		arg.ResponsibleID,
		arg.PlannedStart,
		arg.PlannedEnd,
		arg.Notes,
	)
	var i ErpProductionControl
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnitID,
		&i.Station,
		&i.StationSeq,
		&i.ResponsibleID,
		&i.PlannedStart,
		&i.PlannedEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRework = `-- name: CreateRework :one

INSERT INTO erp_production_rework (
    tenant_id, control_id, causal_id, reported_by, defect_desc, severity
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, control_id, causal_id, reported_by, corrected_by,
          defect_desc, correction, severity, reported_at, resolved_at,
          created_at, updated_at
`

type CreateReworkParams struct {
	TenantID   string      `json:"tenant_id"`
	ControlID  pgtype.UUID `json:"control_id"`
	CausalID   pgtype.UUID `json:"causal_id"`
	ReportedBy pgtype.UUID `json:"reported_by"`
	DefectDesc string      `json:"defect_desc"`
	Severity   string      `json:"severity"`
}

// ─── Production Rework ─────────────────────────────────────────────────────────
func (q *Queries) CreateRework(ctx context.Context, arg CreateReworkParams) (ErpProductionRework, error) {
	row := q.db.QueryRow(ctx, createRework,
		arg.TenantID,
		arg.ControlID,
		arg.CausalID,
		arg.ReportedBy,
		arg.DefectDesc,
		arg.Severity,
	)
	var i ErpProductionRework
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ControlID,
		&i.CausalID,
		&i.ReportedBy,
		&i.CorrectedBy,
		&i.DefectDesc,
		&i.Correction,
		&i.Severity,
		&i.ReportedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBOMItem = `-- name: DeleteBOMItem :execrows
DELETE FROM erp_carroceria_bom WHERE id = $1 AND tenant_id = $2
`

type DeleteBOMItemParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) DeleteBOMItem(ctx context.Context, arg DeleteBOMItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBOMItem, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const executeControl = `-- name: ExecuteControl :one
INSERT INTO erp_production_control_executions (
    tenant_id, control_id, operator_id, causal_id, started_at, exec_type, notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, control_id, operator_id, causal_id, started_at,
          ended_at, duration, exec_type, notes, created_at
`

type ExecuteControlParams struct {
	TenantID   string             `json:"tenant_id"`
	ControlID  pgtype.UUID        `json:"control_id"`
	OperatorID pgtype.UUID        `json:"operator_id"`
	CausalID   pgtype.UUID        `json:"causal_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	ExecType   string             `json:"exec_type"`
	Notes      string             `json:"notes"`
}

func (q *Queries) ExecuteControl(ctx context.Context, arg ExecuteControlParams) (ErpProductionControlExecution, error) {
	row := q.db.QueryRow(ctx, executeControl,
		arg.TenantID,
		arg.ControlID,
		arg.OperatorID,
		arg.CausalID,
		arg.StartedAt,
		arg.ExecType,
		arg.Notes,
	)
	var i ErpProductionControlExecution
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ControlID,
		&i.OperatorID,
		&i.CausalID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Duration,
		&i.ExecType,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getCarroceriaBOM = `-- name: GetCarroceriaBOM :many

SELECT bom.id, bom.tenant_id, bom.carroceria_model_id, bom.article_id,
       bom.quantity, bom.unit_of_use, bom.created_at, bom.updated_at,
       a.code AS article_code, a.name AS article_name
FROM erp_carroceria_bom bom
JOIN erp_articles a ON a.id = bom.article_id AND a.tenant_id = bom.tenant_id
WHERE bom.carroceria_model_id = $1 AND bom.tenant_id = $2
ORDER BY a.code
`

type GetCarroceriaBOMParams struct {
	CarroceriaModelID pgtype.UUID `json:"carroceria_model_id"`
	TenantID          string      `json:"tenant_id"`
}

type GetCarroceriaBOMRow struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          string             `json:"tenant_id"`
	CarroceriaModelID pgtype.UUID        `json:"carroceria_model_id"`
	ArticleID         pgtype.UUID        `json:"article_id"`
	Quantity          pgtype.Numeric     `json:"quantity"`
	UnitOfUse         string             `json:"unit_of_use"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ArticleCode       string             `json:"article_code"`
	ArticleName       string             `json:"article_name"`
}

// ─── Carroceria BOM ────────────────────────────────────────────────────────────
func (q *Queries) GetCarroceriaBOM(ctx context.Context, arg GetCarroceriaBOMParams) ([]GetCarroceriaBOMRow, error) {
	rows, err := q.db.Query(ctx, getCarroceriaBOM, arg.CarroceriaModelID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCarroceriaBOMRow{}
	for rows.Next() {
		var i GetCarroceriaBOMRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CarroceriaModelID,
			&i.ArticleID,
			&i.Quantity,
			&i.UnitOfUse,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArticleCode,
			&i.ArticleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCarroceriaModel = `-- name: GetCarroceriaModel :one
SELECT id, tenant_id, code, model_code, description, abbreviation, double_deck,
       axle_weight_pct, productive_hours_per_station, active, tech_sheet_image,
       created_at, updated_at
FROM erp_carroceria_models
WHERE id = $1 AND tenant_id = $2
`

type GetCarroceriaModelParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) GetCarroceriaModel(ctx context.Context, arg GetCarroceriaModelParams) (ErpCarroceriaModel, error) {
	row := q.db.QueryRow(ctx, getCarroceriaModel, arg.ID, arg.TenantID)
	var i ErpCarroceriaModel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.ModelCode,
		&i.Description,
		&i.Abbreviation,
		&i.DoubleDeck,
		&i.AxleWeightPct,
		&i.ProductiveHoursPerStation,
		&i.Active,
		&i.TechSheetImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCertificate = `-- name: GetCertificate :one

SELECT id, tenant_id, unit_id, certificate_number, cert_type, issued_by,
       issued_at, valid_from, valid_until, authority, document_url,
       observations, status, revoked_at, revocation_reason, created_at, updated_at
FROM erp_manufacturing_certificates
WHERE tenant_id = $1 AND unit_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetCertificateParams struct {
	TenantID string      `json:"tenant_id"`
	UnitID   pgtype.UUID `json:"unit_id"`
}

// ─── Manufacturing Certificates ───────────────────────────────────────────────
func (q *Queries) GetCertificate(ctx context.Context, arg GetCertificateParams) (ErpManufacturingCertificate, error) {
	row := q.db.QueryRow(ctx, getCertificate, arg.TenantID, arg.UnitID)
	var i ErpManufacturingCertificate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnitID,
		&i.CertificateNumber,
		&i.CertType,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Authority,
		&i.DocumentUrl,
		&i.Observations,
		&i.Status,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getControlExecution = `-- name: GetControlExecution :one
SELECT id, tenant_id, control_id, operator_id, causal_id, started_at,
       ended_at, duration, exec_type, notes, created_at
FROM erp_production_control_executions
WHERE id = $1 AND tenant_id = $2
`

type GetControlExecutionParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) GetControlExecution(ctx context.Context, arg GetControlExecutionParams) (ErpProductionControlExecution, error) {
	row := q.db.QueryRow(ctx, getControlExecution, arg.ID, arg.TenantID)
	var i ErpProductionControlExecution
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ControlID,
		&i.OperatorID,
		&i.CausalID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Duration,
		&i.ExecType,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getLCM = `-- name: GetLCM :one
SELECT id, tenant_id, unit_id, issued_at, issued_by, warehouse_id,
       reference, status, notes, created_at, updated_at
FROM erp_manufacturing_lcm
WHERE id = $1 AND tenant_id = $2
`

type GetLCMParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) GetLCM(ctx context.Context, arg GetLCMParams) (ErpManufacturingLcm, error) {
	row := q.db.QueryRow(ctx, getLCM, arg.ID, arg.TenantID)
	var i ErpManufacturingLcm
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnitID,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.WarehouseID,
		&i.Reference,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManufacturingKPIs = `-- name: GetManufacturingKPIs :one

SELECT
    COUNT(*) AS total_units,
    COUNT(*) FILTER (WHERE status = 'pending') AS pending,
    COUNT(*) FILTER (WHERE status = 'in_production') AS in_production,
    COUNT(*) FILTER (WHERE status = 'completed') AS completed,
    COUNT(*) FILTER (WHERE status = 'delivered') AS delivered,
    COUNT(*) FILTER (WHERE status = 'returned') AS returned,
    COUNT(*) FILTER (WHERE expected_completion < CURRENT_DATE AND actual_completion IS NULL) AS overdue
FROM erp_manufacturing_units
WHERE tenant_id = $1
`

type GetManufacturingKPIsRow struct {
	TotalUnits   int64 `json:"total_units"`
	Pending      int64 `json:"pending"`
	InProduction int64 `json:"in_production"`
	Completed    int64 `json:"completed"`
	Delivered    int64 `json:"delivered"`
	Returned     int64 `json:"returned"`
	Overdue      int64 `json:"overdue"`
}

// ─── Analytics ─────────────────────────────────────────────────────────────────
func (q *Queries) GetManufacturingKPIs(ctx context.Context, tenantID string) (GetManufacturingKPIsRow, error) {
	row := q.db.QueryRow(ctx, getManufacturingKPIs, tenantID)
	var i GetManufacturingKPIsRow
	err := row.Scan(
		&i.TotalUnits,
		&i.Pending,
		&i.InProduction,
		&i.Completed,
		&i.Delivered,
		&i.Returned,
		&i.Overdue,
	)
	return i, err
}

const getManufacturingUnit = `-- name: GetManufacturingUnit :one
SELECT mu.id, mu.tenant_id, mu.work_order_number, mu.chassis_serial, mu.engine_number,
       mu.chassis_brand_id, mu.chassis_model_id, mu.carroceria_model_id,
       mu.customer_id, mu.entry_date, mu.expected_completion, mu.actual_completion,
       mu.exit_date, mu.tachograph_id, mu.tachograph_serial, mu.invoice_reference,
       mu.observations, mu.status, mu.created_at, mu.updated_at,
       cb.name AS chassis_brand_name,
       cm.description AS chassis_model_description,
       crm.description AS carroceria_model_description,
       e.name AS customer_name
FROM erp_manufacturing_units mu
LEFT JOIN erp_chassis_brands cb ON cb.id = mu.chassis_brand_id AND cb.tenant_id = mu.tenant_id
LEFT JOIN erp_chassis_models cm ON cm.id = mu.chassis_model_id AND cm.tenant_id = mu.tenant_id
LEFT JOIN erp_carroceria_models crm ON crm.id = mu.carroceria_model_id AND crm.tenant_id = mu.tenant_id
LEFT JOIN erp_entities e ON e.id = mu.customer_id AND e.tenant_id = mu.tenant_id
WHERE mu.id = $1 AND mu.tenant_id = $2
`

type GetManufacturingUnitParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

type GetManufacturingUnitRow struct {
	ID                         pgtype.UUID        `json:"id"`
	TenantID                   string             `json:"tenant_id"`
	WorkOrderNumber            int32              `json:"work_order_number"`
	ChassisSerial              string             `json:"chassis_serial"`
	EngineNumber               string             `json:"engine_number"`
	ChassisBrandID             pgtype.UUID        `json:"chassis_brand_id"`
	ChassisModelID             pgtype.UUID        `json:"chassis_model_id"`
	CarroceriaModelID          pgtype.UUID        `json:"carroceria_model_id"`
	CustomerID                 pgtype.UUID        `json:"customer_id"`
	EntryDate                  pgtype.Date        `json:"entry_date"`
	ExpectedCompletion         pgtype.Date        `json:"expected_completion"`
	ActualCompletion           pgtype.Date        `json:"actual_completion"`
	ExitDate                   pgtype.Date        `json:"exit_date"`
	TachographID               pgtype.Int4        `json:"tachograph_id"`
	TachographSerial           string             `json:"tachograph_serial"`
	InvoiceReference           pgtype.Text        `json:"invoice_reference"`
	Observations               string             `json:"observations"`
	Status                     string             `json:"status"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	ChassisBrandName           pgtype.Text        `json:"chassis_brand_name"`
	ChassisModelDescription    pgtype.Text        `json:"chassis_model_description"`
	CarroceriaModelDescription pgtype.Text        `json:"carroceria_model_description"`
	CustomerName               pgtype.Text        `json:"customer_name"`
}

func (q *Queries) GetManufacturingUnit(ctx context.Context, arg GetManufacturingUnitParams) (GetManufacturingUnitRow, error) {
	row := q.db.QueryRow(ctx, getManufacturingUnit, arg.ID, arg.TenantID)
	var i GetManufacturingUnitRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkOrderNumber,
		&i.ChassisSerial,
		&i.EngineNumber,
		&i.ChassisBrandID,
		&i.ChassisModelID,
		&i.CarroceriaModelID,
		&i.CustomerID,
		&i.EntryDate,
		&i.ExpectedCompletion,
		&i.ActualCompletion,
		&i.ExitDate,
		&i.TachographID,
		&i.TachographSerial,
		&i.InvoiceReference,
		&i.Observations,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChassisBrandName,
		&i.ChassisModelDescription,
		&i.CarroceriaModelDescription,
		&i.CustomerName,
	)
	return i, err
}

const getProductionControl = `-- name: GetProductionControl :one
SELECT id, tenant_id, unit_id, station, station_seq, responsible_id,
       planned_start, planned_end, actual_start, actual_end, status, notes,
       created_at, updated_at
FROM erp_production_controls
WHERE id = $1 AND tenant_id = $2
`

type GetProductionControlParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) GetProductionControl(ctx context.Context, arg GetProductionControlParams) (ErpProductionControl, error) {
	row := q.db.QueryRow(ctx, getProductionControl, arg.ID, arg.TenantID)
	var i ErpProductionControl
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnitID,
		&i.Station,
		&i.StationSeq,
		&i.ResponsibleID,
		&i.PlannedStart,
		&i.PlannedEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnitControlExecutions = `-- name: GetUnitControlExecutions :many

SELECT pce.id, pce.tenant_id, pce.control_id, pce.operator_id, pce.causal_id,
       pce.started_at, pce.ended_at, pce.duration, pce.exec_type, pce.notes,
       pce.created_at,
       pc.station AS station_name,
       caus.code AS causal_code, caus.description AS causal_description,
       e.name AS operator_name
FROM erp_production_control_executions pce
JOIN erp_production_controls pc ON pc.id = pce.control_id AND pc.tenant_id = pce.tenant_id
LEFT JOIN erp_production_control_causals caus ON caus.id = pce.causal_id AND caus.tenant_id = pce.tenant_id
LEFT JOIN erp_entities e ON e.id = pce.operator_id AND e.tenant_id = pce.tenant_id
WHERE pc.unit_id = $1 AND pce.tenant_id = $2
ORDER BY pce.started_at DESC
`

type GetUnitControlExecutionsParams struct {
	UnitID   pgtype.UUID `json:"unit_id"`
	TenantID string      `json:"tenant_id"`
}

type GetUnitControlExecutionsRow struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          string             `json:"tenant_id"`
	ControlID         pgtype.UUID        `json:"control_id"`
	OperatorID        pgtype.UUID        `json:"operator_id"`
	CausalID          pgtype.UUID        `json:"causal_id"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	EndedAt           pgtype.Timestamptz `json:"ended_at"`
	Duration          pgtype.Interval    `json:"duration"`
	ExecType          string             `json:"exec_type"`
	Notes             string             `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	StationName       string             `json:"station_name"`
	CausalCode        pgtype.Text        `json:"causal_code"`
	CausalDescription pgtype.Text        `json:"causal_description"`
	OperatorName      pgtype.Text        `json:"operator_name"`
}

// ─── Control Executions (time entries per station) ────────────────────────────
func (q *Queries) GetUnitControlExecutions(ctx context.Context, arg GetUnitControlExecutionsParams) ([]GetUnitControlExecutionsRow, error) {
	rows, err := q.db.Query(ctx, getUnitControlExecutions, arg.UnitID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnitControlExecutionsRow{}
	for rows.Next() {
		var i GetUnitControlExecutionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ControlID,
			&i.OperatorID,
			&i.CausalID,
			&i.StartedAt,
			&i.EndedAt,
			&i.Duration,
			&i.ExecType,
			&i.Notes,
			&i.CreatedAt,
			&i.StationName,
			&i.CausalCode,
			&i.CausalDescription,
			&i.OperatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnitPendingControls = `-- name: GetUnitPendingControls :many
SELECT pc.id, pc.tenant_id, pc.unit_id, pc.station, pc.station_seq,
       pc.responsible_id, pc.planned_start, pc.planned_end, pc.actual_start,
       pc.actual_end, pc.status, pc.notes, pc.created_at, pc.updated_at
FROM erp_production_controls pc
WHERE pc.tenant_id = $1
  AND pc.unit_id = $2::UUID
  AND pc.status IN ('pending', 'in_progress', 'blocked', 'rework')
ORDER BY pc.station_seq
`

type GetUnitPendingControlsParams struct {
	TenantID string      `json:"tenant_id"`
	UnitID   pgtype.UUID `json:"unit_id"`
}

func (q *Queries) GetUnitPendingControls(ctx context.Context, arg GetUnitPendingControlsParams) ([]ErpProductionControl, error) {
	rows, err := q.db.Query(ctx, getUnitPendingControls, arg.TenantID, arg.UnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpProductionControl{}
	for rows.Next() {
		var i ErpProductionControl
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UnitID,
			&i.Station,
			&i.StationSeq,
			&i.ResponsibleID,
			&i.PlannedStart,
			&i.PlannedEnd,
			&i.ActualStart,
			&i.ActualEnd,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const issueCertificate = `-- name: IssueCertificate :execrows
UPDATE erp_manufacturing_certificates
SET status = 'issued', issued_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type IssueCertificateParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) IssueCertificate(ctx context.Context, arg IssueCertificateParams) (int64, error) {
	result, err := q.db.Exec(ctx, issueCertificate, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCNRTWork = `-- name: ListCNRTWork :many

SELECT id, tenant_id, unit_id, cnrt_number, inspection_type, inspector_name,
       inspection_date, approved, approval_date, expiry_date, observations,
       rejection_reasons, status, document_url, created_at, updated_at
FROM erp_cnrt_work_orders
WHERE tenant_id = $1 AND unit_id = $2
ORDER BY inspection_date DESC
`

type ListCNRTWorkParams struct {
	TenantID string      `json:"tenant_id"`
	UnitID   pgtype.UUID `json:"unit_id"`
}

// ─── CNRT Work Orders ─────────────────────────────────────────────────────────
func (q *Queries) ListCNRTWork(ctx context.Context, arg ListCNRTWorkParams) ([]ErpCnrtWorkOrder, error) {
	rows, err := q.db.Query(ctx, listCNRTWork, arg.TenantID, arg.UnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpCnrtWorkOrder{}
	for rows.Next() {
		var i ErpCnrtWorkOrder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UnitID,
			&i.CnrtNumber,
			&i.InspectionType,
			&i.InspectorName,
			&i.InspectionDate,
			&i.Approved,
			&i.ApprovalDate,
			&i.ExpiryDate,
			&i.Observations,
			&i.RejectionReasons,
			&i.Status,
			&i.DocumentUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCarroceriaModels = `-- name: ListCarroceriaModels :many

SELECT id, tenant_id, code, model_code, description, abbreviation, double_deck,
       axle_weight_pct, productive_hours_per_station, active, tech_sheet_image,
       created_at, updated_at
FROM erp_carroceria_models
WHERE tenant_id = $1 AND active = true
ORDER BY description
`

// ─── Carroceria Models ─────────────────────────────────────────────────────────
func (q *Queries) ListCarroceriaModels(ctx context.Context, tenantID string) ([]ErpCarroceriaModel, error) {
	rows, err := q.db.Query(ctx, listCarroceriaModels, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpCarroceriaModel{}
	for rows.Next() {
		var i ErpCarroceriaModel
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.ModelCode,
			&i.Description,
			&i.Abbreviation,
			&i.DoubleDeck,
			&i.AxleWeightPct,
			&i.ProductiveHoursPerStation,
			&i.Active,
			&i.TechSheetImage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChassisBrands = `-- name: ListChassisBrands :many

SELECT id, tenant_id, code, name, active, created_at, updated_at
FROM erp_chassis_brands
WHERE tenant_id = $1 AND active = true
ORDER BY name
`

// ─── Chassis Brands ───────────────────────────────────────────────────────────
func (q *Queries) ListChassisBrands(ctx context.Context, tenantID string) ([]ErpChassisBrand, error) {
	rows, err := q.db.Query(ctx, listChassisBrands, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpChassisBrand{}
	for rows.Next() {
		var i ErpChassisBrand
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChassisModels = `-- name: ListChassisModels :many

SELECT cm.id, cm.tenant_id, cm.brand_id, cm.model_code, cm.description,
       cm.traction, cm.engine_location, cm.active, cm.created_at, cm.updated_at,
       cb.name AS brand_name
FROM erp_chassis_models cm
JOIN erp_chassis_brands cb ON cb.id = cm.brand_id AND cb.tenant_id = cm.tenant_id
WHERE cm.tenant_id = $1
  AND ($2::TEXT = '' OR cm.brand_id::TEXT = $2::TEXT)
  AND cm.active = true
ORDER BY cb.name, cm.description
`

type ListChassisModelsParams struct {
	TenantID    string `json:"tenant_id"`
	BrandFilter string `json:"brand_filter"`
}

type ListChassisModelsRow struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       string             `json:"tenant_id"`
	BrandID        pgtype.UUID        `json:"brand_id"`
	ModelCode      string             `json:"model_code"`
	Description    string             `json:"description"`
	Traction       string             `json:"traction"`
	EngineLocation string             `json:"engine_location"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	BrandName      string             `json:"brand_name"`
}

// ─── Chassis Models ────────────────────────────────────────────────────────────
func (q *Queries) ListChassisModels(ctx context.Context, arg ListChassisModelsParams) ([]ListChassisModelsRow, error) {
	rows, err := q.db.Query(ctx, listChassisModels, arg.TenantID, arg.BrandFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChassisModelsRow{}
	for rows.Next() {
		var i ListChassisModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BrandID,
			&i.ModelCode,
			&i.Description,
			&i.Traction,
			&i.EngineLocation,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BrandName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChassisModel = `-- name: GetChassisModel :one
SELECT cm.id, cm.tenant_id, cm.brand_id, cm.model_code, cm.description,
       cm.traction, cm.engine_location, cm.active, cm.created_at, cm.updated_at,
       cb.name AS brand_name
FROM erp_chassis_models cm
JOIN erp_chassis_brands cb ON cb.id = cm.brand_id AND cb.tenant_id = cm.tenant_id
WHERE cm.id = $1 AND cm.tenant_id = $2
`

type GetChassisModelParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

type GetChassisModelRow struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       string             `json:"tenant_id"`
	BrandID        pgtype.UUID        `json:"brand_id"`
	ModelCode      string             `json:"model_code"`
	Description    string             `json:"description"`
	Traction       string             `json:"traction"`
	EngineLocation string             `json:"engine_location"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	BrandName      string             `json:"brand_name"`
}

func (q *Queries) GetChassisModel(ctx context.Context, arg GetChassisModelParams) (GetChassisModelRow, error) {
	row := q.db.QueryRow(ctx, getChassisModel, arg.ID, arg.TenantID)
	var i GetChassisModelRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BrandID,
		&i.ModelCode,
		&i.Description,
		&i.Traction,
		&i.EngineLocation,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BrandName,
	)
	return i, err
}

const listControlCausals = `-- name: ListControlCausals :many

SELECT id, tenant_id, code, description, causal_type, active, created_at, updated_at
FROM erp_production_control_causals
WHERE tenant_id = $1 AND active = true
ORDER BY causal_type, code
`

// ─── Production Control Causals ────────────────────────────────────────────────
func (q *Queries) ListControlCausals(ctx context.Context, tenantID string) ([]ErpProductionControlCausal, error) {
	rows, err := q.db.Query(ctx, listControlCausals, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpProductionControlCausal{}
	for rows.Next() {
		var i ErpProductionControlCausal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Description,
			&i.CausalType,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLCM = `-- name: ListLCM :many

SELECT lcm.id, lcm.tenant_id, lcm.unit_id, lcm.issued_at, lcm.issued_by,
       lcm.warehouse_id, lcm.reference, lcm.status, lcm.notes,
       lcm.created_at, lcm.updated_at,
       e.name AS issued_by_name
FROM erp_manufacturing_lcm lcm
LEFT JOIN erp_entities e ON e.id = lcm.issued_by AND e.tenant_id = lcm.tenant_id
WHERE lcm.tenant_id = $1
  AND ($4::TEXT = '' OR lcm.unit_id::TEXT = $4::TEXT)
  AND ($5::TEXT = '' OR lcm.status = $5::TEXT)
ORDER BY lcm.issued_at DESC
LIMIT $2 OFFSET $3
`

type ListLCMParams struct {
	TenantID     string `json:"tenant_id"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
	UnitFilter   string `json:"unit_filter"`
	StatusFilter string `json:"status_filter"`
}

type ListLCMRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     string             `json:"tenant_id"`
	UnitID       pgtype.UUID        `json:"unit_id"`
	IssuedAt     pgtype.Timestamptz `json:"issued_at"`
	IssuedBy     pgtype.UUID        `json:"issued_by"`
	WarehouseID  pgtype.UUID        `json:"warehouse_id"`
	Reference    string             `json:"reference"`
	Status       string             `json:"status"`
	Notes        string             `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	IssuedByName pgtype.Text        `json:"issued_by_name"`
}

// ─── LCM (Material Consumption per Unit) ─────────────────────────────────────
func (q *Queries) ListLCM(ctx context.Context, arg ListLCMParams) ([]ListLCMRow, error) {
	rows, err := q.db.Query(ctx, listLCM,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.UnitFilter,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLCMRow{}
	for rows.Next() {
		var i ListLCMRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UnitID,
			&i.IssuedAt,
			&i.IssuedBy,
			&i.WarehouseID,
			&i.Reference,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IssuedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLCMModels = `-- name: ListLCMModels :many

SELECT lm.id, lm.tenant_id, lm.lcm_id, lm.article_id, lm.bom_qty,
       lm.issued_qty, lm.returned_qty, lm.unit_cost, lm.notes,
       lm.created_at, lm.updated_at,
       a.code AS article_code, a.name AS article_name
FROM erp_manufacturing_lcm_models lm
JOIN erp_articles a ON a.id = lm.article_id AND a.tenant_id = lm.tenant_id
WHERE lm.lcm_id = $1 AND lm.tenant_id = $2
ORDER BY a.code
`

type ListLCMModelsParams struct {
	LcmID    pgtype.UUID `json:"lcm_id"`
	TenantID string      `json:"tenant_id"`
}

type ListLCMModelsRow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    string             `json:"tenant_id"`
	LcmID       pgtype.UUID        `json:"lcm_id"`
	ArticleID   pgtype.UUID        `json:"article_id"`
	BomQty      pgtype.Numeric     `json:"bom_qty"`
	IssuedQty   pgtype.Numeric     `json:"issued_qty"`
	ReturnedQty pgtype.Numeric     `json:"returned_qty"`
	UnitCost    pgtype.Numeric     `json:"unit_cost"`
	Notes       string             `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ArticleCode string             `json:"article_code"`
	ArticleName string             `json:"article_name"`
}

// ─── LCM Line Items (articles per LCM) ───────────────────────────────────────
func (q *Queries) ListLCMModels(ctx context.Context, arg ListLCMModelsParams) ([]ListLCMModelsRow, error) {
	rows, err := q.db.Query(ctx, listLCMModels, arg.LcmID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLCMModelsRow{}
	for rows.Next() {
		var i ListLCMModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LcmID,
			&i.ArticleID,
			&i.BomQty,
			&i.IssuedQty,
			&i.ReturnedQty,
			&i.UnitCost,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArticleCode,
			&i.ArticleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManufacturingUnits = `-- name: ListManufacturingUnits :many

SELECT mu.id, mu.tenant_id, mu.work_order_number, mu.chassis_serial, mu.engine_number,
       mu.chassis_brand_id, mu.chassis_model_id, mu.carroceria_model_id,
       mu.customer_id, mu.entry_date, mu.expected_completion, mu.actual_completion,
       mu.exit_date, mu.tachograph_id, mu.tachograph_serial, mu.invoice_reference,
       mu.observations, mu.status, mu.created_at, mu.updated_at,
       cb.name AS chassis_brand_name,
       cm.description AS chassis_model_description,
       crm.description AS carroceria_model_description,
       e.name AS customer_name
FROM erp_manufacturing_units mu
LEFT JOIN erp_chassis_brands cb ON cb.id = mu.chassis_brand_id AND cb.tenant_id = mu.tenant_id
LEFT JOIN erp_chassis_models cm ON cm.id = mu.chassis_model_id AND cm.tenant_id = mu.tenant_id
LEFT JOIN erp_carroceria_models crm ON crm.id = mu.carroceria_model_id AND crm.tenant_id = mu.tenant_id
LEFT JOIN erp_entities e ON e.id = mu.customer_id AND e.tenant_id = mu.tenant_id
WHERE mu.tenant_id = $1
  AND ($4::TEXT = '' OR mu.status = $4::TEXT)
ORDER BY mu.work_order_number DESC
LIMIT $2 OFFSET $3
`

type ListManufacturingUnitsParams struct {
	TenantID     string `json:"tenant_id"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
	StatusFilter string `json:"status_filter"`
}

type ListManufacturingUnitsRow struct {
	ID                         pgtype.UUID        `json:"id"`
	TenantID                   string             `json:"tenant_id"`
	WorkOrderNumber            int32              `json:"work_order_number"`
	ChassisSerial              string             `json:"chassis_serial"`
	EngineNumber               string             `json:"engine_number"`
	ChassisBrandID             pgtype.UUID        `json:"chassis_brand_id"`
	ChassisModelID             pgtype.UUID        `json:"chassis_model_id"`
	CarroceriaModelID          pgtype.UUID        `json:"carroceria_model_id"`
	CustomerID                 pgtype.UUID        `json:"customer_id"`
	EntryDate                  pgtype.Date        `json:"entry_date"`
	ExpectedCompletion         pgtype.Date        `json:"expected_completion"`
	ActualCompletion           pgtype.Date        `json:"actual_completion"`
	ExitDate                   pgtype.Date        `json:"exit_date"`
	TachographID               pgtype.Int4        `json:"tachograph_id"`
	TachographSerial           string             `json:"tachograph_serial"`
	InvoiceReference           pgtype.Text        `json:"invoice_reference"`
	Observations               string             `json:"observations"`
	Status                     string             `json:"status"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	ChassisBrandName           pgtype.Text        `json:"chassis_brand_name"`
	ChassisModelDescription    pgtype.Text        `json:"chassis_model_description"`
	CarroceriaModelDescription pgtype.Text        `json:"carroceria_model_description"`
	CustomerName               pgtype.Text        `json:"customer_name"`
}

// ─── Manufacturing Units ───────────────────────────────────────────────────────
func (q *Queries) ListManufacturingUnits(ctx context.Context, arg ListManufacturingUnitsParams) ([]ListManufacturingUnitsRow, error) {
	rows, err := q.db.Query(ctx, listManufacturingUnits,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManufacturingUnitsRow{}
	for rows.Next() {
		var i ListManufacturingUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkOrderNumber,
			&i.ChassisSerial,
			&i.EngineNumber,
			&i.ChassisBrandID,
			&i.ChassisModelID,
			&i.CarroceriaModelID,
			&i.CustomerID,
			&i.EntryDate,
			&i.ExpectedCompletion,
			&i.ActualCompletion,
			&i.ExitDate,
			&i.TachographID,
			&i.TachographSerial,
			&i.InvoiceReference,
			&i.Observations,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChassisBrandName,
			&i.ChassisModelDescription,
			&i.CarroceriaModelDescription,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionControls = `-- name: ListProductionControls :many

SELECT pc.id, pc.tenant_id, pc.unit_id, pc.station, pc.station_seq,
       pc.responsible_id, pc.planned_start, pc.planned_end, pc.actual_start,
       pc.actual_end, pc.status, pc.notes, pc.created_at, pc.updated_at,
       e.name AS responsible_name
FROM erp_production_controls pc
LEFT JOIN erp_entities e ON e.id = pc.responsible_id AND e.tenant_id = pc.tenant_id
WHERE pc.tenant_id = $1 AND pc.unit_id = $2
ORDER BY pc.station_seq
`

type ListProductionControlsParams struct {
	TenantID string      `json:"tenant_id"`
	UnitID   pgtype.UUID `json:"unit_id"`
}

type ListProductionControlsRow struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        string             `json:"tenant_id"`
	UnitID          pgtype.UUID        `json:"unit_id"`
	Station         string             `json:"station"`
	StationSeq      int32              `json:"station_seq"`
	ResponsibleID   pgtype.UUID        `json:"responsible_id"`
	PlannedStart    pgtype.Date        `json:"planned_start"`
	PlannedEnd      pgtype.Date        `json:"planned_end"`
	ActualStart     pgtype.Timestamptz `json:"actual_start"`
	ActualEnd       pgtype.Timestamptz `json:"actual_end"`
	Status          string             `json:"status"`
	Notes           string             `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ResponsibleName pgtype.Text        `json:"responsible_name"`
}

// ─── Production Controls (station tracking per unit) ──────────────────────────
func (q *Queries) ListProductionControls(ctx context.Context, arg ListProductionControlsParams) ([]ListProductionControlsRow, error) {
	rows, err := q.db.Query(ctx, listProductionControls, arg.TenantID, arg.UnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductionControlsRow{}
	for rows.Next() {
		var i ListProductionControlsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UnitID,
			&i.Station,
			&i.StationSeq,
			&i.ResponsibleID,
			&i.PlannedStart,
			&i.PlannedEnd,
			&i.ActualStart,
			&i.ActualEnd,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResponsibleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCertificate = `-- name: UpdateCertificate :one
UPDATE erp_manufacturing_certificates SET
    certificate_number = $3,
    cert_type = $4,
    valid_from = $5,
    valid_until = $6,
    authority = $7,
    document_url = $8,
    observations = $9,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, unit_id, certificate_number, cert_type, issued_by,
          issued_at, valid_from, valid_until, authority, document_url,
          observations, status, revoked_at, revocation_reason, created_at, updated_at
`

type UpdateCertificateParams struct {
	ID                pgtype.UUID `json:"id"`
	TenantID          string      `json:"tenant_id"`
	CertificateNumber string      `json:"certificate_number"`
	CertType          string      `json:"cert_type"`
	ValidFrom         pgtype.Date `json:"valid_from"`
	ValidUntil        pgtype.Date `json:"valid_until"`
	Authority         string      `json:"authority"`
	DocumentUrl       string      `json:"document_url"`
	Observations      string      `json:"observations"`
}

func (q *Queries) UpdateCertificate(ctx context.Context, arg UpdateCertificateParams) (ErpManufacturingCertificate, error) {
	row := q.db.QueryRow(ctx, updateCertificate,
		arg.ID,
		arg.TenantID,
		arg.CertificateNumber,
		arg.CertType,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.Authority,
		arg.DocumentUrl,
		arg.Observations,
	)
	var i ErpManufacturingCertificate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnitID,
		&i.CertificateNumber,
		&i.CertType,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Authority,
		&i.DocumentUrl,
		&i.Observations,
		&i.Status,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateManufacturingUnitStatus = `-- name: UpdateManufacturingUnitStatus :execrows
UPDATE erp_manufacturing_units
SET status = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type UpdateManufacturingUnitStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateManufacturingUnitStatus(ctx context.Context, arg UpdateManufacturingUnitStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateManufacturingUnitStatus, arg.ID, arg.TenantID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUnitCompletion = `-- name: UpdateUnitCompletion :execrows
UPDATE erp_manufacturing_units
SET actual_completion = $3, exit_date = $4, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type UpdateUnitCompletionParams struct {
	ID               pgtype.UUID `json:"id"`
	TenantID         string      `json:"tenant_id"`
	ActualCompletion pgtype.Date `json:"actual_completion"`
	ExitDate         pgtype.Date `json:"exit_date"`
}

func (q *Queries) UpdateUnitCompletion(ctx context.Context, arg UpdateUnitCompletionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUnitCompletion,
		arg.ID,
		arg.TenantID,
		arg.ActualCompletion,
		arg.ExitDate,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
