// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listProductSections = `-- name: ListProductSections :many
SELECT id, tenant_id, legacy_id, name, sort_order, rubro_id, active, created_at
FROM erp_product_sections
WHERE tenant_id = $1
ORDER BY sort_order, name
`

func (q *Queries) ListProductSections(ctx context.Context, tenantID string) ([]ErpProductSection, error) {
	rows, err := q.db.Query(ctx, listProductSections, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpProductSection{}
	for rows.Next() {
		var i ErpProductSection
		if err := rows.Scan(
			&i.ID, &i.TenantID, &i.LegacyID, &i.Name, &i.SortOrder,
			&i.RubroID, &i.Active, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, tenant_id, legacy_id, description, supplier_entity_id,
       supplier_code, created_at
FROM erp_products
WHERE tenant_id = $1
ORDER BY description
LIMIT $2 OFFSET $3
`

type ListProductsParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ErpProduct, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpProduct{}
	for rows.Next() {
		var i ErpProduct
		if err := rows.Scan(
			&i.ID, &i.TenantID, &i.LegacyID, &i.Description,
			&i.SupplierEntityID, &i.SupplierCode, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductAttributes = `-- name: ListProductAttributes :many
SELECT id, tenant_id, legacy_id, name, attribute_type, section_id,
       section_legacy_id, article_code, helper_xml, helper_dir, parameters,
       sort_order, active, print_label, print_value,
       active_in_quote, active_in_tech_sheet, quote_description,
       define_before_section_id, standard_additional,
       code, print_section_id, created_at
FROM erp_product_attributes
WHERE tenant_id = $1
  AND ($2::BOOLEAN = false OR active = true)
ORDER BY sort_order, name
`

type ListProductAttributesParams struct {
	TenantID   string `json:"tenant_id"`
	ActiveOnly bool   `json:"active_only"`
}

func (q *Queries) ListProductAttributes(ctx context.Context, arg ListProductAttributesParams) ([]ErpProductAttribute, error) {
	rows, err := q.db.Query(ctx, listProductAttributes, arg.TenantID, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpProductAttribute{}
	for rows.Next() {
		var i ErpProductAttribute
		if err := rows.Scan(
			&i.ID, &i.TenantID, &i.LegacyID, &i.Name, &i.AttributeType,
			&i.SectionID, &i.SectionLegacyID, &i.ArticleCode,
			&i.HelperXML, &i.HelperDir, &i.Parameters,
			&i.SortOrder, &i.Active, &i.PrintLabel, &i.PrintValue,
			&i.ActiveInQuote, &i.ActiveInTechSheet, &i.QuoteDescription,
			&i.DefineBeforeSectionID, &i.StandardAdditional,
			&i.Code, &i.PrintSectionID, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductAttributeOptions = `-- name: ListProductAttributeOptions :many
SELECT id, tenant_id, legacy_id, attribute_id, attribute_legacy_id,
       option_name, option_value, created_at
FROM erp_product_attribute_options
WHERE tenant_id = $1 AND attribute_id = $2
ORDER BY option_value
`

type ListProductAttributeOptionsParams struct {
	TenantID    string      `json:"tenant_id"`
	AttributeID pgtype.UUID `json:"attribute_id"`
}

func (q *Queries) ListProductAttributeOptions(ctx context.Context, arg ListProductAttributeOptionsParams) ([]ErpProductAttributeOption, error) {
	rows, err := q.db.Query(ctx, listProductAttributeOptions, arg.TenantID, arg.AttributeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpProductAttributeOption{}
	for rows.Next() {
		var i ErpProductAttributeOption
		if err := rows.Scan(
			&i.ID, &i.TenantID, &i.LegacyID, &i.AttributeID,
			&i.AttributeLegacyID, &i.OptionName, &i.OptionValue, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductAttributeValues = `-- name: ListProductAttributeValues :many
SELECT id, tenant_id, legacy_id, product_id, product_legacy_id,
       attribute_id, attribute_legacy_id, value, quantity,
       quote_legacy_id, recorded_at, created_at
FROM erp_product_attribute_values
WHERE tenant_id = $1 AND product_id = $2
ORDER BY attribute_legacy_id
`

type ListProductAttributeValuesParams struct {
	TenantID  string      `json:"tenant_id"`
	ProductID pgtype.UUID `json:"product_id"`
}

// Values for a single product, ordered by attribute. The UI replaces
// producto/producto_atributos_valores.xml with this.
func (q *Queries) ListProductAttributeValues(ctx context.Context, arg ListProductAttributeValuesParams) ([]ErpProductAttributeValue, error) {
	rows, err := q.db.Query(ctx, listProductAttributeValues, arg.TenantID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpProductAttributeValue{}
	for rows.Next() {
		var i ErpProductAttributeValue
		if err := rows.Scan(
			&i.ID, &i.TenantID, &i.LegacyID, &i.ProductID,
			&i.ProductLegacyID, &i.AttributeID, &i.AttributeLegacyID,
			&i.Value, &i.Quantity, &i.QuoteLegacyID, &i.RecordedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductAttributeHomologations = `-- name: ListProductAttributeHomologations :many
SELECT id, tenant_id, legacy_id, attribute_id, attribute_legacy_id,
       homologation_id, homologation_legacy_id, created_at
FROM erp_product_attribute_homologations
WHERE tenant_id = $1 AND attribute_id = $2
ORDER BY homologation_legacy_id
`

type ListProductAttributeHomologationsParams struct {
	TenantID    string      `json:"tenant_id"`
	AttributeID pgtype.UUID `json:"attribute_id"`
}

// Cross-reference between attribute definitions and vehicle homologations.
func (q *Queries) ListProductAttributeHomologations(ctx context.Context, arg ListProductAttributeHomologationsParams) ([]ErpProductAttributeHomologation, error) {
	rows, err := q.db.Query(ctx, listProductAttributeHomologations, arg.TenantID, arg.AttributeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpProductAttributeHomologation{}
	for rows.Next() {
		var i ErpProductAttributeHomologation
		if err := rows.Scan(
			&i.ID, &i.TenantID, &i.LegacyID, &i.AttributeID,
			&i.AttributeLegacyID, &i.HomologationID, &i.HomologationLegacyID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
