// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: production.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeProductionOrder = `-- name: CompleteProductionOrder :execrows
UPDATE erp_production_orders SET status = 'completed', end_date = COALESCE(end_date, CURRENT_DATE)
WHERE id = $1 AND tenant_id = $2 AND status = 'in_progress'
`

type CompleteProductionOrderParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) CompleteProductionOrder(ctx context.Context, arg CompleteProductionOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeProductionOrder, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createProductionCenter = `-- name: CreateProductionCenter :one
INSERT INTO erp_production_centers (tenant_id, code, name)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, code, name, active
`

type CreateProductionCenterParams struct {
	TenantID string `json:"tenant_id"`
	Code     string `json:"code"`
	Name     string `json:"name"`
}

func (q *Queries) CreateProductionCenter(ctx context.Context, arg CreateProductionCenterParams) (ErpProductionCenter, error) {
	row := q.db.QueryRow(ctx, createProductionCenter, arg.TenantID, arg.Code, arg.Name)
	var i ErpProductionCenter
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Active,
	)
	return i, err
}

const createProductionInspection = `-- name: CreateProductionInspection :one
INSERT INTO erp_production_inspections (tenant_id, order_id, step_id, inspector_id, result, observations)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, order_id, step_id, inspector_id, result, observations, created_at
`

type CreateProductionInspectionParams struct {
	TenantID     string      `json:"tenant_id"`
	OrderID      pgtype.UUID `json:"order_id"`
	StepID       pgtype.UUID `json:"step_id"`
	InspectorID  pgtype.UUID `json:"inspector_id"`
	Result       string      `json:"result"`
	Observations string      `json:"observations"`
}

func (q *Queries) CreateProductionInspection(ctx context.Context, arg CreateProductionInspectionParams) (ErpProductionInspection, error) {
	row := q.db.QueryRow(ctx, createProductionInspection,
		arg.TenantID,
		arg.OrderID,
		arg.StepID,
		arg.InspectorID,
		arg.Result,
		arg.Observations,
	)
	var i ErpProductionInspection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.StepID,
		&i.InspectorID,
		&i.Result,
		&i.Observations,
		&i.CreatedAt,
	)
	return i, err
}

const createProductionMaterial = `-- name: CreateProductionMaterial :one
INSERT INTO erp_production_materials (tenant_id, order_id, article_id, required_qty, warehouse_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, order_id, article_id, required_qty, consumed_qty, warehouse_id
`

type CreateProductionMaterialParams struct {
	TenantID    string         `json:"tenant_id"`
	OrderID     pgtype.UUID    `json:"order_id"`
	ArticleID   pgtype.UUID    `json:"article_id"`
	RequiredQty pgtype.Numeric `json:"required_qty"`
	WarehouseID pgtype.UUID    `json:"warehouse_id"`
}

func (q *Queries) CreateProductionMaterial(ctx context.Context, arg CreateProductionMaterialParams) (ErpProductionMaterial, error) {
	row := q.db.QueryRow(ctx, createProductionMaterial,
		arg.TenantID,
		arg.OrderID,
		arg.ArticleID,
		arg.RequiredQty,
		arg.WarehouseID,
	)
	var i ErpProductionMaterial
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.ArticleID,
		&i.RequiredQty,
		&i.ConsumedQty,
		&i.WarehouseID,
	)
	return i, err
}

const createProductionOrder = `-- name: CreateProductionOrder :one
INSERT INTO erp_production_orders (tenant_id, number, date, product_id, center_id, quantity,
    priority, order_id, start_date, end_date, user_id, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, tenant_id, number, date, product_id, center_id, quantity, status,
    priority, order_id, start_date, end_date, user_id, notes, created_at
`

type CreateProductionOrderParams struct {
	TenantID  string         `json:"tenant_id"`
	Number    string         `json:"number"`
	Date      pgtype.Date    `json:"date"`
	ProductID pgtype.UUID    `json:"product_id"`
	CenterID  pgtype.UUID    `json:"center_id"`
	Quantity  pgtype.Numeric `json:"quantity"`
	Priority  int32          `json:"priority"`
	OrderID   pgtype.UUID    `json:"order_id"`
	StartDate pgtype.Date    `json:"start_date"`
	EndDate   pgtype.Date    `json:"end_date"`
	UserID    string         `json:"user_id"`
	Notes     string         `json:"notes"`
}

func (q *Queries) CreateProductionOrder(ctx context.Context, arg CreateProductionOrderParams) (ErpProductionOrder, error) {
	row := q.db.QueryRow(ctx, createProductionOrder,
		arg.TenantID,
		arg.Number,
		arg.Date,
		arg.ProductID,
		arg.CenterID,
		arg.Quantity,
		arg.Priority,
		arg.OrderID,
		arg.StartDate,
		arg.EndDate,
		arg.UserID,
		arg.Notes,
	)
	var i ErpProductionOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Number,
		&i.Date,
		&i.ProductID,
		&i.CenterID,
		&i.Quantity,
		&i.Status,
		&i.Priority,
		&i.OrderID,
		&i.StartDate,
		&i.EndDate,
		&i.UserID,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createProductionStep = `-- name: CreateProductionStep :one
INSERT INTO erp_production_steps (tenant_id, order_id, step_name, sort_order, assigned_to)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, order_id, step_name, sort_order, status, assigned_to, started_at, completed_at, notes
`

type CreateProductionStepParams struct {
	TenantID   string      `json:"tenant_id"`
	OrderID    pgtype.UUID `json:"order_id"`
	StepName   string      `json:"step_name"`
	SortOrder  int32       `json:"sort_order"`
	AssignedTo pgtype.UUID `json:"assigned_to"`
}

func (q *Queries) CreateProductionStep(ctx context.Context, arg CreateProductionStepParams) (ErpProductionStep, error) {
	row := q.db.QueryRow(ctx, createProductionStep,
		arg.TenantID,
		arg.OrderID,
		arg.StepName,
		arg.SortOrder,
		arg.AssignedTo,
	)
	var i ErpProductionStep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.StepName,
		&i.SortOrder,
		&i.Status,
		&i.AssignedTo,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Notes,
	)
	return i, err
}

const createUnit = `-- name: CreateUnit :one
INSERT INTO erp_units (tenant_id, chassis_number, internal_number, model, customer_id,
    order_id, production_order_id, patent, engine_brand, body_style, seat_count, year, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, tenant_id, chassis_number, internal_number, model, customer_id,
    order_id, production_order_id, patent, status, engine_brand, body_style,
    seat_count, year, metadata, delivered_at, created_at
`

type CreateUnitParams struct {
	TenantID          string      `json:"tenant_id"`
	ChassisNumber     string      `json:"chassis_number"`
	InternalNumber    pgtype.Text `json:"internal_number"`
	Model             pgtype.Text `json:"model"`
	CustomerID        pgtype.UUID `json:"customer_id"`
	OrderID           pgtype.UUID `json:"order_id"`
	ProductionOrderID pgtype.UUID `json:"production_order_id"`
	Patent            pgtype.Text `json:"patent"`
	EngineBrand       pgtype.Text `json:"engine_brand"`
	BodyStyle         pgtype.Text `json:"body_style"`
	SeatCount         pgtype.Int4 `json:"seat_count"`
	Year              pgtype.Int4 `json:"year"`
	Metadata          []byte      `json:"metadata"`
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (ErpUnit, error) {
	row := q.db.QueryRow(ctx, createUnit,
		arg.TenantID,
		arg.ChassisNumber,
		arg.InternalNumber,
		arg.Model,
		arg.CustomerID,
		arg.OrderID,
		arg.ProductionOrderID,
		arg.Patent,
		arg.EngineBrand,
		arg.BodyStyle,
		arg.SeatCount,
		arg.Year,
		arg.Metadata,
	)
	var i ErpUnit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChassisNumber,
		&i.InternalNumber,
		&i.Model,
		&i.CustomerID,
		&i.OrderID,
		&i.ProductionOrderID,
		&i.Patent,
		&i.Status,
		&i.EngineBrand,
		&i.BodyStyle,
		&i.SeatCount,
		&i.Year,
		&i.Metadata,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProductionOrder = `-- name: GetProductionOrder :one
SELECT id, tenant_id, number, date, product_id, center_id, quantity, status,
       priority, order_id, start_date, end_date, user_id, notes, created_at
FROM erp_production_orders WHERE id = $1 AND tenant_id = $2
`

type GetProductionOrderParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) GetProductionOrder(ctx context.Context, arg GetProductionOrderParams) (ErpProductionOrder, error) {
	row := q.db.QueryRow(ctx, getProductionOrder, arg.ID, arg.TenantID)
	var i ErpProductionOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Number,
		&i.Date,
		&i.ProductID,
		&i.CenterID,
		&i.Quantity,
		&i.Status,
		&i.Priority,
		&i.OrderID,
		&i.StartDate,
		&i.EndDate,
		&i.UserID,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getUnit = `-- name: GetUnit :one
SELECT id, tenant_id, chassis_number, internal_number, model, customer_id,
       order_id, production_order_id, patent, status, engine_brand, body_style,
       seat_count, year, metadata, delivered_at, created_at
FROM erp_units WHERE id = $1 AND tenant_id = $2
`

type GetUnitParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) GetUnit(ctx context.Context, arg GetUnitParams) (ErpUnit, error) {
	row := q.db.QueryRow(ctx, getUnit, arg.ID, arg.TenantID)
	var i ErpUnit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChassisNumber,
		&i.InternalNumber,
		&i.Model,
		&i.CustomerID,
		&i.OrderID,
		&i.ProductionOrderID,
		&i.Patent,
		&i.Status,
		&i.EngineBrand,
		&i.BodyStyle,
		&i.SeatCount,
		&i.Year,
		&i.Metadata,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listProductionCenters = `-- name: ListProductionCenters :many
SELECT id, tenant_id, code, name, active
FROM erp_production_centers WHERE tenant_id = $1 ORDER BY code
`

func (q *Queries) ListProductionCenters(ctx context.Context, tenantID string) ([]ErpProductionCenter, error) {
	rows, err := q.db.Query(ctx, listProductionCenters, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpProductionCenter{}
	for rows.Next() {
		var i ErpProductionCenter
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionMaterials = `-- name: ListProductionMaterials :many
SELECT pm.id, pm.tenant_id, pm.order_id, pm.article_id, pm.required_qty,
       pm.consumed_qty, pm.warehouse_id,
       a.code AS article_code, a.name AS article_name
FROM erp_production_materials pm
JOIN erp_articles a ON a.id = pm.article_id
WHERE pm.order_id = $1 AND pm.tenant_id = $2
ORDER BY a.code
`

type ListProductionMaterialsParams struct {
	OrderID  pgtype.UUID `json:"order_id"`
	TenantID string      `json:"tenant_id"`
}

type ListProductionMaterialsRow struct {
	ID          pgtype.UUID    `json:"id"`
	TenantID    string         `json:"tenant_id"`
	OrderID     pgtype.UUID    `json:"order_id"`
	ArticleID   pgtype.UUID    `json:"article_id"`
	RequiredQty pgtype.Numeric `json:"required_qty"`
	ConsumedQty pgtype.Numeric `json:"consumed_qty"`
	WarehouseID pgtype.UUID    `json:"warehouse_id"`
	ArticleCode string         `json:"article_code"`
	ArticleName string         `json:"article_name"`
}

func (q *Queries) ListProductionMaterials(ctx context.Context, arg ListProductionMaterialsParams) ([]ListProductionMaterialsRow, error) {
	rows, err := q.db.Query(ctx, listProductionMaterials, arg.OrderID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductionMaterialsRow{}
	for rows.Next() {
		var i ListProductionMaterialsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrderID,
			&i.ArticleID,
			&i.RequiredQty,
			&i.ConsumedQty,
			&i.WarehouseID,
			&i.ArticleCode,
			&i.ArticleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionOrders = `-- name: ListProductionOrders :many
SELECT po.id, po.tenant_id, po.number, po.date, po.product_id, po.center_id,
       po.quantity, po.status, po.priority, po.order_id, po.start_date, po.end_date,
       po.user_id, po.notes, po.created_at,
       a.code AS product_code, a.name AS product_name
FROM erp_production_orders po
JOIN erp_articles a ON a.id = po.product_id
WHERE po.tenant_id = $1
  AND ($4::TEXT = '' OR po.status = $4::TEXT)
ORDER BY po.date DESC
LIMIT $2 OFFSET $3
`

type ListProductionOrdersParams struct {
	TenantID     string `json:"tenant_id"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
	StatusFilter string `json:"status_filter"`
}

type ListProductionOrdersRow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    string             `json:"tenant_id"`
	Number      string             `json:"number"`
	Date        pgtype.Date        `json:"date"`
	ProductID   pgtype.UUID        `json:"product_id"`
	CenterID    pgtype.UUID        `json:"center_id"`
	Quantity    pgtype.Numeric     `json:"quantity"`
	Status      string             `json:"status"`
	Priority    int32              `json:"priority"`
	OrderID     pgtype.UUID        `json:"order_id"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	UserID      string             `json:"user_id"`
	Notes       string             `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProductCode string             `json:"product_code"`
	ProductName string             `json:"product_name"`
}

func (q *Queries) ListProductionOrders(ctx context.Context, arg ListProductionOrdersParams) ([]ListProductionOrdersRow, error) {
	rows, err := q.db.Query(ctx, listProductionOrders,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductionOrdersRow{}
	for rows.Next() {
		var i ListProductionOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Number,
			&i.Date,
			&i.ProductID,
			&i.CenterID,
			&i.Quantity,
			&i.Status,
			&i.Priority,
			&i.OrderID,
			&i.StartDate,
			&i.EndDate,
			&i.UserID,
			&i.Notes,
			&i.CreatedAt,
			&i.ProductCode,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionSteps = `-- name: ListProductionSteps :many
SELECT id, tenant_id, order_id, step_name, sort_order, status,
       assigned_to, started_at, completed_at, notes
FROM erp_production_steps WHERE order_id = $1 AND tenant_id = $2
ORDER BY sort_order
`

type ListProductionStepsParams struct {
	OrderID  pgtype.UUID `json:"order_id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) ListProductionSteps(ctx context.Context, arg ListProductionStepsParams) ([]ErpProductionStep, error) {
	rows, err := q.db.Query(ctx, listProductionSteps, arg.OrderID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpProductionStep{}
	for rows.Next() {
		var i ErpProductionStep
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrderID,
			&i.StepName,
			&i.SortOrder,
			&i.Status,
			&i.AssignedTo,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnits = `-- name: ListUnits :many
SELECT id, tenant_id, chassis_number, internal_number, model, customer_id,
       order_id, production_order_id, patent, status, engine_brand, body_style,
       seat_count, year, delivered_at, created_at
FROM erp_units WHERE tenant_id = $1
  AND ($4::TEXT = '' OR status = $4::TEXT)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUnitsParams struct {
	TenantID     string `json:"tenant_id"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
	StatusFilter string `json:"status_filter"`
}

type ListUnitsRow struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          string             `json:"tenant_id"`
	ChassisNumber     string             `json:"chassis_number"`
	InternalNumber    pgtype.Text        `json:"internal_number"`
	Model             pgtype.Text        `json:"model"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	OrderID           pgtype.UUID        `json:"order_id"`
	ProductionOrderID pgtype.UUID        `json:"production_order_id"`
	Patent            pgtype.Text        `json:"patent"`
	Status            string             `json:"status"`
	EngineBrand       pgtype.Text        `json:"engine_brand"`
	BodyStyle         pgtype.Text        `json:"body_style"`
	SeatCount         pgtype.Int4        `json:"seat_count"`
	Year              pgtype.Int4        `json:"year"`
	DeliveredAt       pgtype.Date        `json:"delivered_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUnits(ctx context.Context, arg ListUnitsParams) ([]ListUnitsRow, error) {
	rows, err := q.db.Query(ctx, listUnits,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnitsRow{}
	for rows.Next() {
		var i ListUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChassisNumber,
			&i.InternalNumber,
			&i.Model,
			&i.CustomerID,
			&i.OrderID,
			&i.ProductionOrderID,
			&i.Patent,
			&i.Status,
			&i.EngineBrand,
			&i.BodyStyle,
			&i.SeatCount,
			&i.Year,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startProductionOrder = `-- name: StartProductionOrder :execrows
UPDATE erp_production_orders SET status = 'in_progress', start_date = COALESCE(start_date, CURRENT_DATE)
WHERE id = $1 AND tenant_id = $2 AND status = 'planned'
`

type StartProductionOrderParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) StartProductionOrder(ctx context.Context, arg StartProductionOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, startProductionOrder, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProductionStep = `-- name: UpdateProductionStep :execrows
UPDATE erp_production_steps SET status = $3, started_at = CASE WHEN $3 = 'in_progress' AND started_at IS NULL THEN now() ELSE started_at END,
    completed_at = CASE WHEN $3 = 'completed' THEN now() ELSE completed_at END, notes = COALESCE(NULLIF($4, ''), notes)
WHERE id = $1 AND tenant_id = $2
`

type UpdateProductionStepParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
	Status   string      `json:"status"`
	Column4  interface{} `json:"column_4"`
}

func (q *Queries) UpdateProductionStep(ctx context.Context, arg UpdateProductionStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProductionStep,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.Column4,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUnitStatus = `-- name: UpdateUnitStatus :execrows
UPDATE erp_units SET status = $3, delivered_at = CASE WHEN $3 = 'delivered' THEN CURRENT_DATE ELSE delivered_at END
WHERE id = $1 AND tenant_id = $2
`

type UpdateUnitStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateUnitStatus(ctx context.Context, arg UpdateUnitStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUnitStatus, arg.ID, arg.TenantID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listHomologations = `-- name: ListHomologations :many
SELECT id, tenant_id, plano, expte, dispos, fecha_aprob, fecha_vto,
       seats, seats_lower, weight_tare, weight_gross, vin,
       commercial_code, commercial_desc, active, created_at
FROM erp_homologations
WHERE tenant_id = $1
  AND ($4::BOOLEAN = false OR active = true)
ORDER BY commercial_code, id
LIMIT $2 OFFSET $3
`

type ListHomologationsParams struct {
	TenantID   string `json:"tenant_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
	ActiveOnly bool   `json:"active_only"`
}

func (q *Queries) ListHomologations(ctx context.Context, arg ListHomologationsParams) ([]ErpHomologation, error) {
	rows, err := q.db.Query(ctx, listHomologations,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.ActiveOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpHomologation{}
	for rows.Next() {
		var i ErpHomologation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Plano,
			&i.Expte,
			&i.Dispos,
			&i.FechaAprob,
			&i.FechaVto,
			&i.Seats,
			&i.SeatsLower,
			&i.WeightTare,
			&i.WeightGross,
			&i.Vin,
			&i.CommercialCode,
			&i.CommercialDesc,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomologationRevisions = `-- name: ListHomologationRevisions :many
SELECT id, tenant_id, homologation_id, date, notes, created_at
FROM erp_homologation_revisions
WHERE tenant_id = $1 AND homologation_id = $2
ORDER BY date DESC, id
LIMIT $3 OFFSET $4
`

type ListHomologationRevisionsParams struct {
	TenantID       string      `json:"tenant_id"`
	HomologationID pgtype.UUID `json:"homologation_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListHomologationRevisions(ctx context.Context, arg ListHomologationRevisionsParams) ([]ErpHomologationRevision, error) {
	rows, err := q.db.Query(ctx, listHomologationRevisions,
		arg.TenantID,
		arg.HomologationID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpHomologationRevision{}
	for rows.Next() {
		var i ErpHomologationRevision
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.HomologationID,
			&i.Date,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomologationRevisionLines = `-- name: ListHomologationRevisionLines :many
SELECT id, tenant_id, revision_id, article_id, article_code, article_desc, article_unit,
       process_1, process_2, process_3, process_4,
       multiplier, quantity, replacement_cost, replacement_partial,
       replacement_cost_desc, replacement_partial_desc,
       account_code, account_name, partial_with_surcharge, region_percentage,
       partial_clog, partial_surcharge_log, logistics_cost, created_at
FROM erp_homologation_revision_lines
WHERE tenant_id = $1 AND revision_id = $2
ORDER BY process_1, process_2, process_3, process_4, article_code
LIMIT $3 OFFSET $4
`

type ListHomologationRevisionLinesParams struct {
	TenantID   string      `json:"tenant_id"`
	RevisionID pgtype.UUID `json:"revision_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListHomologationRevisionLines(ctx context.Context, arg ListHomologationRevisionLinesParams) ([]ErpHomologationRevisionLine, error) {
	rows, err := q.db.Query(ctx, listHomologationRevisionLines,
		arg.TenantID,
		arg.RevisionID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpHomologationRevisionLine{}
	for rows.Next() {
		var i ErpHomologationRevisionLine
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RevisionID,
			&i.ArticleID,
			&i.ArticleCode,
			&i.ArticleDesc,
			&i.ArticleUnit,
			&i.Process1,
			&i.Process2,
			&i.Process3,
			&i.Process4,
			&i.Multiplier,
			&i.Quantity,
			&i.ReplacementCost,
			&i.ReplacementPartial,
			&i.ReplacementCostDesc,
			&i.ReplacementPartialDesc,
			&i.AccountCode,
			&i.AccountName,
			&i.PartialWithSurcharge,
			&i.RegionPercentage,
			&i.PartialClog,
			&i.PartialSurchargeLog,
			&i.LogisticsCost,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionInspectionHomologations = `-- name: ListProductionInspectionHomologations :many
SELECT id, tenant_id, legacy_id,
       inspection_id, inspection_legacy_id,
       homologation_id, homologation_legacy_id, created_at
FROM erp_production_inspection_homologations
WHERE tenant_id = $1 AND inspection_id = $2
ORDER BY homologation_legacy_id
LIMIT $3 OFFSET $4
`

type ListProductionInspectionHomologationsParams struct {
	TenantID     string      `json:"tenant_id"`
	InspectionID pgtype.UUID `json:"inspection_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

// Production inspection templates × homologated vehicle models. Pareto #7.
func (q *Queries) ListProductionInspectionHomologations(ctx context.Context, arg ListProductionInspectionHomologationsParams) ([]ErpProductionInspectionHomologation, error) {
	rows, err := q.db.Query(ctx, listProductionInspectionHomologations,
		arg.TenantID, arg.InspectionID, arg.Limit, arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpProductionInspectionHomologation{}
	for rows.Next() {
		var i ErpProductionInspectionHomologation
		if err := rows.Scan(
			&i.ID, &i.TenantID, &i.LegacyID,
			&i.InspectionID, &i.InspectionLegacyID,
			&i.HomologationID, &i.HomologationLegacyID, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
