// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: purchasing.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvePurchaseOrder = `-- name: ApprovePurchaseOrder :execrows
UPDATE erp_purchase_orders SET status = 'approved'
WHERE id = $1 AND tenant_id = $2 AND status = 'draft'
`

type ApprovePurchaseOrderParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) ApprovePurchaseOrder(ctx context.Context, arg ApprovePurchaseOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, approvePurchaseOrder, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPurchaseOrder = `-- name: CreatePurchaseOrder :one
INSERT INTO erp_purchase_orders (tenant_id, number, date, supplier_id, currency_id, total, notes, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, number, date, supplier_id, status, currency_id, total, notes, user_id, created_at
`

type CreatePurchaseOrderParams struct {
	TenantID   string         `json:"tenant_id"`
	Number     string         `json:"number"`
	Date       pgtype.Date    `json:"date"`
	SupplierID pgtype.UUID    `json:"supplier_id"`
	CurrencyID pgtype.UUID    `json:"currency_id"`
	Total      pgtype.Numeric `json:"total"`
	Notes      string         `json:"notes"`
	UserID     string         `json:"user_id"`
}

func (q *Queries) CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (ErpPurchaseOrder, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrder,
		arg.TenantID,
		arg.Number,
		arg.Date,
		arg.SupplierID,
		arg.CurrencyID,
		arg.Total,
		arg.Notes,
		arg.UserID,
	)
	var i ErpPurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Number,
		&i.Date,
		&i.SupplierID,
		&i.Status,
		&i.CurrencyID,
		&i.Total,
		&i.Notes,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const createPurchaseOrderLine = `-- name: CreatePurchaseOrderLine :one
INSERT INTO erp_purchase_order_lines (tenant_id, order_id, article_id, quantity, unit_price, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, order_id, article_id, quantity, unit_price, received_qty, sort_order
`

type CreatePurchaseOrderLineParams struct {
	TenantID  string         `json:"tenant_id"`
	OrderID   pgtype.UUID    `json:"order_id"`
	ArticleID pgtype.UUID    `json:"article_id"`
	Quantity  pgtype.Numeric `json:"quantity"`
	UnitPrice pgtype.Numeric `json:"unit_price"`
	SortOrder int32          `json:"sort_order"`
}

func (q *Queries) CreatePurchaseOrderLine(ctx context.Context, arg CreatePurchaseOrderLineParams) (ErpPurchaseOrderLine, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrderLine,
		arg.TenantID,
		arg.OrderID,
		arg.ArticleID,
		arg.Quantity,
		arg.UnitPrice,
		arg.SortOrder,
	)
	var i ErpPurchaseOrderLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.ArticleID,
		&i.Quantity,
		&i.UnitPrice,
		&i.ReceivedQty,
		&i.SortOrder,
	)
	return i, err
}

const createPurchaseReceipt = `-- name: CreatePurchaseReceipt :one
INSERT INTO erp_purchase_receipts (tenant_id, order_id, date, number, user_id, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, order_id, date, number, user_id, notes, created_at
`

type CreatePurchaseReceiptParams struct {
	TenantID string      `json:"tenant_id"`
	OrderID  pgtype.UUID `json:"order_id"`
	Date     pgtype.Date `json:"date"`
	Number   string      `json:"number"`
	UserID   string      `json:"user_id"`
	Notes    string      `json:"notes"`
}

func (q *Queries) CreatePurchaseReceipt(ctx context.Context, arg CreatePurchaseReceiptParams) (ErpPurchaseReceipt, error) {
	row := q.db.QueryRow(ctx, createPurchaseReceipt,
		arg.TenantID,
		arg.OrderID,
		arg.Date,
		arg.Number,
		arg.UserID,
		arg.Notes,
	)
	var i ErpPurchaseReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.Date,
		&i.Number,
		&i.UserID,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createPurchaseReceiptLine = `-- name: CreatePurchaseReceiptLine :one
INSERT INTO erp_purchase_receipt_lines (tenant_id, receipt_id, order_line_id, article_id, quantity)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, receipt_id, order_line_id, article_id, quantity
`

type CreatePurchaseReceiptLineParams struct {
	TenantID    string         `json:"tenant_id"`
	ReceiptID   pgtype.UUID    `json:"receipt_id"`
	OrderLineID pgtype.UUID    `json:"order_line_id"`
	ArticleID   pgtype.UUID    `json:"article_id"`
	Quantity    pgtype.Numeric `json:"quantity"`
}

func (q *Queries) CreatePurchaseReceiptLine(ctx context.Context, arg CreatePurchaseReceiptLineParams) (ErpPurchaseReceiptLine, error) {
	row := q.db.QueryRow(ctx, createPurchaseReceiptLine,
		arg.TenantID,
		arg.ReceiptID,
		arg.OrderLineID,
		arg.ArticleID,
		arg.Quantity,
	)
	var i ErpPurchaseReceiptLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReceiptID,
		&i.OrderLineID,
		&i.ArticleID,
		&i.Quantity,
	)
	return i, err
}

const getPurchaseOrder = `-- name: GetPurchaseOrder :one
SELECT id, tenant_id, number, date, supplier_id, status, currency_id, total, notes, user_id, created_at
FROM erp_purchase_orders WHERE id = $1 AND tenant_id = $2
`

type GetPurchaseOrderParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) GetPurchaseOrder(ctx context.Context, arg GetPurchaseOrderParams) (ErpPurchaseOrder, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrder, arg.ID, arg.TenantID)
	var i ErpPurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Number,
		&i.Date,
		&i.SupplierID,
		&i.Status,
		&i.CurrencyID,
		&i.Total,
		&i.Notes,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const listPurchaseOrderLines = `-- name: ListPurchaseOrderLines :many
SELECT pol.id, pol.tenant_id, pol.order_id, pol.article_id, pol.quantity,
       pol.unit_price, pol.received_qty, pol.sort_order,
       a.code AS article_code, a.name AS article_name
FROM erp_purchase_order_lines pol
JOIN erp_articles a ON a.id = pol.article_id
WHERE pol.order_id = $1 AND pol.tenant_id = $2
ORDER BY pol.sort_order
`

type ListPurchaseOrderLinesParams struct {
	OrderID  pgtype.UUID `json:"order_id"`
	TenantID string      `json:"tenant_id"`
}

type ListPurchaseOrderLinesRow struct {
	ID          pgtype.UUID    `json:"id"`
	TenantID    string         `json:"tenant_id"`
	OrderID     pgtype.UUID    `json:"order_id"`
	ArticleID   pgtype.UUID    `json:"article_id"`
	Quantity    pgtype.Numeric `json:"quantity"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	ReceivedQty pgtype.Numeric `json:"received_qty"`
	SortOrder   int32          `json:"sort_order"`
	ArticleCode string         `json:"article_code"`
	ArticleName string         `json:"article_name"`
}

func (q *Queries) ListPurchaseOrderLines(ctx context.Context, arg ListPurchaseOrderLinesParams) ([]ListPurchaseOrderLinesRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrderLines, arg.OrderID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchaseOrderLinesRow{}
	for rows.Next() {
		var i ListPurchaseOrderLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrderID,
			&i.ArticleID,
			&i.Quantity,
			&i.UnitPrice,
			&i.ReceivedQty,
			&i.SortOrder,
			&i.ArticleCode,
			&i.ArticleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrders = `-- name: ListPurchaseOrders :many
SELECT po.id, po.tenant_id, po.number, po.date, po.supplier_id, po.status,
       po.currency_id, po.total, po.notes, po.user_id, po.created_at,
       e.name AS supplier_name
FROM erp_purchase_orders po
JOIN erp_entities e ON e.id = po.supplier_id
WHERE po.tenant_id = $1
  AND ($4::TEXT = '' OR po.status = $4::TEXT)
ORDER BY po.date DESC, po.number DESC
LIMIT $2 OFFSET $3
`

type ListPurchaseOrdersParams struct {
	TenantID     string `json:"tenant_id"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
	StatusFilter string `json:"status_filter"`
}

type ListPurchaseOrdersRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     string             `json:"tenant_id"`
	Number       string             `json:"number"`
	Date         pgtype.Date        `json:"date"`
	SupplierID   pgtype.UUID        `json:"supplier_id"`
	Status       string             `json:"status"`
	CurrencyID   pgtype.UUID        `json:"currency_id"`
	Total        pgtype.Numeric     `json:"total"`
	Notes        string             `json:"notes"`
	UserID       string             `json:"user_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	SupplierName string             `json:"supplier_name"`
}

func (q *Queries) ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]ListPurchaseOrdersRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrders,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchaseOrdersRow{}
	for rows.Next() {
		var i ListPurchaseOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Number,
			&i.Date,
			&i.SupplierID,
			&i.Status,
			&i.CurrencyID,
			&i.Total,
			&i.Notes,
			&i.UserID,
			&i.CreatedAt,
			&i.SupplierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseReceipts = `-- name: ListPurchaseReceipts :many
SELECT pr.id, pr.tenant_id, pr.order_id, pr.date, pr.number, pr.user_id, pr.notes, pr.created_at,
       po.number AS order_number
FROM erp_purchase_receipts pr
JOIN erp_purchase_orders po ON po.id = pr.order_id
WHERE pr.tenant_id = $1
ORDER BY pr.date DESC
LIMIT $2 OFFSET $3
`

type ListPurchaseReceiptsParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

type ListPurchaseReceiptsRow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    string             `json:"tenant_id"`
	OrderID     pgtype.UUID        `json:"order_id"`
	Date        pgtype.Date        `json:"date"`
	Number      string             `json:"number"`
	UserID      string             `json:"user_id"`
	Notes       string             `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	OrderNumber string             `json:"order_number"`
}

func (q *Queries) ListPurchaseReceipts(ctx context.Context, arg ListPurchaseReceiptsParams) ([]ListPurchaseReceiptsRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseReceipts, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchaseReceiptsRow{}
	for rows.Next() {
		var i ListPurchaseReceiptsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrderID,
			&i.Date,
			&i.Number,
			&i.UserID,
			&i.Notes,
			&i.CreatedAt,
			&i.OrderNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReceivedQty = `-- name: UpdateReceivedQty :exec
UPDATE erp_purchase_order_lines SET received_qty = received_qty + $3
WHERE id = $1 AND tenant_id = $2
`

type UpdateReceivedQtyParams struct {
	ID          pgtype.UUID    `json:"id"`
	TenantID    string         `json:"tenant_id"`
	ReceivedQty pgtype.Numeric `json:"received_qty"`
}

func (q *Queries) UpdateReceivedQty(ctx context.Context, arg UpdateReceivedQtyParams) error {
	_, err := q.db.Exec(ctx, updateReceivedQty, arg.ID, arg.TenantID, arg.ReceivedQty)
	return err
}
