// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sales.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO erp_orders (tenant_id, number, date, order_type, customer_id, quotation_id, total, user_id, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, number, date, order_type, customer_id, quotation_id, status, total, user_id, notes, created_at
`

type CreateOrderParams struct {
	TenantID    string         `json:"tenant_id"`
	Number      string         `json:"number"`
	Date        pgtype.Date    `json:"date"`
	OrderType   string         `json:"order_type"`
	CustomerID  pgtype.UUID    `json:"customer_id"`
	QuotationID pgtype.UUID    `json:"quotation_id"`
	Total       pgtype.Numeric `json:"total"`
	UserID      string         `json:"user_id"`
	Notes       string         `json:"notes"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (ErpOrder, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.TenantID,
		arg.Number,
		arg.Date,
		arg.OrderType,
		arg.CustomerID,
		arg.QuotationID,
		arg.Total,
		arg.UserID,
		arg.Notes,
	)
	var i ErpOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Number,
		&i.Date,
		&i.OrderType,
		&i.CustomerID,
		&i.QuotationID,
		&i.Status,
		&i.Total,
		&i.UserID,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createPriceList = `-- name: CreatePriceList :one
INSERT INTO erp_price_lists (tenant_id, name, currency_id, valid_from, valid_until)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, currency_id, valid_from, valid_until, active
`

type CreatePriceListParams struct {
	TenantID   string      `json:"tenant_id"`
	Name       string      `json:"name"`
	CurrencyID pgtype.UUID `json:"currency_id"`
	ValidFrom  pgtype.Date `json:"valid_from"`
	ValidUntil pgtype.Date `json:"valid_until"`
}

func (q *Queries) CreatePriceList(ctx context.Context, arg CreatePriceListParams) (ErpPriceList, error) {
	row := q.db.QueryRow(ctx, createPriceList,
		arg.TenantID,
		arg.Name,
		arg.CurrencyID,
		arg.ValidFrom,
		arg.ValidUntil,
	)
	var i ErpPriceList
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CurrencyID,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Active,
	)
	return i, err
}

const createPriceListItem = `-- name: CreatePriceListItem :one
INSERT INTO erp_price_list_items (tenant_id, price_list_id, article_id, description, price)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, price_list_id, article_id, description, price
`

type CreatePriceListItemParams struct {
	TenantID    string         `json:"tenant_id"`
	PriceListID pgtype.UUID    `json:"price_list_id"`
	ArticleID   pgtype.UUID    `json:"article_id"`
	Description pgtype.Text    `json:"description"`
	Price       pgtype.Numeric `json:"price"`
}

func (q *Queries) CreatePriceListItem(ctx context.Context, arg CreatePriceListItemParams) (ErpPriceListItem, error) {
	row := q.db.QueryRow(ctx, createPriceListItem,
		arg.TenantID,
		arg.PriceListID,
		arg.ArticleID,
		arg.Description,
		arg.Price,
	)
	var i ErpPriceListItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PriceListID,
		&i.ArticleID,
		&i.Description,
		&i.Price,
	)
	return i, err
}

const createQuotation = `-- name: CreateQuotation :one
INSERT INTO erp_quotations (tenant_id, number, date, customer_id, currency_id, total, valid_until, notes, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, number, date, customer_id, status, currency_id, total, valid_until, notes, user_id, created_at
`

type CreateQuotationParams struct {
	TenantID   string         `json:"tenant_id"`
	Number     string         `json:"number"`
	Date       pgtype.Date    `json:"date"`
	CustomerID pgtype.UUID    `json:"customer_id"`
	CurrencyID pgtype.UUID    `json:"currency_id"`
	Total      pgtype.Numeric `json:"total"`
	ValidUntil pgtype.Date    `json:"valid_until"`
	Notes      string         `json:"notes"`
	UserID     string         `json:"user_id"`
}

func (q *Queries) CreateQuotation(ctx context.Context, arg CreateQuotationParams) (ErpQuotation, error) {
	row := q.db.QueryRow(ctx, createQuotation,
		arg.TenantID,
		arg.Number,
		arg.Date,
		arg.CustomerID,
		arg.CurrencyID,
		arg.Total,
		arg.ValidUntil,
		arg.Notes,
		arg.UserID,
	)
	var i ErpQuotation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Number,
		&i.Date,
		&i.CustomerID,
		&i.Status,
		&i.CurrencyID,
		&i.Total,
		&i.ValidUntil,
		&i.Notes,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const createQuotationLine = `-- name: CreateQuotationLine :one
INSERT INTO erp_quotation_lines (tenant_id, quotation_id, article_id, description, quantity, unit_price, sort_order, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, quotation_id, article_id, description, quantity, unit_price, sort_order, metadata
`

type CreateQuotationLineParams struct {
	TenantID    string         `json:"tenant_id"`
	QuotationID pgtype.UUID    `json:"quotation_id"`
	ArticleID   pgtype.UUID    `json:"article_id"`
	Description string         `json:"description"`
	Quantity    pgtype.Numeric `json:"quantity"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	SortOrder   int32          `json:"sort_order"`
	Metadata    []byte         `json:"metadata"`
}

func (q *Queries) CreateQuotationLine(ctx context.Context, arg CreateQuotationLineParams) (ErpQuotationLine, error) {
	row := q.db.QueryRow(ctx, createQuotationLine,
		arg.TenantID,
		arg.QuotationID,
		arg.ArticleID,
		arg.Description,
		arg.Quantity,
		arg.UnitPrice,
		arg.SortOrder,
		arg.Metadata,
	)
	var i ErpQuotationLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.QuotationID,
		&i.ArticleID,
		&i.Description,
		&i.Quantity,
		&i.UnitPrice,
		&i.SortOrder,
		&i.Metadata,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, tenant_id, number, date, order_type, customer_id, quotation_id,
       status, total, user_id, notes, created_at
FROM erp_orders WHERE id = $1 AND tenant_id = $2
`

type GetOrderParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (ErpOrder, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.ID, arg.TenantID)
	var i ErpOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Number,
		&i.Date,
		&i.OrderType,
		&i.CustomerID,
		&i.QuotationID,
		&i.Status,
		&i.Total,
		&i.UserID,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getQuotation = `-- name: GetQuotation :one
SELECT id, tenant_id, number, date, customer_id, status, currency_id, total,
       valid_until, notes, user_id, created_at
FROM erp_quotations WHERE id = $1 AND tenant_id = $2
`

type GetQuotationParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) GetQuotation(ctx context.Context, arg GetQuotationParams) (ErpQuotation, error) {
	row := q.db.QueryRow(ctx, getQuotation, arg.ID, arg.TenantID)
	var i ErpQuotation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Number,
		&i.Date,
		&i.CustomerID,
		&i.Status,
		&i.CurrencyID,
		&i.Total,
		&i.ValidUntil,
		&i.Notes,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT o.id, o.tenant_id, o.number, o.date, o.order_type, o.customer_id,
       o.quotation_id, o.status, o.total, o.user_id, o.notes, o.created_at,
       e.name AS customer_name
FROM erp_orders o
LEFT JOIN erp_entities e ON e.id = o.customer_id
WHERE o.tenant_id = $1
  AND ($4::TEXT = '' OR o.status = $4::TEXT)
  AND ($5::TEXT = '' OR o.order_type = $5::TEXT)
ORDER BY o.date DESC
LIMIT $2 OFFSET $3
`

type ListOrdersParams struct {
	TenantID     string `json:"tenant_id"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
	StatusFilter string `json:"status_filter"`
	TypeFilter   string `json:"type_filter"`
}

type ListOrdersRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     string             `json:"tenant_id"`
	Number       string             `json:"number"`
	Date         pgtype.Date        `json:"date"`
	OrderType    string             `json:"order_type"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	QuotationID  pgtype.UUID        `json:"quotation_id"`
	Status       string             `json:"status"`
	Total        pgtype.Numeric     `json:"total"`
	UserID       string             `json:"user_id"`
	Notes        string             `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CustomerName pgtype.Text        `json:"customer_name"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.StatusFilter,
		arg.TypeFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersRow{}
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Number,
			&i.Date,
			&i.OrderType,
			&i.CustomerID,
			&i.QuotationID,
			&i.Status,
			&i.Total,
			&i.UserID,
			&i.Notes,
			&i.CreatedAt,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceListItems = `-- name: ListPriceListItems :many
SELECT pli.id, pli.tenant_id, pli.price_list_id, pli.article_id, pli.description, pli.price,
       a.code AS article_code, a.name AS article_name
FROM erp_price_list_items pli
LEFT JOIN erp_articles a ON a.id = pli.article_id
WHERE pli.price_list_id = $1 AND pli.tenant_id = $2
ORDER BY a.code, pli.description
`

type ListPriceListItemsParams struct {
	PriceListID pgtype.UUID `json:"price_list_id"`
	TenantID    string      `json:"tenant_id"`
}

type ListPriceListItemsRow struct {
	ID          pgtype.UUID    `json:"id"`
	TenantID    string         `json:"tenant_id"`
	PriceListID pgtype.UUID    `json:"price_list_id"`
	ArticleID   pgtype.UUID    `json:"article_id"`
	Description pgtype.Text    `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	ArticleCode pgtype.Text    `json:"article_code"`
	ArticleName pgtype.Text    `json:"article_name"`
}

func (q *Queries) ListPriceListItems(ctx context.Context, arg ListPriceListItemsParams) ([]ListPriceListItemsRow, error) {
	rows, err := q.db.Query(ctx, listPriceListItems, arg.PriceListID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPriceListItemsRow{}
	for rows.Next() {
		var i ListPriceListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PriceListID,
			&i.ArticleID,
			&i.Description,
			&i.Price,
			&i.ArticleCode,
			&i.ArticleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceLists = `-- name: ListPriceLists :many
SELECT id, tenant_id, name, currency_id, valid_from, valid_until, active
FROM erp_price_lists WHERE tenant_id = $1 ORDER BY name
`

func (q *Queries) ListPriceLists(ctx context.Context, tenantID string) ([]ErpPriceList, error) {
	rows, err := q.db.Query(ctx, listPriceLists, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpPriceList{}
	for rows.Next() {
		var i ErpPriceList
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.CurrencyID,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotationLines = `-- name: ListQuotationLines :many
SELECT ql.id, ql.tenant_id, ql.quotation_id, ql.article_id, ql.description,
       ql.quantity, ql.unit_price, ql.sort_order, ql.metadata
FROM erp_quotation_lines ql
WHERE ql.quotation_id = $1 AND ql.tenant_id = $2
ORDER BY ql.sort_order
`

type ListQuotationLinesParams struct {
	QuotationID pgtype.UUID `json:"quotation_id"`
	TenantID    string      `json:"tenant_id"`
}

func (q *Queries) ListQuotationLines(ctx context.Context, arg ListQuotationLinesParams) ([]ErpQuotationLine, error) {
	rows, err := q.db.Query(ctx, listQuotationLines, arg.QuotationID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpQuotationLine{}
	for rows.Next() {
		var i ErpQuotationLine
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.QuotationID,
			&i.ArticleID,
			&i.Description,
			&i.Quantity,
			&i.UnitPrice,
			&i.SortOrder,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotations = `-- name: ListQuotations :many
SELECT q.id, q.tenant_id, q.number, q.date, q.customer_id, q.status,
       q.currency_id, q.total, q.valid_until, q.notes, q.user_id, q.created_at,
       e.name AS customer_name
FROM erp_quotations q
JOIN erp_entities e ON e.id = q.customer_id
WHERE q.tenant_id = $1
  AND ($4::TEXT = '' OR q.status = $4::TEXT)
ORDER BY q.date DESC
LIMIT $2 OFFSET $3
`

type ListQuotationsParams struct {
	TenantID     string `json:"tenant_id"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
	StatusFilter string `json:"status_filter"`
}

type ListQuotationsRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     string             `json:"tenant_id"`
	Number       string             `json:"number"`
	Date         pgtype.Date        `json:"date"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	Status       string             `json:"status"`
	CurrencyID   pgtype.UUID        `json:"currency_id"`
	Total        pgtype.Numeric     `json:"total"`
	ValidUntil   pgtype.Date        `json:"valid_until"`
	Notes        string             `json:"notes"`
	UserID       string             `json:"user_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CustomerName string             `json:"customer_name"`
}

func (q *Queries) ListQuotations(ctx context.Context, arg ListQuotationsParams) ([]ListQuotationsRow, error) {
	rows, err := q.db.Query(ctx, listQuotations,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuotationsRow{}
	for rows.Next() {
		var i ListQuotationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Number,
			&i.Date,
			&i.CustomerID,
			&i.Status,
			&i.CurrencyID,
			&i.Total,
			&i.ValidUntil,
			&i.Notes,
			&i.UserID,
			&i.CreatedAt,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :execrows
UPDATE erp_orders SET status = $3 WHERE id = $1 AND tenant_id = $2
`

type UpdateOrderStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.TenantID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateQuotationStatus = `-- name: UpdateQuotationStatus :execrows
UPDATE erp_quotations SET status = $3 WHERE id = $1 AND tenant_id = $2
`

type UpdateQuotationStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateQuotationStatus(ctx context.Context, arg UpdateQuotationStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateQuotationStatus, arg.ID, arg.TenantID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listQuotationOptions = `-- name: ListQuotationOptions :many
SELECT id, tenant_id, legacy_id,
       quotation_id, quotation_legacy_id,
       section_legacy_id, description, created_at
FROM erp_quotation_section_items
WHERE tenant_id = $1 AND quotation_id = $2
ORDER BY section_legacy_id, legacy_id
LIMIT $3 OFFSET $4
`

type ListQuotationOptionsParams struct {
	TenantID    string      `json:"tenant_id"`
	QuotationID pgtype.UUID `json:"quotation_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

// Free-text option lines per quotation section.
func (q *Queries) ListQuotationOptions(ctx context.Context, arg ListQuotationOptionsParams) ([]ErpQuotationSectionItem, error) {
	rows, err := q.db.Query(ctx, listQuotationOptions,
		arg.TenantID, arg.QuotationID, arg.Limit, arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpQuotationSectionItem{}
	for rows.Next() {
		var i ErpQuotationSectionItem
		if err := rows.Scan(
			&i.ID, &i.TenantID, &i.LegacyID,
			&i.QuotationID, &i.QuotationLegacyID,
			&i.SectionLegacyID, &i.Description, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
