// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO erp_articles (tenant_id, code, name, family_id, category_id, unit_id, article_type,
    min_stock, max_stock, reorder_point, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, tenant_id, code, name, family_id, category_id, unit_id, article_type,
    min_stock, max_stock, reorder_point, last_cost, avg_cost, metadata, active, created_at, updated_at
`

type CreateArticleParams struct {
	TenantID     string         `json:"tenant_id"`
	Code         string         `json:"code"`
	Name         string         `json:"name"`
	FamilyID     pgtype.UUID    `json:"family_id"`
	CategoryID   pgtype.UUID    `json:"category_id"`
	UnitID       pgtype.UUID    `json:"unit_id"`
	ArticleType  string         `json:"article_type"`
	MinStock     pgtype.Numeric `json:"min_stock"`
	MaxStock     pgtype.Numeric `json:"max_stock"`
	ReorderPoint pgtype.Numeric `json:"reorder_point"`
	Metadata     []byte         `json:"metadata"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (ErpArticle, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.FamilyID,
		arg.CategoryID,
		arg.UnitID,
		arg.ArticleType,
		arg.MinStock,
		arg.MaxStock,
		arg.ReorderPoint,
		arg.Metadata,
	)
	var i ErpArticle
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.FamilyID,
		&i.CategoryID,
		&i.UnitID,
		&i.ArticleType,
		&i.MinStock,
		&i.MaxStock,
		&i.ReorderPoint,
		&i.LastCost,
		&i.AvgCost,
		&i.Metadata,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBOMEntry = `-- name: CreateBOMEntry :one
INSERT INTO erp_bom (tenant_id, parent_id, child_id, quantity, unit_id, sort_order, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, parent_id, child_id, quantity, unit_id, sort_order, notes
`

type CreateBOMEntryParams struct {
	TenantID  string         `json:"tenant_id"`
	ParentID  pgtype.UUID    `json:"parent_id"`
	ChildID   pgtype.UUID    `json:"child_id"`
	Quantity  pgtype.Numeric `json:"quantity"`
	UnitID    pgtype.UUID    `json:"unit_id"`
	SortOrder int32          `json:"sort_order"`
	Notes     string         `json:"notes"`
}

func (q *Queries) CreateBOMEntry(ctx context.Context, arg CreateBOMEntryParams) (ErpBom, error) {
	row := q.db.QueryRow(ctx, createBOMEntry,
		arg.TenantID,
		arg.ParentID,
		arg.ChildID,
		arg.Quantity,
		arg.UnitID,
		arg.SortOrder,
		arg.Notes,
	)
	var i ErpBom
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.ChildID,
		&i.Quantity,
		&i.UnitID,
		&i.SortOrder,
		&i.Notes,
	)
	return i, err
}

const createStockMovement = `-- name: CreateStockMovement :one
INSERT INTO erp_stock_movements (tenant_id, article_id, warehouse_id, movement_type, quantity, unit_cost,
    reference_type, reference_id, concept_id, user_id, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, tenant_id, article_id, warehouse_id, movement_type, quantity, unit_cost,
    reference_type, reference_id, concept_id, user_id, notes, created_at
`

type CreateStockMovementParams struct {
	TenantID      string         `json:"tenant_id"`
	ArticleID     pgtype.UUID    `json:"article_id"`
	WarehouseID   pgtype.UUID    `json:"warehouse_id"`
	MovementType  string         `json:"movement_type"`
	Quantity      pgtype.Numeric `json:"quantity"`
	UnitCost      pgtype.Numeric `json:"unit_cost"`
	ReferenceType pgtype.Text    `json:"reference_type"`
	ReferenceID   pgtype.UUID    `json:"reference_id"`
	ConceptID     pgtype.UUID    `json:"concept_id"`
	UserID        string         `json:"user_id"`
	Notes         string         `json:"notes"`
}

func (q *Queries) CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (ErpStockMovement, error) {
	row := q.db.QueryRow(ctx, createStockMovement,
		arg.TenantID,
		arg.ArticleID,
		arg.WarehouseID,
		arg.MovementType,
		arg.Quantity,
		arg.UnitCost,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.ConceptID,
		arg.UserID,
		arg.Notes,
	)
	var i ErpStockMovement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ArticleID,
		&i.WarehouseID,
		&i.MovementType,
		&i.Quantity,
		&i.UnitCost,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.ConceptID,
		&i.UserID,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createWarehouse = `-- name: CreateWarehouse :one
INSERT INTO erp_warehouses (tenant_id, code, name, location)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, code, name, location, active
`

type CreateWarehouseParams struct {
	TenantID string `json:"tenant_id"`
	Code     string `json:"code"`
	Name     string `json:"name"`
	Location string `json:"location"`
}

func (q *Queries) CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (ErpWarehouse, error) {
	row := q.db.QueryRow(ctx, createWarehouse,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Location,
	)
	var i ErpWarehouse
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Location,
		&i.Active,
	)
	return i, err
}

const deleteBOMEntry = `-- name: DeleteBOMEntry :exec
DELETE FROM erp_bom WHERE id = $1 AND tenant_id = $2
`

type DeleteBOMEntryParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) DeleteBOMEntry(ctx context.Context, arg DeleteBOMEntryParams) error {
	_, err := q.db.Exec(ctx, deleteBOMEntry, arg.ID, arg.TenantID)
	return err
}

const getArticle = `-- name: GetArticle :one
SELECT id, tenant_id, code, name, family_id, category_id, unit_id, article_type,
       min_stock, max_stock, reorder_point, last_cost, avg_cost, metadata, active, created_at, updated_at
FROM erp_articles WHERE id = $1 AND tenant_id = $2
`

type GetArticleParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) GetArticle(ctx context.Context, arg GetArticleParams) (ErpArticle, error) {
	row := q.db.QueryRow(ctx, getArticle, arg.ID, arg.TenantID)
	var i ErpArticle
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.FamilyID,
		&i.CategoryID,
		&i.UnitID,
		&i.ArticleType,
		&i.MinStock,
		&i.MaxStock,
		&i.ReorderPoint,
		&i.LastCost,
		&i.AvgCost,
		&i.Metadata,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStockLevels = `-- name: GetStockLevels :many
SELECT sl.id, sl.tenant_id, sl.article_id, sl.warehouse_id, sl.quantity, sl.reserved, sl.updated_at,
       a.code AS article_code, a.name AS article_name, w.code AS warehouse_code, w.name AS warehouse_name
FROM erp_stock_levels sl
JOIN erp_articles a ON a.id = sl.article_id
JOIN erp_warehouses w ON w.id = sl.warehouse_id
WHERE sl.tenant_id = $1
  AND ($2::UUID IS NULL OR sl.article_id = $2::UUID)
  AND ($3::UUID IS NULL OR sl.warehouse_id = $3::UUID)
ORDER BY a.code, w.code
`

type GetStockLevelsParams struct {
	TenantID        string      `json:"tenant_id"`
	ArticleFilter   pgtype.UUID `json:"article_filter"`
	WarehouseFilter pgtype.UUID `json:"warehouse_filter"`
}

type GetStockLevelsRow struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      string             `json:"tenant_id"`
	ArticleID     pgtype.UUID        `json:"article_id"`
	WarehouseID   pgtype.UUID        `json:"warehouse_id"`
	Quantity      pgtype.Numeric     `json:"quantity"`
	Reserved      pgtype.Numeric     `json:"reserved"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ArticleCode   string             `json:"article_code"`
	ArticleName   string             `json:"article_name"`
	WarehouseCode string             `json:"warehouse_code"`
	WarehouseName string             `json:"warehouse_name"`
}

func (q *Queries) GetStockLevels(ctx context.Context, arg GetStockLevelsParams) ([]GetStockLevelsRow, error) {
	rows, err := q.db.Query(ctx, getStockLevels, arg.TenantID, arg.ArticleFilter, arg.WarehouseFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStockLevelsRow{}
	for rows.Next() {
		var i GetStockLevelsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ArticleID,
			&i.WarehouseID,
			&i.Quantity,
			&i.Reserved,
			&i.UpdatedAt,
			&i.ArticleCode,
			&i.ArticleName,
			&i.WarehouseCode,
			&i.WarehouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticles = `-- name: ListArticles :many
SELECT id, tenant_id, code, name, family_id, category_id, unit_id, article_type,
       min_stock, max_stock, reorder_point, last_cost, avg_cost, metadata, active, created_at, updated_at
FROM erp_articles
WHERE tenant_id = $1
  AND ($4::BOOLEAN = false OR active = true)
  AND ($5::TEXT = '' OR name ILIKE '%' || $5::TEXT || '%'
       OR code ILIKE '%' || $5::TEXT || '%')
  AND ($6::TEXT = '' OR article_type = $6::TEXT)
ORDER BY code
LIMIT $2 OFFSET $3
`

type ListArticlesParams struct {
	TenantID          string `json:"tenant_id"`
	Limit             int32  `json:"limit"`
	Offset            int32  `json:"offset"`
	ActiveOnly        bool   `json:"active_only"`
	Search            string `json:"search"`
	ArticleTypeFilter string `json:"article_type_filter"`
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]ErpArticle, error) {
	rows, err := q.db.Query(ctx, listArticles,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.ActiveOnly,
		arg.Search,
		arg.ArticleTypeFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpArticle{}
	for rows.Next() {
		var i ErpArticle
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.FamilyID,
			&i.CategoryID,
			&i.UnitID,
			&i.ArticleType,
			&i.MinStock,
			&i.MaxStock,
			&i.ReorderPoint,
			&i.LastCost,
			&i.AvgCost,
			&i.Metadata,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBOM = `-- name: ListBOM :many
SELECT b.id, b.tenant_id, b.parent_id, b.child_id, b.quantity, b.unit_id, b.sort_order, b.notes,
       a.code AS child_code, a.name AS child_name
FROM erp_bom b
JOIN erp_articles a ON a.id = b.child_id
WHERE b.tenant_id = $1 AND b.parent_id = $2
ORDER BY b.sort_order, a.name
`

type ListBOMParams struct {
	TenantID string      `json:"tenant_id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

type ListBOMRow struct {
	ID        pgtype.UUID    `json:"id"`
	TenantID  string         `json:"tenant_id"`
	ParentID  pgtype.UUID    `json:"parent_id"`
	ChildID   pgtype.UUID    `json:"child_id"`
	Quantity  pgtype.Numeric `json:"quantity"`
	UnitID    pgtype.UUID    `json:"unit_id"`
	SortOrder int32          `json:"sort_order"`
	Notes     string         `json:"notes"`
	ChildCode string         `json:"child_code"`
	ChildName string         `json:"child_name"`
}

func (q *Queries) ListBOM(ctx context.Context, arg ListBOMParams) ([]ListBOMRow, error) {
	rows, err := q.db.Query(ctx, listBOM, arg.TenantID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBOMRow{}
	for rows.Next() {
		var i ListBOMRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ParentID,
			&i.ChildID,
			&i.Quantity,
			&i.UnitID,
			&i.SortOrder,
			&i.Notes,
			&i.ChildCode,
			&i.ChildName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMovements = `-- name: ListStockMovements :many
SELECT sm.id, sm.tenant_id, sm.article_id, sm.warehouse_id, sm.movement_type, sm.quantity,
       sm.unit_cost, sm.reference_type, sm.reference_id, sm.concept_id, sm.user_id, sm.notes, sm.created_at,
       a.code AS article_code, a.name AS article_name
FROM erp_stock_movements sm
JOIN erp_articles a ON a.id = sm.article_id
WHERE sm.tenant_id = $1
  AND ($4::UUID IS NULL OR sm.article_id = $4::UUID)
ORDER BY sm.created_at DESC
LIMIT $2 OFFSET $3
`

type ListStockMovementsParams struct {
	TenantID      string      `json:"tenant_id"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
	ArticleFilter pgtype.UUID `json:"article_filter"`
}

type ListStockMovementsRow struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      string             `json:"tenant_id"`
	ArticleID     pgtype.UUID        `json:"article_id"`
	WarehouseID   pgtype.UUID        `json:"warehouse_id"`
	MovementType  string             `json:"movement_type"`
	Quantity      pgtype.Numeric     `json:"quantity"`
	UnitCost      pgtype.Numeric     `json:"unit_cost"`
	ReferenceType pgtype.Text        `json:"reference_type"`
	ReferenceID   pgtype.UUID        `json:"reference_id"`
	ConceptID     pgtype.UUID        `json:"concept_id"`
	UserID        string             `json:"user_id"`
	Notes         string             `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ArticleCode   string             `json:"article_code"`
	ArticleName   string             `json:"article_name"`
}

func (q *Queries) ListStockMovements(ctx context.Context, arg ListStockMovementsParams) ([]ListStockMovementsRow, error) {
	rows, err := q.db.Query(ctx, listStockMovements,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.ArticleFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockMovementsRow{}
	for rows.Next() {
		var i ListStockMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ArticleID,
			&i.WarehouseID,
			&i.MovementType,
			&i.Quantity,
			&i.UnitCost,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.ConceptID,
			&i.UserID,
			&i.Notes,
			&i.CreatedAt,
			&i.ArticleCode,
			&i.ArticleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMovementsByRef = `-- name: ListStockMovementsByRef :many
SELECT id, tenant_id, article_id, warehouse_id, movement_type, quantity, unit_cost,
       reference_type, reference_id
FROM erp_stock_movements
WHERE tenant_id = $1 AND reference_type = $2 AND reference_id = $3
`

type ListStockMovementsByRefParams struct {
	TenantID      string      `json:"tenant_id"`
	ReferenceType pgtype.Text `json:"reference_type"`
	ReferenceID   pgtype.UUID `json:"reference_id"`
}

type ListStockMovementsByRefRow struct {
	ID            pgtype.UUID    `json:"id"`
	TenantID      string         `json:"tenant_id"`
	ArticleID     pgtype.UUID    `json:"article_id"`
	WarehouseID   pgtype.UUID    `json:"warehouse_id"`
	MovementType  string         `json:"movement_type"`
	Quantity      pgtype.Numeric `json:"quantity"`
	UnitCost      pgtype.Numeric `json:"unit_cost"`
	ReferenceType pgtype.Text    `json:"reference_type"`
	ReferenceID   pgtype.UUID    `json:"reference_id"`
}

func (q *Queries) ListStockMovementsByRef(ctx context.Context, arg ListStockMovementsByRefParams) ([]ListStockMovementsByRefRow, error) {
	rows, err := q.db.Query(ctx, listStockMovementsByRef, arg.TenantID, arg.ReferenceType, arg.ReferenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockMovementsByRefRow{}
	for rows.Next() {
		var i ListStockMovementsByRefRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ArticleID,
			&i.WarehouseID,
			&i.MovementType,
			&i.Quantity,
			&i.UnitCost,
			&i.ReferenceType,
			&i.ReferenceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarehouses = `-- name: ListWarehouses :many
SELECT id, tenant_id, code, name, location, active
FROM erp_warehouses WHERE tenant_id = $1 AND ($2::BOOLEAN = false OR active = true)
ORDER BY code
`

type ListWarehousesParams struct {
	TenantID   string `json:"tenant_id"`
	ActiveOnly bool   `json:"active_only"`
}

func (q *Queries) ListWarehouses(ctx context.Context, arg ListWarehousesParams) ([]ErpWarehouse, error) {
	rows, err := q.db.Query(ctx, listWarehouses, arg.TenantID, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpWarehouse{}
	for rows.Next() {
		var i ErpWarehouse
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Location,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE erp_articles
SET code = $3, name = $4, family_id = $5, category_id = $6, unit_id = $7, article_type = $8,
    min_stock = $9, max_stock = $10, reorder_point = $11, metadata = $12, active = $13, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, code, name, family_id, category_id, unit_id, article_type,
    min_stock, max_stock, reorder_point, last_cost, avg_cost, metadata, active, created_at, updated_at
`

type UpdateArticleParams struct {
	ID           pgtype.UUID    `json:"id"`
	TenantID     string         `json:"tenant_id"`
	Code         string         `json:"code"`
	Name         string         `json:"name"`
	FamilyID     pgtype.UUID    `json:"family_id"`
	CategoryID   pgtype.UUID    `json:"category_id"`
	UnitID       pgtype.UUID    `json:"unit_id"`
	ArticleType  string         `json:"article_type"`
	MinStock     pgtype.Numeric `json:"min_stock"`
	MaxStock     pgtype.Numeric `json:"max_stock"`
	ReorderPoint pgtype.Numeric `json:"reorder_point"`
	Metadata     []byte         `json:"metadata"`
	Active       bool           `json:"active"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (ErpArticle, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.ID,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.FamilyID,
		arg.CategoryID,
		arg.UnitID,
		arg.ArticleType,
		arg.MinStock,
		arg.MaxStock,
		arg.ReorderPoint,
		arg.Metadata,
		arg.Active,
	)
	var i ErpArticle
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.FamilyID,
		&i.CategoryID,
		&i.UnitID,
		&i.ArticleType,
		&i.MinStock,
		&i.MaxStock,
		&i.ReorderPoint,
		&i.LastCost,
		&i.AvgCost,
		&i.Metadata,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStockLevel = `-- name: UpsertStockLevel :exec
INSERT INTO erp_stock_levels (tenant_id, article_id, warehouse_id, quantity, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (tenant_id, article_id, warehouse_id)
DO UPDATE SET quantity = erp_stock_levels.quantity + $4, updated_at = now()
`

type UpsertStockLevelParams struct {
	TenantID    string         `json:"tenant_id"`
	ArticleID   pgtype.UUID    `json:"article_id"`
	WarehouseID pgtype.UUID    `json:"warehouse_id"`
	Quantity    pgtype.Numeric `json:"quantity"`
}

func (q *Queries) UpsertStockLevel(ctx context.Context, arg UpsertStockLevelParams) error {
	_, err := q.db.Exec(ctx, upsertStockLevel,
		arg.TenantID,
		arg.ArticleID,
		arg.WarehouseID,
		arg.Quantity,
	)
	return err
}

const listArticleCosts = `-- name: ListArticleCosts :many
SELECT id, tenant_id, legacy_id, article_code, article_id, subsystem_code,
       cost, percentage_1, percentage_2, percentage_3,
       supplier_article_code, supplier_code, supplier_entity_id,
       invoice_date, last_update_date,
       movement_no, movement_post, movement_date, recalc_flag, created_at
FROM erp_article_costs
WHERE tenant_id = $1 AND article_id = $2
ORDER BY last_update_date DESC NULLS LAST, supplier_code
LIMIT $3 OFFSET $4
`

type ListArticleCostsParams struct {
	TenantID  string      `json:"tenant_id"`
	ArticleID pgtype.UUID `json:"article_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

// Per-supplier cost ledger for a single article. The migrated STKINSPR
// rows carry one entry per (article, supplier) pair with the last update
// date.
func (q *Queries) ListArticleCosts(ctx context.Context, arg ListArticleCostsParams) ([]ErpArticleCost, error) {
	rows, err := q.db.Query(ctx, listArticleCosts,
		arg.TenantID,
		arg.ArticleID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpArticleCost{}
	for rows.Next() {
		var i ErpArticleCost
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LegacyID,
			&i.ArticleCode,
			&i.ArticleID,
			&i.SubsystemCode,
			&i.Cost,
			&i.Percentage1,
			&i.Percentage2,
			&i.Percentage3,
			&i.SupplierArticleCode,
			&i.SupplierCode,
			&i.SupplierEntityID,
			&i.InvoiceDate,
			&i.LastUpdateDate,
			&i.MovementNo,
			&i.MovementPost,
			&i.MovementDate,
			&i.RecalcFlag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticleCostHistory = `-- name: ListArticleCostHistory :many
SELECT id, tenant_id, legacy_id, article_code, article_id,
       year, month, cost, period_code, created_at
FROM erp_article_cost_history
WHERE tenant_id = $1 AND article_id = $2
ORDER BY year DESC, month DESC
LIMIT $3 OFFSET $4
`

type ListArticleCostHistoryParams struct {
	TenantID  string      `json:"tenant_id"`
	ArticleID pgtype.UUID `json:"article_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

// Monthly cost history snapshots per article (STK_COSTO_HIST migrated).
func (q *Queries) ListArticleCostHistory(ctx context.Context, arg ListArticleCostHistoryParams) ([]ErpArticleCostHistory, error) {
	rows, err := q.db.Query(ctx, listArticleCostHistory,
		arg.TenantID, arg.ArticleID, arg.Limit, arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpArticleCostHistory{}
	for rows.Next() {
		var i ErpArticleCostHistory
		if err := rows.Scan(
			&i.ID, &i.TenantID, &i.LegacyID, &i.ArticleCode, &i.ArticleID,
			&i.Year, &i.Month, &i.Cost, &i.PeriodCode, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
