// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: treasury.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBankAccount = `-- name: CreateBankAccount :one
INSERT INTO erp_bank_accounts (tenant_id, bank_name, branch, account_number, cbu, alias, currency_id, account_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, bank_name, branch, account_number, cbu, alias, currency_id, account_id, active, created_at
`

type CreateBankAccountParams struct {
	TenantID      string      `json:"tenant_id"`
	BankName      string      `json:"bank_name"`
	Branch        string      `json:"branch"`
	AccountNumber string      `json:"account_number"`
	Cbu           pgtype.Text `json:"cbu"`
	Alias         pgtype.Text `json:"alias"`
	CurrencyID    pgtype.UUID `json:"currency_id"`
	AccountID     pgtype.UUID `json:"account_id"`
}

func (q *Queries) CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (ErpBankAccount, error) {
	row := q.db.QueryRow(ctx, createBankAccount,
		arg.TenantID,
		arg.BankName,
		arg.Branch,
		arg.AccountNumber,
		arg.Cbu,
		arg.Alias,
		arg.CurrencyID,
		arg.AccountID,
	)
	var i ErpBankAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BankName,
		&i.Branch,
		&i.AccountNumber,
		&i.Cbu,
		&i.Alias,
		&i.CurrencyID,
		&i.AccountID,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const createCashCount = `-- name: CreateCashCount :one
INSERT INTO erp_cash_counts (tenant_id, cash_register_id, date, expected, counted, difference, user_id, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, cash_register_id, date, expected, counted, difference, user_id, notes, created_at
`

type CreateCashCountParams struct {
	TenantID       string         `json:"tenant_id"`
	CashRegisterID pgtype.UUID    `json:"cash_register_id"`
	Date           pgtype.Date    `json:"date"`
	Expected       pgtype.Numeric `json:"expected"`
	Counted        pgtype.Numeric `json:"counted"`
	Difference     pgtype.Numeric `json:"difference"`
	UserID         string         `json:"user_id"`
	Notes          string         `json:"notes"`
}

func (q *Queries) CreateCashCount(ctx context.Context, arg CreateCashCountParams) (ErpCashCount, error) {
	row := q.db.QueryRow(ctx, createCashCount,
		arg.TenantID,
		arg.CashRegisterID,
		arg.Date,
		arg.Expected,
		arg.Counted,
		arg.Difference,
		arg.UserID,
		arg.Notes,
	)
	var i ErpCashCount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CashRegisterID,
		&i.Date,
		&i.Expected,
		&i.Counted,
		&i.Difference,
		&i.UserID,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createCashRegister = `-- name: CreateCashRegister :one
INSERT INTO erp_cash_registers (tenant_id, name, account_id)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, account_id, active, created_at
`

type CreateCashRegisterParams struct {
	TenantID  string      `json:"tenant_id"`
	Name      string      `json:"name"`
	AccountID pgtype.UUID `json:"account_id"`
}

func (q *Queries) CreateCashRegister(ctx context.Context, arg CreateCashRegisterParams) (ErpCashRegister, error) {
	row := q.db.QueryRow(ctx, createCashRegister, arg.TenantID, arg.Name, arg.AccountID)
	var i ErpCashRegister
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.AccountID,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const createCheck = `-- name: CreateCheck :one
INSERT INTO erp_checks (tenant_id, direction, number, bank_name, amount, issue_date, due_date, entity_id, movement_id, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, direction, number, bank_name, amount, issue_date, due_date, entity_id, status, movement_id, notes, created_at
`

type CreateCheckParams struct {
	TenantID   string         `json:"tenant_id"`
	Direction  string         `json:"direction"`
	Number     string         `json:"number"`
	BankName   string         `json:"bank_name"`
	Amount     pgtype.Numeric `json:"amount"`
	IssueDate  pgtype.Date    `json:"issue_date"`
	DueDate    pgtype.Date    `json:"due_date"`
	EntityID   pgtype.UUID    `json:"entity_id"`
	MovementID pgtype.UUID    `json:"movement_id"`
	Notes      string         `json:"notes"`
}

func (q *Queries) CreateCheck(ctx context.Context, arg CreateCheckParams) (ErpCheck, error) {
	row := q.db.QueryRow(ctx, createCheck,
		arg.TenantID,
		arg.Direction,
		arg.Number,
		arg.BankName,
		arg.Amount,
		arg.IssueDate,
		arg.DueDate,
		arg.EntityID,
		arg.MovementID,
		arg.Notes,
	)
	var i ErpCheck
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Direction,
		&i.Number,
		&i.BankName,
		&i.Amount,
		&i.IssueDate,
		&i.DueDate,
		&i.EntityID,
		&i.Status,
		&i.MovementID,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createTreasuryMovement = `-- name: CreateTreasuryMovement :one
INSERT INTO erp_treasury_movements (tenant_id, date, number, movement_type, amount,
    currency_id, bank_account_id, cash_register_id, entity_id, concept_id,
    payment_method, reference_type, reference_id, journal_entry_id, user_id, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, tenant_id, date, number, movement_type, amount, currency_id,
    bank_account_id, cash_register_id, entity_id, concept_id, payment_method,
    reference_type, reference_id, journal_entry_id, user_id, notes, status, created_at
`

type CreateTreasuryMovementParams struct {
	TenantID       string         `json:"tenant_id"`
	Date           pgtype.Date    `json:"date"`
	Number         string         `json:"number"`
	MovementType   string         `json:"movement_type"`
	Amount         pgtype.Numeric `json:"amount"`
	CurrencyID     pgtype.UUID    `json:"currency_id"`
	BankAccountID  pgtype.UUID    `json:"bank_account_id"`
	CashRegisterID pgtype.UUID    `json:"cash_register_id"`
	EntityID       pgtype.UUID    `json:"entity_id"`
	ConceptID      pgtype.UUID    `json:"concept_id"`
	PaymentMethod  pgtype.Text    `json:"payment_method"`
	ReferenceType  pgtype.Text    `json:"reference_type"`
	ReferenceID    pgtype.UUID    `json:"reference_id"`
	JournalEntryID pgtype.UUID    `json:"journal_entry_id"`
	UserID         string         `json:"user_id"`
	Notes          string         `json:"notes"`
}

func (q *Queries) CreateTreasuryMovement(ctx context.Context, arg CreateTreasuryMovementParams) (ErpTreasuryMovement, error) {
	row := q.db.QueryRow(ctx, createTreasuryMovement,
		arg.TenantID,
		arg.Date,
		arg.Number,
		arg.MovementType,
		arg.Amount,
		arg.CurrencyID,
		arg.BankAccountID,
		arg.CashRegisterID,
		arg.EntityID,
		arg.ConceptID,
		arg.PaymentMethod,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.JournalEntryID,
		arg.UserID,
		arg.Notes,
	)
	var i ErpTreasuryMovement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Date,
		&i.Number,
		&i.MovementType,
		&i.Amount,
		&i.CurrencyID,
		&i.BankAccountID,
		&i.CashRegisterID,
		&i.EntityID,
		&i.ConceptID,
		&i.PaymentMethod,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.JournalEntryID,
		&i.UserID,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCheck = `-- name: GetCheck :one
SELECT id, tenant_id, direction, number, bank_name, amount, issue_date, due_date,
       entity_id, status, movement_id, notes, created_at
FROM erp_checks WHERE id = $1 AND tenant_id = $2
`

type GetCheckParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
}

func (q *Queries) GetCheck(ctx context.Context, arg GetCheckParams) (ErpCheck, error) {
	row := q.db.QueryRow(ctx, getCheck, arg.ID, arg.TenantID)
	var i ErpCheck
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Direction,
		&i.Number,
		&i.BankName,
		&i.Amount,
		&i.IssueDate,
		&i.DueDate,
		&i.EntityID,
		&i.Status,
		&i.MovementID,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getTreasuryBalance = `-- name: GetTreasuryBalance :many
SELECT ba.id, ba.bank_name, ba.account_number,
       COALESCE(SUM(CASE WHEN tm.movement_type IN ('bank_deposit', 'check_received') THEN tm.amount ELSE 0 END), 0)::NUMERIC(16,2) AS total_in,
       COALESCE(SUM(CASE WHEN tm.movement_type IN ('bank_withdrawal', 'check_issued') THEN tm.amount ELSE 0 END), 0)::NUMERIC(16,2) AS total_out,
       COALESCE(SUM(CASE WHEN tm.movement_type IN ('bank_deposit', 'check_received') THEN tm.amount
                         WHEN tm.movement_type IN ('bank_withdrawal', 'check_issued') THEN -tm.amount
                         ELSE 0 END), 0)::NUMERIC(16,2) AS balance
FROM erp_bank_accounts ba
LEFT JOIN erp_treasury_movements tm ON tm.bank_account_id = ba.id AND tm.status = 'confirmed'
WHERE ba.tenant_id = $1 AND ba.active = true
GROUP BY ba.id, ba.bank_name, ba.account_number
ORDER BY ba.bank_name
`

type GetTreasuryBalanceRow struct {
	ID            pgtype.UUID    `json:"id"`
	BankName      string         `json:"bank_name"`
	AccountNumber string         `json:"account_number"`
	TotalIn       pgtype.Numeric `json:"total_in"`
	TotalOut      pgtype.Numeric `json:"total_out"`
	Balance       pgtype.Numeric `json:"balance"`
}

func (q *Queries) GetTreasuryBalance(ctx context.Context, tenantID string) ([]GetTreasuryBalanceRow, error) {
	rows, err := q.db.Query(ctx, getTreasuryBalance, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTreasuryBalanceRow{}
	for rows.Next() {
		var i GetTreasuryBalanceRow
		if err := rows.Scan(
			&i.ID,
			&i.BankName,
			&i.AccountNumber,
			&i.TotalIn,
			&i.TotalOut,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankAccounts = `-- name: ListBankAccounts :many
SELECT id, tenant_id, bank_name, branch, account_number, cbu, alias,
       currency_id, account_id, active, created_at
FROM erp_bank_accounts
WHERE tenant_id = $1 AND ($2::BOOLEAN = false OR active = true)
ORDER BY bank_name
`

type ListBankAccountsParams struct {
	TenantID   string `json:"tenant_id"`
	ActiveOnly bool   `json:"active_only"`
}

func (q *Queries) ListBankAccounts(ctx context.Context, arg ListBankAccountsParams) ([]ErpBankAccount, error) {
	rows, err := q.db.Query(ctx, listBankAccounts, arg.TenantID, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpBankAccount{}
	for rows.Next() {
		var i ErpBankAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BankName,
			&i.Branch,
			&i.AccountNumber,
			&i.Cbu,
			&i.Alias,
			&i.CurrencyID,
			&i.AccountID,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCashCounts = `-- name: ListCashCounts :many
SELECT id, tenant_id, cash_register_id, date, expected, counted, difference, user_id, notes, created_at
FROM erp_cash_counts WHERE tenant_id = $1 ORDER BY date DESC LIMIT $2 OFFSET $3
`

type ListCashCountsParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListCashCounts(ctx context.Context, arg ListCashCountsParams) ([]ErpCashCount, error) {
	rows, err := q.db.Query(ctx, listCashCounts, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpCashCount{}
	for rows.Next() {
		var i ErpCashCount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CashRegisterID,
			&i.Date,
			&i.Expected,
			&i.Counted,
			&i.Difference,
			&i.UserID,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCashRegisters = `-- name: ListCashRegisters :many
SELECT id, tenant_id, name, account_id, active, created_at
FROM erp_cash_registers WHERE tenant_id = $1 ORDER BY name
`

func (q *Queries) ListCashRegisters(ctx context.Context, tenantID string) ([]ErpCashRegister, error) {
	rows, err := q.db.Query(ctx, listCashRegisters, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpCashRegister{}
	for rows.Next() {
		var i ErpCashRegister
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.AccountID,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecks = `-- name: ListChecks :many
SELECT id, tenant_id, direction, number, bank_name, amount, issue_date, due_date,
       entity_id, status, movement_id, notes, created_at
FROM erp_checks
WHERE tenant_id = $1
  AND ($2::TEXT = '' OR direction = $2::TEXT)
  AND ($3::TEXT = '' OR status = $3::TEXT)
ORDER BY due_date
`

type ListChecksParams struct {
	TenantID        string `json:"tenant_id"`
	DirectionFilter string `json:"direction_filter"`
	StatusFilter    string `json:"status_filter"`
}

func (q *Queries) ListChecks(ctx context.Context, arg ListChecksParams) ([]ErpCheck, error) {
	rows, err := q.db.Query(ctx, listChecks, arg.TenantID, arg.DirectionFilter, arg.StatusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpCheck{}
	for rows.Next() {
		var i ErpCheck
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Direction,
			&i.Number,
			&i.BankName,
			&i.Amount,
			&i.IssueDate,
			&i.DueDate,
			&i.EntityID,
			&i.Status,
			&i.MovementID,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTreasuryMovements = `-- name: ListTreasuryMovements :many
SELECT tm.id, tm.tenant_id, tm.date, tm.number, tm.movement_type, tm.amount,
       tm.currency_id, tm.bank_account_id, tm.cash_register_id, tm.entity_id,
       tm.concept_id, tm.payment_method, tm.user_id, tm.notes, tm.status, tm.created_at,
       e.name AS entity_name
FROM erp_treasury_movements tm
LEFT JOIN erp_entities e ON e.id = tm.entity_id
WHERE tm.tenant_id = $1
  AND ($4::DATE IS NULL OR tm.date >= $4::DATE)
  AND ($5::DATE IS NULL OR tm.date <= $5::DATE)
  AND ($6::TEXT = '' OR tm.movement_type = $6::TEXT)
ORDER BY tm.date DESC, tm.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTreasuryMovementsParams struct {
	TenantID   string      `json:"tenant_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	DateFrom   pgtype.Date `json:"date_from"`
	DateTo     pgtype.Date `json:"date_to"`
	TypeFilter string      `json:"type_filter"`
}

type ListTreasuryMovementsRow struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       string             `json:"tenant_id"`
	Date           pgtype.Date        `json:"date"`
	Number         string             `json:"number"`
	MovementType   string             `json:"movement_type"`
	Amount         pgtype.Numeric     `json:"amount"`
	CurrencyID     pgtype.UUID        `json:"currency_id"`
	BankAccountID  pgtype.UUID        `json:"bank_account_id"`
	CashRegisterID pgtype.UUID        `json:"cash_register_id"`
	EntityID       pgtype.UUID        `json:"entity_id"`
	ConceptID      pgtype.UUID        `json:"concept_id"`
	PaymentMethod  pgtype.Text        `json:"payment_method"`
	UserID         string             `json:"user_id"`
	Notes          string             `json:"notes"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	EntityName     pgtype.Text        `json:"entity_name"`
}

func (q *Queries) ListTreasuryMovements(ctx context.Context, arg ListTreasuryMovementsParams) ([]ListTreasuryMovementsRow, error) {
	rows, err := q.db.Query(ctx, listTreasuryMovements,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.DateFrom,
		arg.DateTo,
		arg.TypeFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTreasuryMovementsRow{}
	for rows.Next() {
		var i ListTreasuryMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Date,
			&i.Number,
			&i.MovementType,
			&i.Amount,
			&i.CurrencyID,
			&i.BankAccountID,
			&i.CashRegisterID,
			&i.EntityID,
			&i.ConceptID,
			&i.PaymentMethod,
			&i.UserID,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.EntityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCheckStatus = `-- name: UpdateCheckStatus :execrows
UPDATE erp_checks SET status = $3
WHERE id = $1 AND tenant_id = $2
`

type UpdateCheckStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID string      `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateCheckStatus(ctx context.Context, arg UpdateCheckStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCheckStatus, arg.ID, arg.TenantID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
