// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Data      []byte             `json:"data"`
	Channel   string             `json:"channel"`
	IsRead    bool               `json:"is_read"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type NotificationPreference struct {
	UserID       string             `json:"user_id"`
	EmailEnabled bool               `json:"email_enabled"`
	InAppEnabled bool               `json:"in_app_enabled"`
	QuietStart   pgtype.Time        `json:"quiet_start"`
	QuietEnd     pgtype.Time        `json:"quiet_end"`
	MutedTypes   []string           `json:"muted_types"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID string `json:"id"`
}
