// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, title, body, data, channel)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, type, title, body, data, channel, is_read, read_at, created_at
`

type CreateNotificationParams struct {
	UserID  string `json:"user_id"`
	Type    string `json:"type"`
	Title   string `json:"title"`
	Body    string `json:"body"`
	Data    []byte `json:"data"`
	Channel string `json:"channel"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Data,
		arg.Channel,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.Channel,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPreferences = `-- name: GetPreferences :one
SELECT user_id, email_enabled, in_app_enabled, quiet_start, quiet_end, muted_types, updated_at
FROM notification_preferences
WHERE user_id = $1
`

func (q *Queries) GetPreferences(ctx context.Context, userID string) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, getPreferences, userID)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.EmailEnabled,
		&i.InAppEnabled,
		&i.QuietStart,
		&i.QuietEnd,
		&i.MutedTypes,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, type, title, body, data, channel, is_read, read_at, created_at
FROM notifications
WHERE user_id = $1 AND (NOT $3::bool OR is_read = false)
ORDER BY created_at DESC
LIMIT $2
`

type ListNotificationsParams struct {
	UserID     string `json:"user_id"`
	Limit      int32  `json:"limit"`
	UnreadOnly bool   `json:"unread_only"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Limit, arg.UnreadOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.Channel,
			&i.IsRead,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllRead = `-- name: MarkAllRead :execrows
UPDATE notifications SET is_read = true, read_at = now()
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) MarkAllRead(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, markAllRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRead = `-- name: MarkRead :execrows
UPDATE notifications SET is_read = true, read_at = now()
WHERE id = $1 AND user_id = $2 AND is_read = false
`

type MarkReadParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const notificationExistsByUser = `-- name: NotificationExistsByUser :one
SELECT EXISTS(SELECT 1 FROM notifications WHERE id = $1 AND user_id = $2)
`

type NotificationExistsByUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) NotificationExistsByUser(ctx context.Context, arg NotificationExistsByUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, notificationExistsByUser, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const purgeOldNotifications = `-- name: PurgeOldNotifications :execrows
DELETE FROM notifications
WHERE is_read = true AND created_at < now() - interval '90 days'
`

func (q *Queries) PurgeOldNotifications(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOldNotifications)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unreadCount = `-- name: UnreadCount :one
SELECT COUNT(*)::int FROM notifications
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) UnreadCount(ctx context.Context, userID string) (int32, error) {
	row := q.db.QueryRow(ctx, unreadCount, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertPreferences = `-- name: UpsertPreferences :one
INSERT INTO notification_preferences (user_id, email_enabled, in_app_enabled, quiet_start, quiet_end, muted_types, updated_at)
VALUES (
  $1,
  $2,
  $3,
  $4::time,
  $5::time,
  $6,
  now()
)
ON CONFLICT (user_id) DO UPDATE SET
  email_enabled = EXCLUDED.email_enabled,
  in_app_enabled = EXCLUDED.in_app_enabled,
  quiet_start = EXCLUDED.quiet_start,
  quiet_end = EXCLUDED.quiet_end,
  muted_types = EXCLUDED.muted_types,
  updated_at = now()
RETURNING user_id, email_enabled, in_app_enabled, quiet_start, quiet_end, muted_types, updated_at
`

type UpsertPreferencesParams struct {
	UserID       string      `json:"user_id"`
	EmailEnabled bool        `json:"email_enabled"`
	InAppEnabled bool        `json:"in_app_enabled"`
	QuietStart   pgtype.Time `json:"quiet_start"`
	QuietEnd     pgtype.Time `json:"quiet_end"`
	MutedTypes   []string    `json:"muted_types"`
}

func (q *Queries) UpsertPreferences(ctx context.Context, arg UpsertPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertPreferences,
		arg.UserID,
		arg.EmailEnabled,
		arg.InAppEnabled,
		arg.QuietStart,
		arg.QuietEnd,
		arg.MutedTypes,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.EmailEnabled,
		&i.InAppEnabled,
		&i.QuietStart,
		&i.QuietEnd,
		&i.MutedTypes,
		&i.UpdatedAt,
	)
	return i, err
}
